### ISSUE TITLE
Month range is not compatible

### ISSUE THREAD

**Issue by deeeki** [kelektiv/node-cron#108]
The range for the month is not compatible with the original cron.

crontab man page says:

>  month         1-12 (or names, see below)
> http://www.unix.com/man-page/linux/5/crontab/

So node-cron should follow the original range.

**Comment by dule** [comment]
An option to use unix cron format would be nice, particularly if the cron string is generated. Otherwise, I now have to parse my cron string, adjust the month, and rebuild my string to feed it into node-cron.

**Comment by tylerlong** [comment]
Could we just add an option to trigger the unix cron mode? This library is the only one that use 0-11  for months, all others use 1-12. So it is not cool because it's too special.

**Comment by tylerlong** [comment]
@dule I have to do exactly the same, could you please share with me some sample code?

**Comment by tylerlong** [comment]
He is a workaround for the problem:

```
npm install cron-converter --save
```

```js
var Cron = require('cron-converter');

var cronInstance = new Cron({
  outputMonthNames: true
});

var pattern = '* * * 9 *';
pattern = cronInstance.fromString(pattern).toString();
console.log(pattern); // * * * SEP *
```

We changed month number to month name, then it's working fine with this library.
