### ISSUE TITLE
Context gets lost

### ISSUE THREAD

**Issue by milani** [kelektiv/node-cron#172]
I'm using `node-cron` in a script for hubot. Here is the code:

```
  # robot.brain.data exists here in outer context
  .
  .
  .
  noUpdateAlertJob = new CronJob '0 0 9-16 * * 0-4,6', =>
    robot = this
    # robot.brain is undefined here.
    users = robot.brain.data.users or {}
  , null, true, TIMELINE_ALERT_TIMEZONE, robot
```

I receive `ERROR TypeError: Cannot read property 'data' of undefined`. I made sure `robot.brain.data` exists in the outer context. Have any idea what is happening?

**Comment by lags** [comment]
For clarify concept, this snipped (found on google groups) explain your problem
```
var functionX = function() {
  var self = this;
  var functionY = function(y) {
    // If we call "this" in here, we get a reference to functionY,
    // but if we call "self" (defined earlier), we get a reference to
    // function X.
  }
}
```
because when you define:
```
robot = this
```
'this' has reference to CronJob function...

You could try to remove this, if robot is global, otherwise you need declare robot's scope as 'self' and use it later... For example:
```
# robot.brain.data exists here in outer context - in this scope you could use
var self = this;
  .
  .
  .
  noUpdateAlertJob = new CronJob '0 0 9-16 * * 0-4,6', =>
    robot = self # now 'self' get a reference to outer context then you must ensure that robot is present
    # robot.brain is undefined here.
    users = robot.brain.data.users or {}
  , null, true, TIMELINE_ALERT_TIMEZONE, robot
``` 
I hope is clear :)

**Comment by milani** [comment]
@lags No it is not the case. as you see, the last argument is the context of cron function. So `this`, should refer to `robot` inside the callback function.

**Comment by ncb000gt** [comment]
@mil That's strange. I have testing specifically for this case which seems to be passing.

https://github.com/ncb000gt/node-cron/blob/master/tests/test-cron.js#L440

Do the tests run fine for you? What version of cron are you running?

**Comment by ncb000gt** [comment]
Closing due to age. Can create a new ticket if it comes up again.
