### ISSUE TITLE
Know last tick

### ISSUE THREAD

**Issue by lags** [kelektiv/node-cron#173]
Hi,
I'm using node-cron with these parameter:

```
arr.push(new CronJob({
  cronTime: '*/5 30 11 * * *',
  onTick: function() {
    console.log('tick');
  },
  start: true,
  timeZone: 'Europe/Rome'
}));
```

For one minute at 11.30am every five seconds do tick function.
60 / 5 = 12 ticks.
This work correctly but is possible know last tick (twelfth in this case) and launch another function?
Any other approach is pleasing. Many thanks.

**Comment by royhowie** [comment]
https://www.npmjs.com/package/cron#api

>onComplete - [OPTIONAL] - A function that will fire when the job is complete, when it is stopped.

**Comment by lags** [comment]
Thanks for reply royhowie.
But onComplete function don't fire never because this task doesn't stop never.

For example: I must create a task which work at hour and minute fixed but every X second. I try to use function onComplete but it not fire after 12th tick (60 / 5 = 12) because how to use function stop at 12 ?

**Comment by ncb000gt** [comment]
@lags You can't do this with the `onTick` method?

`onTick` fires, you check `new Date().getSeconds()`, if criteria match, create a new job or do whatever you want to do?

**Comment by ncb000gt** [comment]
Closing due to age. Can create a new ticket if it comes up again.
