### ISSUE TITLE
pass parameters into onTick function

### ISSUE THREAD

**Issue by DmitryEfimenko** [kelektiv/node-cron#178]
I know there is [this issue](https://github.com/ncb000gt/node-cron/issues/47), but I feel that a better job could be done with this.
Instead of setting context (which would make `this.stop()` be unavailable), why not add another property to the `CronJob` object - `params`?
Example:

``` javascript
var myParams = { myText: 'this params could be any JSON' };

var job = new CronJob({
  cronTime: '00 30 11 * * 1-5',
  params: myParams,
  onTick: function(p) {
    console.log(p.myText);
  },
  start: false,
  timeZone: 'America/Los_Angeles'
});
```

**Comment by ncb000gt** [comment]
I'd be open to this and would entertain a PR for it. Thanks!

**Comment by ncb000gt** [comment]
Closing due to age. Can create a new ticket if it comes up again.

**Comment by ncb000gt** [comment]
For reference, you should be able to bind parameters to your `onTick` function.
