### ISSUE TITLE
Cron pattern is not executing on minutes correctly */32

### ISSUE THREAD

**Issue by JADurham909** [kelektiv/node-cron#179]
I have a cron job set to */32 \* \* \* \* that is running with the following patttern:

2015-06-29T13:00:32.779Z BEGINS
2015-06-29T13:32:00.833Z KICKED
2015-06-29T14:00:07.236Z KICKED
2015-06-29T14:32:00.886Z KICKED
2015-06-29T15:00:00.914Z KICKED

You can see its running at 0 and 32 minutes on the hour respectively.  It should be executing with 32 minutes between each run.

```
DailySalesImport.prototype.scheduleDailySalesSync = function (callback) {
    try {
        var self = this;
        logger.info('daily sales cron', this.cron);
        new CronJob({
            cronTime: this.cron,
            onTick: function () {
                logger.info('Starting daily sales sync ', {startDate: new Date()});
                self.performDailySalesSync(callback);
            },
            start: true,
            timeZone: 'America/Los_Angeles'
        });
    } catch (ex) {
        callback('Daily sales sync cron pattern not valid');
    }
};
```

info: Starting import process
info: Scheduling daily sales sync...
info: daily sales cron */32 \* \* \* *

**Comment by ncb000gt** [comment]
Yea. This is definitely an issue. I put a test in that fails. I'll push up a fix at some point. Thanks!

**Comment by ncb000gt** [comment]
Closing due to age. Can create a new ticket if it comes up again.

I'm not sure if this got fixed at some point over the last few years, but all tests are passing.
