### ISSUE TITLE
Change the cron job time after executing once/every execution 

### ISSUE THREAD

**Issue by kishanrajdev** [kelektiv/node-cron#186]
I want to change the cronTime once it is executed.  Here is my code

```
var time = '*/20 * * * * *';
job = new CronJob(time, function() {
    /* runs once at the specified date. */
      //this.stop();
      this.setTime('00 * * * * *');      //to change the timing of next run 
    }, function () {
      this.start();
    },
    true /* Start the job right now */
);
```

Changes I have done in library to make this work is 

```
CronJob.prototype.setTime = function(time) {
    if (!(time instanceof CronTime)) time = new CronTime(time);  //before it was a throw error
    this.stop();
    this.cronTime = time;
}
```

This works fine except for the case,  it executes the cronjob twice on the time which was set for the first time and then start running on the new time set (i.e.) cron job will run for 20 secs twice and then runs for every minute.

Can you please comment on the changes which i have made and the issue i have highlighted?

**Comment by ncb000gt** [comment]
I'm not entirely sure I understand the issue with the double execution. Can you post some printout?

You could approach this a different way too.

    function createJob(time) {
        new CronJob(time,
            function() {
              this.stop();
              createJob('00 * * * * *');
            }, function () {
              this.start();
            },
            true);
    }

And then just call createJob once. Alternatively, you could make it so that you pass in a specific date rather than passing in the repeatable cronjob syntax.

**Comment by dudumiquim** [comment]
I have the same question. How can I change the execution time after the job started:
Example:

```
var CronJob = require('cron').CronJob;
var job = new CronJob('*/2 * * * * *', function () {
        // [...]
        job.magic('*/10 * * * * *'); //How to change the job to run each 10 seconds instead 2 seconds while the job run?
    },
    null, true, 'America/Sao_Paulo'
);
```

**Comment by ncb000gt** [comment]
You can use `setTime` on the job after execution. The job needs to be restarted as it is stopped when the time is changed using this method.
