### ISSUE TITLE
Infinite loop while using specific pattern

### ISSUE THREAD

**Issue by pedropapa** [kelektiv/node-cron#191]
Hello,
Recently in an issue (https://github.com/NodeBB/NodeBB/issues/3696) on nodebb project we discovered that a specific pattern on node-cron can make the nodejs thread run in infinte loop, consuming 100% of server's CPU.

The specific pattern is "0 0 17 1 \* *", like you can see in the issue I referenced here changing this pattern to any other valid pattern solves the problem.

node-cron version: 1.0.9, also tested in 1.0.5 version.

**Comment by ncb000gt** [comment]
Sorry this is so late but I'll take a look and see what I can find. We had something similar to this come up a bit ago but I had some testing in around that which ended up being related to the values being out of bounds.

I don't seem to be able to reproduce it though. I started my job automatically and  put some logging after the job was init'd and started. I'm getting printing. =\

Anyway, this doesn't appear to be like that at all.

**Comment by hogewest** [comment]
Looped infinitely with the following pattern.

```js
$ node
> var CronJob = require('cron').CronJob;
undefined
> var job = new CronJob('0 0 30 1 *', function() {});
Month '1' is limited to '29' days.
undefined
> job.start();
// Infinite loop...
```

node-cron version: 1.2.1
