### ISSUE TITLE
Pattern came into infinit loop.

### ISSUE THREAD

**Issue by JhonataRibeiro** [kelektiv/node-cron#194]
I use this pattern  '00 00 00 \* \* *'  (that must run every day at midinight). But it entered in infinit loop.

 var CronJob = require('cron').CronJob;
  new CronJob('00 00 00 \* \* *', function() {
    CheckSomething();
  },null, true, null);

Any suggestion?

**Comment by ncb000gt** [comment]
Closing due to age. Can create a new ticket if it comes up again.
