### ISSUE TITLE
Today is 2015.10.30,but cron error is "Month '1' is limited to '29' days"

### ISSUE THREAD

**Issue by zhenlovezhen2012** [kelektiv/node-cron#196]
Today is 2015.10.28,but cron error is "Month '1' is limited to '29' days",
My cron string is 38 11 10 30 \* \* .

I don't know why,when I use this string " 38 11 10 30  9  \* ",it works fine;

My cron : 1.0.9

**Comment by andela-asolomon** [comment]
You can just do this `38 11 10 29,30 * *`.... from [crontab](http://crontab.org/)

Because 1 is February with 29 days doing it like that works for both i guess

**Comment by jasonmendes** [comment]
The month ranges from 0 to 11, so month 1 would be February

**Comment by ncb000gt** [comment]
Closing due to age. Can create a new ticket if it comes up again.
