### ISSUE TITLE
What would be the crontime syntax to run a job every second?

### ISSUE THREAD

**Issue by thelinuxlich** [kelektiv/node-cron#203]

**Comment by fatihky** [comment]
You can use first example https://github.com/ncb000gt/node-cron#usage-basic-cron-usage

**Comment by matteocontrini** [comment]
This should be closed

**Comment by 360disrupt** [comment]
If you can skip positions from the left side (which I did not test), you could leave out the seconds out. Then this resource might be helpful:
http://crontab.guru/

**Comment by hibangun** [comment]
* * * * * *
