### ISSUE TITLE
Time changes in some countries!

### ISSUE THREAD

**Issue by github4f** [kelektiv/node-cron#204]
I am looking for an accurate job schedule that can be able to consider the leap years as well as time change (+-1 in some countries to save energy). I am not sure your package supports these feature. Could you please comment on that. tnx

**Comment by andrebower** [comment]
Time change will cause double execution or no execution of the task, if the time is set between the critical range (I think most servers change from 02:00 to 03:00 and from 03:00 to 02:00).

**Comment by ncb000gt** [comment]
Closing due to age. Can create a new ticket if it comes up again.
