### ISSUE TITLE
Expose method to test or compare a specific time against a cron expression

### ISSUE THREAD

**Issue by anandanand84** [kelektiv/node-cron#206]
Below is the use case, lets say I wanted to start a process in the morning and stop it in the evening  I would use below

```
new CronJob('00 00 09 * * 1-5', function() {
    Start();
  }, null, true, 'America/Los_Angeles');

  //StopSession
  new CronJob('00 00 15 * * 1-5', function() {
    Stop();
  }, null, true, 'America/Los_Angeles');
```

But say the application is restarted for some reason in the middle, then I should be able to identify that using  the expression

```
var time  = new Date().getTime();

if(new CronTime('* * 09-15 * * 1-5').test(time)){
start();
}


```

**Comment by ncb000gt** [comment]
Closing due to age. Can create a new ticket if it comes up again.
