### ISSUE TITLE
Feature Request: Get more information about a Job

### ISSUE THREAD

**Issue by mchavarriae** [kelektiv/node-cron#208]
Hi

Thanks for share this node-cron package, I'm wondering if there is a way to get information about the job? Basically I want to know if it's active and the next tick.

Thanks

**Comment by ncb000gt** [comment]
Currently there isn't but that would definitely be useful. I'd accept a PR for this.

**Comment by mchavarriae** [comment]
Great. I will try to work on it

**Comment by mickaeltr** [comment]
I'd love to have a human-readable time attached to the cron object.
Something like `cronJob.getHumanTime()` which would return "Every minute" for instance.
See [prettycron](https://www.npmjs.com/package/prettycron), which does this but does not support the cron time format starting with seconds.

**Comment by ncb000gt** [comment]
Closing due to age. Can create a new ticket if it comes up again.

I like the suggestion though @mickaeltr maybe I'll get to it one of these days... *hah*. ;D
