### ISSUE TITLE
Does not seem to be firing on the correct interval

### ISSUE THREAD

**Issue by thisboyiscrazy** [kelektiv/node-cron#209]
```
"use strict"

const should = require('should');
const sinon = require('sinon');

const m60 = 60 * 60 * 1000;

const CronJob = require('cron').CronJob;

describe('Cron',function () {

  it('should fire every 60 min', function () {
    let clock = sinon.useFakeTimers();
    let l = []
    let c = new CronJob('00 30 * * * *',function () {
      l.push(Math.floor(Date.now() / 60000));
    },null,true);

    clock.tick(m60);
    clock.tick(m60);
    clock.tick(m60);
    clock.tick(m60);
    clock.tick(m60);

    console.log(l);
    l.length.should.equal(5);

  });
});
```

Should result in a array of 5 with values close to multiple of 30

I get

```
  Cron
[ 23, 47, 71, 95, 118, 142, 166, 190, 213, 237, 261, 285 ]
    1) should fire every 60 min


  0 passing (77ms)
  1 failing

  1) Cron should fire every 60 min:

      AssertionError: expected 12 to be 5
      + expected - actual

      -12
      +5

      at Assertion.fail (node_modules/should/lib/assertion.js:91:17)
      at Assertion.Object.defineProperty.value (node_modules/should/lib/assertion.js:163:19)
      at Context.<anonymous> (test/cron.js:26:21)
```

**Comment by mike-aungsan** [comment]
I am having the same issue. cron@1.1.0

    var testCronJob = new CronJob(
        '* 0,10,20,30,40,50 * * * *', 
        function () {
          console.log('onTick %s', new Date());
          console.log('');
        
          // have to call stop from onTrick
          //testCronJob.stop()
        },
        function () {
          // this function is only called if testCronJob.stop() explicitly
          console.log('onComplete');
        },
        true,
        'America/Los_Angeles'
    );

onTick Tue Feb 23 2016 14:50:59 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:00 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:01 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:02 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:03 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:04 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:05 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:06 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:07 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:08 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:09 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:10 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:11 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:12 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:13 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:14 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:15 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:16 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:17 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:18 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:19 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:20 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:21 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:22 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:23 GMT-0800 (PST)


onTick Tue Feb 23 2016 15:00:25 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:26 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:27 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:28 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:29 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:30 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:31 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:32 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:33 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:34 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:35 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:36 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:37 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:38 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:39 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:40 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:41 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:42 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:43 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:44 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:45 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:46 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:47 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:48 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:49 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:50 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:51 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:52 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:53 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:54 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:55 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:56 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:57 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:58 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:00:59 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:00 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:01 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:02 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:03 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:04 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:05 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:06 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:07 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:08 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:09 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:10 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:11 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:12 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:13 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:14 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:15 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:16 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:17 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:18 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:19 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:20 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:21 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:22 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:23 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:24 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:25 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:26 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:27 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:28 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:29 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:30 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:31 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:32 GMT-0800 (PST)


onTick Tue Feb 23 2016 15:10:33 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:34 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:35 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:36 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:37 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:38 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:39 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:40 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:41 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:42 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:43 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:44 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:45 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:46 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:47 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:48 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:49 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:50 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:51 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:52 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:53 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:54 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:55 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:56 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:57 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:58 GMT-0800 (PST)

onTick Tue Feb 23 2016 15:10:59 GMT-0800 (PST)


The following suppose to be fired every 10 mins.

    var testCronJob = new CronJob(
        '* */10 * * * *', 
        function () {
          console.log('onTick %s', new Date());
          console.log('');
          
          // have to call stop from onTrick
          //testCronJob.stop()
        },
        function () {
          // this function is only called if testCronJob.stop() explicitly
          console.log('onComplete');
        },
        true,
        'America/Los_Angeles'
    );

**Comment by hellerve** [comment]
Relatedly (?) I have a job running at 6pm on fridays (i.e. `00 00 18 * * 5`), but today it fired at 8:06AM. I am unsure as of how to debug or resolve this.

**Comment by ncb000gt** [comment]
@thisboyiscrazy i took your test and added it to the suite- thanks for that.

However, I'm not seeing this locally. We'll see if travis catches anything as well...otherwise I'm not sure what would be causing the issue you are seeing.

@hellerve That's just weird...that shouldn't happen, obviously. Could something have happened to the date on the system of the machine to have caused something like this to happen? Were you able to pinpoint a cause?

**Comment by erikman** [comment]
I think I have found an issue with double zero that could be related. For me

```
var job = cron.schedule('00 * * * * *', () => {
  console.log('exec now!');
});
job.start();
```

doesn't work, but with `0` instead of `00` it works.

**Comment by ncb000gt** [comment]
Closing due to age. Can create a new ticket if it comes up again.

I added a test for the double 0 and it seems to work in the tests... =\
