### ISSUE TITLE
Handle a date that is now or in the past

### ISSUE THREAD

**Issue by jtwebman** [kelektiv/node-cron#213]
If I set the time to new Date() or a date in the past the job never runs. I would think you would then just fire the call the one time. Is there a reason for this or is this a bug?

**Comment by ncb000gt** [comment]
By the time the code fires, `new Date()` would be in the past. It's not exactly a bug, but it is a bit unexpected. This is probably something that can be handled pretty easily. I'll take a look at it when I get some time, otherwise I'd accept a pr with some testing. :)

**Comment by ncb000gt** [comment]
Closing due to age. Can create a new ticket if it comes up again.
