### ISSUE TITLE
Too many cron job cause Fatal error: watch ENOSPC

### ISSUE THREAD

**Issue by fransiskapw** [kelektiv/node-cron#215]
Hi there,

We're setting many cronjob in our system. It was ok when we set up to 8 cron jobs. Lately we add more and have up to 12cron jobs, and the node server just won't start. The nodemon gave watch ENOSPC error

Do you have idea what cause the problem? And how to prevent it?

**Comment by ncb000gt** [comment]
That's a little strange. ENOSPC is a `no space` error. I'm not entirely sure why cron would be causing that...it seems as though it shouldn't. What are your jobs doing?

**Comment by ncb000gt** [comment]
Closing due to age. Can create a new ticket if it comes up again.
