### ISSUE TITLE
Multiple Cron Jobs

### ISSUE THREAD

**Issue by gcperrin** [kelektiv/node-cron#217]
I've noticed other issues regarding this, but multiple scheduled jobs do not seem to work in all cases (LTS Node v4.xx). Example can be seen below...I understand there could be a buried issue but the code within these jobs is not complex (one checks mongo and sends email on condition, one cleans temp folder).

``` javascript
new CronJob('* 1 * * * *', function() {
        // Stuff here 
    }, null, true, 'America/Chicago');

new CronJob('* 5 * * * *', function() {
       // More stuff here
    }, null, true, 'America/Chicago');
```

The debug statements placed in these functions do not fire. The first one was working fine, when I added a second neither seem to fire.

Thanks,
G

**Comment by SEAPUNK** [comment]
Running this code:

```
const CronJob = require('cron').CronJob

const cron1 = new CronJob('1 * * * * *', function () {
  console.log('1')
}, null, true, 'America/Chicago');

const cron2 = new CronJob('5 * * * * *', function () {
  console.log('5')
}, null, true, 'America/Chicago');
```

Both cronjobs run just fine. First cronjob runs on the first second of every minute,  and the second cronjob runs on the 5th second of every minute.

**Comment by gcaraciolo** [comment]
This could be more explicit in the documentation

**Comment by ncb000gt** [comment]
As @SEAPUNK mentioned, this should work fine without issues, but without seeing your code or a scrubbed version of it, I can't say for sure that it isn't your code.

@gcaraciolo _what_ could be more explicit in the documentation?

**Comment by calebeaires** [comment]
@ncb000gt, @SEAPUNK - On the example above, the cron does not work. I create an cronJob instance to each item of the some links and save then on array.

```javascript
const _jobs = []

// start jobs with its params
start(jobsToDoList){
       _jobs = [];
       jobsToDoList.forEach((process, key) => {
          this._runSchedule(process, key);
        });
}

// schedule
_runSchedule(process, key) {
    _jobs[key] = new CronJob(process.cron, function () {
      // here I do task based on the user 
      this.executeTaskByProcessParams(process.params);
    }, null,
      true, 'America/Sao_Paulo'
    );
}


// ... more code here


```

**Comment by SEAPUNK** [comment]
the snippet with

```js
/* process.cron, */ function () {
  /* --> */ this.someFn();
}
```

is likely your problem; the value of `this` has likely changed during callback, so you either need to use bound functions

```js
_jobs[key] = new CronJob(...args, () => {
  this.executeTaskbyProcessParams();
});
```

or keep a persistent reference of `this`:

```js
_runSchedule() {
  const self = this;
  _jobs[key] = new CronJob(...args, function () {
    self.executeTaskbyProcessParams();
  });
}
```

ref: [this in javascript](https://dmitripavlutin.com/gentle-explanation-of-this-in-javascript)

**Comment by calebeaires** [comment]
the word `this`  were my mistake when typing here, on my code it is `self.executeTaskbyProcessParams()`.

My issue is that just one cron schedule runs, but others dont when I create then througth an loop to put then on a array.

**Comment by SEAPUNK** [comment]
and what is the list of cron strings being used?

**Comment by calebeaires** [comment]
I use the foreach just to pass the `cron` and some param that is used on a function executed when the cron time is executed.

```javascript

const jobsToDoList = [{
 params: ['chartBase', 'table'],
cron: '10 5 * * *'
},
{
  params: ['chartBase', 'tableOne'],
cron: '10 6 * * *'
}]

```

**Comment by SEAPUNK** [comment]
just ran this code, and it worked completely fine for me:

![screen shot 2017-12-06 at 10 41 18 am](https://user-images.githubusercontent.com/4400726/33678882-096c8740-da72-11e7-8212-702767dbf035.png)

**Comment by calebeaires** [comment]
Thanks, your example make me review my entire code, then I could fix.

**Comment by ncb000gt** [comment]
@calebeaires does that clear things up for you so that I can close this ticket?

@SEAPUNK thanks for helping!

**Comment by calebeaires** [comment]
Close it! Everthing make sense right now!
