### ISSUE TITLE
Cron firings tie up event loop

### ISSUE THREAD

**Issue by klinquist** [kelektiv/node-cron#218]
I have a node script which manages a large number of schedules.   At a specific time, thousands of schedules may fire.

I also have a 'keepalive/heartbeat' (in a setInterval) which is required.  When the crons fire, my keepalive hangs up.

**My code is being blocked for 40 seconds**

In other scripts I am able to bring the next execution of a function to the top of the event loop by wrapping things in setImmediate.  Can't quite figure out how to do this in node-cron in order for my tests to pass.

```
    var CronJob = require('cron').CronJob;
    var util = require('util');
    util.log("Scheduling 5000 crons");
    for (var i = 0; i < 5000; i++) {
        new CronJob('00 02 18 * * *', null, null,
            true, /* Start the job right now */
            'America/Los_Angeles' /* Time zone of this job. */
        );
    }
    util.log("Ok");

    var p = new Date().getTime();
    setInterval(function () {
        p = p + 5000;
        var difference = new Date().getTime() - p;
        util.log("Difference between expected & actual: " + difference)
    }, 5000);
```

Output log:

```
22 Feb 18:01:39 - Scheduling 5000 crons
22 Feb 18:01:41 - Ok
22 Feb 18:01:46 - Difference between expected & actual: 3
22 Feb 18:01:51 - Difference between expected & actual: 3
22 Feb 18:01:56 - Difference between expected & actual: 10
22 Feb 18:02:42 - Difference between expected & actual: 40888
22 Feb 18:02:47 - Difference between expected & actual: 40890
```

**Comment by ncb000gt** [comment]
Yea. That seems like it would do it. I'm guessing that the event loop is getting overloaded with too many functions firing at the same time.

That's one of the hard things to try to "cover". I could spawn workers and have the functions fire in workers, but that takes cycles to do and would mean that the job probably wouldn't fire when you wanted it to.

It may make more sense to have cron processors for types of schedulings. For instance, all `token removal tasks run in cron instance 1 within node process 1` and so on for your other types (without knowing exactly what you are doing it's hard to know if this makes any sense).

Does that help?

**Comment by ncb000gt** [comment]
Closing due to age. Can create a new ticket if it comes up again.
