### ISSUE TITLE
jobs not running after long inactivity on Raspberry PI

### ISSUE THREAD

**Issue by GuillaumeNachury** [kelektiv/node-cron#220]
Hi,
I'm having a weird issue with my scheduled jobs on Raspberry after a long incativity.

On my RPI I have a simple nodeJS application that provide a REST api (which actually provide logs of the scheduled jobs) and run 2 jobs a day (00 45 6 \* \* \* and 00 00 8 \* \* *).

After a long inactivity on my RPI, the job never run... actually they will run as soon a HTTP request arrive on the REST API (which are not related)

e.g. I start my nodeJS app at 13:00:00, and wait until the day after. At 6:45:00 the job won't run, but if request the api to get the logs at, let's say, 7:03:00 the 6:45 will run.....

Is there anything that could prenvent / suspend the jobs from runninng ?

Thnaks,
G.

**Comment by nedium** [comment]
Does anyone have any thoughts on this?

**Comment by nidhind** [comment]
Try to turn off all power saving features in your os

**Comment by Connor-Knabe** [comment]
@GuillaumeNachury I've had this issue before as well you a workaround I've found seems to do the trick is to have a setInterval(function(){},5*60*1000); keep it "awake".

**Comment by ncb000gt** [comment]
This may be related to #231 and #232.

**Comment by ncb000gt** [comment]
Closing due to age. Can create a new ticket if it comes up again.
