### ISSUE TITLE
The module crashes if you pass a moment date object instead of a JavaScript date object.

### ISSUE THREAD

**Issue by swmcdonnell** [kelektiv/node-cron#224]
I made a change and submitted a pull request that fixes the problem and accepts either a moment or JavaScript date object.

**Comment by ncb000gt** [comment]
Did you remove the pr for this?

**Comment by swmcdonnell** [comment]
No, here it is. Maybe it's in the wrong place?
https://github.com/swmcdonnell/node-cron/pull/2

**Comment by ncb000gt** [comment]
Well, finally merged this in. :D Sorry for the delay.
