### ISSUE TITLE
What would be the cron-time syntax to run a job every 24 minuts?

### ISSUE THREAD

**Issue by rizvanhaider** [kelektiv/node-cron#225]
I am writing a crone job where user specifies the time but when I do it by (*/24 \* \* \* *) it will run two times after 24 minuts and 1 time after 36 minuts. how should I handle this scenario.?

**Comment by PrinceToch** [comment]
Please check your code after you run cronjob

**Comment by rizvanhaider** [comment]
it also executes when minutes are 00 i.e when time is 10:00:00

**Comment by GJ2511** [comment]
@rizvanhaider 

You probably need :-
`0 */10 * * * *`

**Comment by ncb000gt** [comment]
@rizvanhaider `*/24 * * * *` should run what you want, when you say after 36 minutes do you mean the ontick fires on the 36th minute?

I have just created two tests that use `0 */24 * * * *` and `*/24 * * * *` and they work fine for me. I'm not sure why you would be experiencing what you are...

Are you still having this issue?

**Comment by ncb000gt** [comment]
Closing due to age. We can create a new ticket if still an issue.
