### ISSUE TITLE
Wanna start the job each 05 minutes but not work

### ISSUE THREAD

**Issue by danghoaidanh** [kelektiv/node-cron#230]
I did something like 

var CronJob = require('cron').CronJob;
new CronJob('\* 05 \* \* \* *', function() {
  console.log('You will see this message every second');
}, null, true, 'America/Los_Angeles');

**Comment by GJ2511** [comment]
@danghoaidanh 

You probably need this:-

`cronTime: '0 */5 * * * *'`

**Comment by bertolo1988** [comment]
@GJ2511 can this get a bit more clearer in the documentation ? I see alot of similar issues. I was having one issue of these aswell.

**Comment by ncb000gt** [comment]
I added some documentation around running jobs every X number of minutes as an example. Thanks for the suggestion @bertolo1988 and sorry in the delay.
