### ISSUE TITLE
Increase in milliseconds

### ISSUE THREAD

**Issue by jdnichollsc** [kelektiv/node-cron#241]
Hi guys,

Testing executing a task every second using the cron "\* \* \* \* \* *", we can detect an issue with the milliseconds, see the issue in the log please: http://screencast.com/t/MWrT4SG0XhMS
[debug.txt](https://github.com/ncb000gt/node-cron/files/404063/debug.txt)

Thanks for all, this Node.js module is very useful! :dancers:

**Comment by ncb000gt** [comment]
Thanks. I'll try to dig into this when I get a chance.

**Comment by ncb000gt** [comment]
I've been running the latest `@1.4.0` for a while and am not seeing any drifting with the latest code changes. I'm going to close this due to that. We can open a new ticket if this does appear to be an issue.
