### ISSUE TITLE
onTick is called earlier if time was shifted back

### ISSUE THREAD

**Issue by alexey-komarov** [kelektiv/node-cron#249]
If I have a cron expression "*/10 \* \* \* \* *" and set my system time back for 2 seconds, onTick callback is called twice (e.g first time at 38 seconds and second time at 40 seconds).

I understand, it's expected behavior but Initially I faced with this issue because node.js on my VM guest may fire setTimeout callback a bit earlier (I don't know the reason why it's happen, ntpd and vmware-tools are off).

So, I looked into the cron.js code and found that it can be easily fixed, all that we need is just save current time before calling setTimeout and then in callbackWrapper do something like this:

``` javascript
        var diff = startTime + timeout - Date.now();

        if (diff > 0) {
                var newTimeout = self.cronTime.getTimeout();

                if (newTimeout > diff) {
                        newTimeout = diff;
                }

                remaining += newTimeout;
        }
```

**Comment by ncb000gt** [comment]
Mind putting together a PR with some testing for this? This would definitely help wrt DST issues too.

**Comment by ChrisCinelli** [comment]
Related to: #180

**Comment by jackhftang** [comment]
#243 same problem

**Comment by ncb000gt** [comment]
Closing due to age. We can create a new ticket if still an issue.
