### ISSUE TITLE
Unable to set Job IDs

### ISSUE THREAD

**Issue by minessis** [kelektiv/node-cron#251]
I would like to be able to stop jobs at a later time using a unique job id. I don't see that this is currently possible. Is there any chance of this being implemented?

**Comment by ncb000gt** [comment]
It would be great to have this implemented but I barely have time to maintain the project let alone add the feature. I'd definitely accept a PR with tests though. :)

**Comment by CowPanda** [comment]
@minessis You can wrap job with a function return cron job instance  and define callback when cron job trigger `onTick` , in your callback custom your job id or do something.

**Comment by ncb000gt** [comment]
Closing due to age. We can create a new ticket if still an issue.

**Comment by azakero** [comment]
> I would like to be able to stop jobs at a later time using a unique job id. I don't see that this is currently possible. Is there any chance of this being implemented?

Hey could you do it?
