### ISSUE TITLE
Support for @reboot? 

### ISSUE THREAD

**Issue by ysyyork** [kelektiv/node-cron#256]
I am wondering if this lib support @reboot jobs? From the API, it requires a crontime, I don't know how to specify @reboot. Thanks

**Comment by ncb000gt** [comment]
It doesn't support `@reboot`. That kind of functionality would be akin to:

```
function work() {
    console.log('do something');
}

new CronJob('* * * * * *', work, null, true); //job to call periodically
work(); //called immediately
```
