### ISSUE TITLE
Moment Timezone 0.5.7 was already loaded with data from 2016h

### ISSUE THREAD

**Issue by adrianvlupu** [kelektiv/node-cron#257]
Hi, I am trying to use Sequelize inside a CronJob but I can't get past the error "Moment Timezone 0.5.7 was already loaded with data from 2016h".

I am not specifying any timezone for both the 'cron' or 'sequelize' module.
new cron.CronJob('* * * * * *', () => {
    console.log('running');
}, null, true);

I tried adding a timezone to both but the error remains. No ideea what to do next. Searched StackOverflow but found nothing :(

**Comment by ncb000gt** [comment]
It looks like this is an issue with moment-timezone.

https://github.com/moment/moment-timezone/issues/231

Linking for more info.

**Comment by ncb000gt** [comment]
Closing due to age. We can create a new ticket if still an issue.
