### ISSUE TITLE
How to avoid 2 tasks run parallel. 

### ISSUE THREAD

**Issue by MaggieNgWu** [kelektiv/node-cron#258]
I would like to run 2 tasks with different cron-time, both these two tasks would connect database and modify data. But I would like to guarantee just one task is running at any time. What should I do?

**Comment by MaggieNgWu** [comment]
var task1=new CronJob('* * * * *',function(){
     mongoose.connect(url);
     doSomthing(function(){
           mongoose.connection.close();
     });   
});

var task2=new CronJob('*/5 * * * *',function(){
     mongoose.connect(url);
     doSomthing(function(){
           mongoose.connection.close();
     });   
});

How to avoid "Try to open an unclosed connection"

**Comment by MaggieNgWu** [comment]
`var task1=new CronJob('* * * * *',function(){
       mongoose.connect(url);
       doSomthing(function(){
           mongoose.connection.close();
       });
});

var task2=new CronJob('*/5 * * * *',function(){
     mongoose.connect(url);
     doSomthing(function(){
           mongoose.connection.close();
     });
});

`
How to avoid "Try to open an unclosed connection"

**Comment by MaggieNgWu** [comment]
`var task1=new CronJob('* * * * *',function(){
mongoose.connect(url);
doSomthing(function(){
mongoose.connection.close();
});
});

var task2=new CronJob('*/5 * * * *',function(){
mongoose.connect(url);
doSomthing(function(){
mongoose.connection.close();
});
});`

**Comment by DivineGod** [comment]
You should implement the use of a mutex or a locking system. Depending on requirements this can be done in different ways. `node-cron` does not contain any features to ensure jobs aren't run at the same time.

**Comment by ncb000gt** [comment]
You'd have to manage that with some other process as @DivineGod noted. You could probably just open a new connection in mongoose within your `doSomething` function as well rather than assuming the connection was closed.
