### ISSUE TITLE
I need a syntax to run a job every 4 days.

### ISSUE THREAD

**Issue by vitorbraga** [kelektiv/node-cron#262]
I'm still using: 
`new CronJob('0 */4 * *', function() `
It calls each 4 days, but it calls 60 times (one for each minute of the hour).

DO you guys can help me?
Thanks

**Comment by DivineGod** [comment]
You should read up on [crontab](http://crontab.org/) and how the pattern works. You need to specify minute, hour, day of month, month, day of week. In your case `0 0 */4 * *` would run it at midnight every 4 days. This is also documented in the README.

**Comment by slidenerd** [comment]
@DivineGod this library however takes seconds into account and therefore that documentation is pretty useless, i read that btw before making this comment 👍
