### ISSUE TITLE
Add documentation for `running` property

### ISSUE THREAD

**Issue by Moeriki** [kelektiv/node-cron#265]
There is a `running` property on jobs which is great, I need that.

But it is undocumented, would you mind a pull request adding a test and documentation on it so I can safely use it.

**Comment by sravan-s** [comment]
I kinda need that too

**Comment by ncb000gt** [comment]
Absolutely. Throw in a pull request and I'll merge it in. Thanks. :)

**Comment by sravan-s** [comment]
ahh sorry guys, I kinda misread the post. I thought @Moeriki was looking for a documentation and made this pull request. What should I do?

**Comment by ncb000gt** [comment]
Landed the pr. Thanks @sravan-s.
