### ISSUE TITLE
Change cronTime runtime

### ISSUE THREAD

**Issue by ccaiolopes** [kelektiv/node-cron#268]
I want to parameterize the time the cron will run, can I change the cronTime before running it?

And after it is already started, can I stop it and change only cronTime?

**Comment by ncb000gt** [comment]
Yes. It's semi-undocumented in that it's not in the API list but you can use `setTime()` on any job which will stop a running job (fire the callbacks as well) and then set the new `crontime`. Note that the parameter to `setTime()` needs to be a `CronTime` object.
