### ISSUE TITLE
how does cron timezone, machine timezone and node timezone affect each other ? 

### ISSUE THREAD

**Issue by daksh019** [kelektiv/node-cron#270]
I have a job scheduled to run 23:00 hours everyday in Asia/Kolkata timezone. 

Gave the timezone as : "Asia/Kolkata" and the cron pattern as : "0 0 23 * * *". 

It works fine if the server timezone is set to Asia/Kolkata but not if the server timezone is UTC. 

When the server is set according to UTC it runs at 4:30 am in the morning which is because "Asia/Kolkata" is 5:30 ahead of the UTC. 

Am i missing something ? What does timezone parameter do  and how does the system time affect it?

**Comment by aravindvaideesh** [comment]
I have the same problem ! I have the following cron pattern : '00 00 06 * * 1-5' and the timezone set to Asia/Calcutta. My server's timezone is UTC. My cron gets executed twice, once at 6 AM IST which is the expected behaviour and once at 11 30 AM IST (i.e. 6 AM GMT ).

**Comment by ncb000gt** [comment]
That obviously shouldn't happen. I'll keep this ticket open so that I can, hopefully, remember to look into it.

**Comment by DevNitish** [comment]
I also faced the same issue and solved that by **using only UTC time format in both front end back-end** (in NodeJs). For that I used a package called [MomentJs](https://momentjs.com/) in both server side and front end. For user input, I am taking time in Local Zone and converting that into UTC. And to display time I convert UTC time into local (by using MomentJs API)

**Comment by MichaelLiss** [comment]
Hi,

I am also publishing an issue.. hoping it will help get this resolved.

I am using CronGroup (which I believe is based off this)

I am running my app on Heroku... with 'standard' settings - meaning I have not changed anything to alter the most basic heroku setup to get it working

Here is my usage:

        var allJobs_debugThis = false;

        // the simple test will send simpleCounterStop messages to me
        var simpleCounter = 0;
        var simpleCounterStop = 1;
        var simplePhone = '5555555555';  // obviously NOT my phone number...

        const simpleCronGroup = new CronGroup({
            timezone: 'America/Los Angeles'
        });

        simpleSmsToMe = () =>{
            var debugThis = false || allJobs_debugThis;

            var msg = `simple test : message ${simpleCounter+1} of ${simpleCounterStop}`;
            smsImpl.send(simplePhone, keys.twillioNumber, msg)
            .then(sentTo => {

                if(debugThis){
                    console.log('sent message to ' + sentTo);
                }
            })
            .catch(err => {
                console.log(err);
            })
        }

        runSimpleTest = () => {

            var debugThis = true || allJobs_debugThis;

            var now = new Date();
            if(debugThis){
                console.log(`${now} setup simple test `);
            }

            simpleCronGroup.add({
                name: "SMS to Me",
                schedule: '0 35 19 * * *',  // set to run at 19:30 (America/Los Angeles)
                worker: () => simpleSmsToMe(),
            });

            simpleCronGroup.on('run', ({name, runnedBy}) => {
                var now = new Date();
                
                if(debugThis){
                    console.log(`${now} running ${name}`);
                }
            });
            
            simpleCronGroup.on('complete', ({name, runnedAt, completedAt}) => {
                var now = new Date();
                if(debugThis){
                    console.log(`${now} completed ` + JSON.stringify(name));
                }
                simpleCounter++;
                if(simpleCounter >= simpleCounterStop){
                    simpleCronGroup.stop();

                    if(debugThis){
                        console.log(`${now} stopping ${name}`);
                    }
                }
            });
            
            simpleCronGroup.on('error', ({name, err}) => {
                console.error(`${name} is completed with error\n${err.stack || err}`);
            });

            if(debugThis){
                console.log(`${now} starting simple cron group `);
            }
            simpleCronGroup.start();
        }

Here is the heroku log output when my job starts.  NOTE this log was collected right after 7:30 PST.

2019-03-07T03:34:34.222954+00:00 app[web.1]: Thu Mar 07 2019 03:34:34 GMT+0000 (UTC) setup simple test
2019-03-07T03:34:34.224810+00:00 app[web.1]: Thu Mar 07 2019 03:34:34 GMT+0000 (UTC) starting simple cron group

**Comment by MichaelLiss** [comment]
> That obviously shouldn't happen. I'll keep this ticket open so that I can, hopefully, remember to look into it.

I don't believe this is your problem... 
I think if the server is set to the correct time zone your code works just fine.

**Comment by MichaelLiss** [comment]
> That obviously shouldn't happen. I'll keep this ticket open so that I can, hopefully, remember to look into it.

So... Is the intent to have this component check the server time zone, make a corresponding TZ correction, if required, and fire off the event at the right time for the time zone indicated in the constructor?

**Comment by intcreator** [comment]
is this still happening? if so, would someone mind writing a test to demonstrate the behavior? one of the existing tests should be pretty close and a good starting point: https://github.com/kelektiv/node-cron/blob/master/tests/cron.test.js

**Comment by intcreator** [comment]
closing as stale
