### ISSUE TITLE
Implementing on complete : FUNCTION when checking job status !

### ISSUE THREAD

**Issue by Ralqawareet** [kelektiv/node-cron#273]
Hello , 
i've noticed that if i have a cron job scheduled which has an on complete : FUNCTION and start set t true , the on complete FUNCTION get's executed whenever i check if the job is running which doesn't make sense ! 
or this is meant to be like this ?
excuses for poor English

**Comment by ncb000gt** [comment]
I put together some code (ssh'd in, sorry about the image)
![screen shot 2017-11-21 at 10 17 44 pm](https://user-images.githubusercontent.com/62615/33108377-d0ffc9da-cf09-11e7-8fc2-f0e00a2ce18d.png)

And this is what I get.
![screen shot 2017-11-21 at 10 12 00 pm](https://user-images.githubusercontent.com/62615/33108395-e0e13172-cf09-11e7-81e4-d3d90c7343fa.png)

Let me know if this is still an issue for you. I can't seem to replicate it here. Thanks!
