### ISSUE TITLE
Multiple cpu cores coordination

### ISSUE THREAD

**Issue by manishsangwan** [kelektiv/node-cron#275]
I have two cpu cors. when i use cronjob each core works independently and tasks are duplicated. 
Is there a solution to it.
Thanx

**Comment by alecl** [comment]
Check out [this article](http://mattpker.com/2015/08/07/How-to-schedule-jobs-in-NodeJS/) on using [is-master](https://www.npmjs.com/package/is-master) with cron to coordinate this.

**Comment by manishsangwan** [comment]
thanx @alecl

**Comment by manuel-di-iorio** [comment]
Just adding my two cents to this old issue: even if you limit the execution to the master process, note that if you have more than one server (for horizontally scaling), you will still get duplicated tasks, obviously. To solve this, you will need to implement some sort of queue/lock system 👍
