### ISSUE TITLE
[Request] Fix drifting

### ISSUE THREAD

**Issue by EnricSala** [kelektiv/node-cron#279]
Nice module!

The only problem that I am having is that I need it to be a little more precise, as there is quite a bit of drifting from one execution to the next.

For example, I need to execute a function every multiple of 5 seconds during each minute (in sync with the clock, so I can't use setInterval):
```
const cron = require('cron');

const job = new cron.CronJob({
    cronTime: '*/5 * * * * *',
    onTick: () => console.log(new Date()),
    start: true,
    timeZone: 'UTC'
});
```

The output:
```
2017-03-21T19:46:10.949Z
2017-03-21T19:46:15.964Z
2017-03-21T19:46:20.969Z
2017-03-21T19:46:25.975Z
2017-03-21T19:46:30.980Z
2017-03-21T19:46:35.988Z
2017-03-21T19:46:40.994Z
2017-03-21T19:46:46.000Z
2017-03-21T19:46:51.005Z
2017-03-21T19:46:55.008Z  <-- only 4.003 seconds from previous tick!
2017-03-21T19:47:00.014Z
2017-03-21T19:47:05.020Z
```

If you take look at the milliseconds, they keep incrementing until they overflow, so the time between calls is actually:  5, 5, **4**, 5, 5.

I know that looking at the milliseconds is a bit too much, especially in the scope of cron, but for "high frequency" ticks the accumulated drift matters.

Is it fixable? Ideally I would like the function to be called at .000 or around the low milliseconds. At least they should be consistent and not drift and overflow like this.

Thanks!

EDIT: this may be related to issue #241.

**Comment by ncb000gt** [comment]
Sorry it's taken so long, but this is definitely an issue. I haven't had time to look at this and I'm not sure how much more time I'll have for it.

Hopefully I or someone in the community can get to it at some point though. =\ I'll leave this ticket open as it's definitely an issue.

**Comment by ncb000gt** [comment]
I've been running the latest @1.4.0 for a while and am not seeing any drifting with the latest code changes. I'm going to close this due to that. We can open a new ticket if this does appear to be an issue.
