### ISSUE TITLE
Cron overlap

### ISSUE THREAD

**Issue by dfloresgonz** [kelektiv/node-cron#280]
How can cron overlap be avoid? if a cron executes each 10 seconds but the onTick function takes more than that? how can that be avoid using just node-cron and not flock which I don't understand.

thanks

**Comment by ncb000gt** [comment]
You can put a variable outside of the ontick function and then check that variable to see if it's set to true, like `locked = false` and then set locked to true inside the ontick. check `locked` in the ontick and don't execute if it's still locked. :) Sorry this is so late.

**Comment by dfloresgonz** [comment]
Thanks anyways, I did something like that and using stop() function.

**Comment by nemanjapetrovic** [comment]
@dfloresgonz   can you provide us with a code example how you solve this issue? Tnx.

@ncb000gt Also, this should be added in readme.md as documentation notice about the problem that may occur and how to solve it.

**Comment by ncb000gt** [comment]
@nemanjapetrovic this isn't a problem with the module. it is something you'd have to handle in any case where you may have the same function called, but the execution time permits overlap. for instance, if you had an api call that was able to trigger a database update or full table scan or something similar and it was still operating when another call came in to do the exact same thing, you'd have to deal with that in your own code.

if this comes up more then i'll add it to the readme.

**Comment by dfloresgonz** [comment]
@ncb000gt I think what @nemanjapetrovic  meant was to have a built-in option where you can configure if you don't want crons to overlap or something similar.

I'll explain my case:
I had a cron which ran each 5 seconds, this would check for a DB table to see if there were any pending emails to be sent. If there were pending emails, these would be send, obviously this operations would take more than 5 seconds (actually unknown duration) so the next cron would execute.

How I solved it.

- When my cron triggered I stopped it using myCron.stop();
- Then I invoke my other functions (sending emails) sendEmails();
- As soon as all emails were sent I'd start again the cron using myCron.start();

Now I use AWS Rules for my crons but that's another story.

I hope I helped in something.

**Comment by ncb000gt** [comment]
@dfloresgonz @nemanjapetrovic Yea. I hear you. I've pushed back for quite a long time against the added complexity of managing cron states for people due to the fact that I'm pretty much the only person working on the code and there are already a bunch of complex issues that exist in the code. But, someone else has offered to work on something similar to what is being discussed here so the module may gain some new functionality in the somewhat near future.

**Comment by dfloresgonz** [comment]
Thanks @ncb000gt but in my case It was really easy to avoid this issue. you just need to create a good algorithm, perhaps have a section of patterns on how to solve some issues, one of them is cron overlap and detail how you can use stop() and start() to avoid such issue. Not just changing your code which would take time.

**Comment by ncb000gt** [comment]
That's a good idea. Something like a larger set of examples or recipes or something like that could be useful.

**Comment by nemanjapetrovic** [comment]
@dfloresgonz  Thanks for the example. 

@ncb000gt  Yes, a set of examples will be a great thing and very useful.

**Comment by ncb000gt** [comment]
@nemanjapetrovic sorry about the miscommunication. i do agree that kind of thing could be helpful and would be a better idea than the current list of examples in the readme.

**Comment by ncb000gt** [comment]
I added some examples in this commit: 6056681. Does this do what you were asking for or do you think I missed one?

**Comment by nemanjapetrovic** [comment]
@ncb000gt Thank you, this commit will help a lot especially: *is_job_running.js*

**Comment by ncb000gt** [comment]
Cool. Glad to hear it.
