### ISSUE TITLE
Generators support

### ISSUE THREAD

**Issue by Ezechiele** [kelektiv/node-cron#289]
Does "node-cron" supports generators? Because i'm not able to have it work, as example

> var CronJob = require('cron').CronJob;
> new CronJob('* * * * * *', function*() {
>     const r = yield mongoose.model.find({somedata}).exec()
>     console.log(r)
> }, null, true);

won't work.
Am i missing something or generators are not supported yet?

**Comment by klaveren** [comment]
Why you instantiate a NEW CronJob? 
Try without a new... CronJob is not a new constructor.

CronJob('* * * * * ', function() {
const r = yield mongoose.model.find({somedata}).exec()
console.log(r)
}, null, true)

if you needed a catch the process id, maybe stop, restart you can use a variable like this:

var myTask = CronJob('* * * * * ', function() {
const r = yield mongoose.model.find({somedata}).exec()
console.log(r)
}, null, true)

myTask.destroy()
myTask.restart() See the documentation for understand better.

**Comment by Ezechiele** [comment]
I instantiate a new CronJob because the documentation say so, if for examplethe following code
`var CronJob = require('cron').CronJob;
CronJob('* * * * * *', function() {
        console.log("Hello")
    }, function () {
        /* This function is executed when the job stops */
    },
    true, /* Start the job right now */
    null /* Time zone of this job. */
);`
result in **TypeError: self.start is not a function**

And, in addition to that, your example can't work because the function is defined as _function()_ and not as _function*****()_ so the **yield** is not recognized, am I missing something?

**Comment by klaveren** [comment]
Forgive me I got confused with another lib.
I'll delete the answer because it's wrong.
https://www.npmjs.com/package/node-cron

**Comment by yanickrochon** [comment]
First of all, do not use generators anymore. If you must run your job asynchronously, run it inside a `Promise`, in order to support `async`/`await` syntax. But, no, this module does not support asynchronous jobs.

**Comment by brandonros** [comment]
What if the onTick function passed a "onFinish" callback?

**Comment by Ezechiele** [comment]
As @yanickrochon said don't use generators and use promises instead, the following will work:

```
var CronJob = require('cron').CronJob;
var job = new CronJob({
	cronTime: '* * * * *',
	onTick: function() {
    	        const r = await mongoose.model.find({somedata}).exec()
		console.log(r)
	}
});
```

**Comment by brandonros** [comment]
You pasted a bad example. You need to make the onTick callback an async
function, or you'll get a syntax error. :)

**Comment by yanickrochon** [comment]
Out of curiosity, how was this resolved?

**Comment by brandonros** [comment]
```
var CronJob = require('cron').CronJob;
var job = new CronJob({
	cronTime: '* * * * *',
	onTick: async function() {
    	        const r = await mongoose.model.find({somedata}).exec()
		console.log(r)
	}
});
```

**Comment by Ezechiele** [comment]
@brandonros Thank you for pointing that out, I'm actually using the code without the onTick callback being an async function and it works, do you know what could be the issue?

**Comment by astateful** [comment]
Not sure why this thread was closed...in my (limited) understanding, the fireOnTick method in line 442 of cron.js does not wait (either through await or promise.all, etc.) for the callbacks to be completed. So although Ezechiele's onTick function is declared as 'async', it will still work but basically not have the desired outcome (i.e. that all work will be executed before the fireOnTick method returns).

I think in order to make this library async/promise friendly, child-process would need to be replaced with async-child-process (so that 'spawned child process' can be 'awaited' on) and then the interface would need to be adapted slightly to be promise-based one.
