### ISSUE TITLE
Disappointed by API :)

### ISSUE THREAD

**Issue by ORESoftware** [kelektiv/node-cron#290]
We have:

```js
let {CronJob} = require('cron');
let job = new CronJob(function(a,b,c){

});

```
Looks like a is a function, but I don't see an explanation of what that function would be, a callback? Why would it be a callback?

Furthermore, why isn't `a`,`b`, or `c` not the timestamp of that particular job? It would be nice to know the time that generated the job, right?

**Comment by ncb000gt** [comment]
Are you sure you have the right module?

Take a look at the API in the README.
