### ISSUE TITLE
Firing at weird intervals?

### ISSUE THREAD

**Issue by matthieunelmes** [kelektiv/node-cron#291]
`var textJob = new cronJob('0 08 * * *', function () {
    doSomething();
}, null, true);`

Fires at 9am and 9:22pm...

I'm guessing 9am is due to daylight savings, but I cannot explain the 9:22pm??

Also I've tried with '00 08 * * *'

**Comment by amit27592** [comment]
Are you running this on a personal computer or a server? For me this problem arose when I was running node-cron on my personal computer & it went to sleep in between invocations. (Which messed up the setTimeout alarm).

If yours is the same case, then you can try setting TIMEOUT_MAX value in timers.js to 60000, which should ensure proper firing as it will check every minute whether to fire the alarm.

**Comment by matthieunelmes** [comment]
Interestingly, it's running as an app on Google cloud, so perhaps because it's running on shared architecture the app get's put to sleep??

**Comment by amit27592** [comment]
Yeah that could be it as Google would freeze your function if it doesn't execute any code for a sustained period of time. And as it's a per minute billing system, reducing TIMEOUT_MAX to a minute will not work for you either as I'm assuming it would count as a sustained use and your pricing would be extremely high.

**Comment by matthieunelmes** [comment]
Perhaps time to spin up the Raspberry Pi as a node.js server to test

**Comment by amit27592** [comment]
You could try using the Cron service that Google App Engine provides (https://cloud.google.com/solutions/reliable-task-scheduling-compute-engine) to trigger your app periodically.

**Comment by ncb000gt** [comment]
That's definitely weird. Given the age of the ticket and the fact that I don't see this when I run the module I'm going to close it, but if it's still an issue then we can revisit this.
