### ISSUE TITLE
Problem while deploying to Google App Engine

### ISSUE THREAD

**Issue by sushant23** [kelektiv/node-cron#294]
I am having a problem while deploying my **sails js** app with this library to Google App Engine. I am getting following error 

> error: Error: The hook `sockets` is taking too long to load.
> Make sure it is triggering its `initialize()` callback, or else set `sails.config.sockets._hookTimeout to a higher value (currently 20000)
>     at Timeout.tooLong [as _onTimeout] (/app/node_modules/sails/lib/app/private/loadHooks.js:85:21)
>     at ontimeout (timers.js:488:11)
>     at tryOnTimeout (timers.js:323:5)
>     at Timer.listOnTimeout (timers.js:283:5)

**Comment by ncb000gt** [comment]
I don't see where this is related to the cron module. Can you share some other code or are might you be looking at the wrong module?

**Comment by ncb000gt** [comment]
Closing due to age. We can create a new ticket if this is still an issue.
