### ISSUE TITLE
Error: Unknown alias: und

### ISSUE THREAD

**Issue by JulienDaoust** [kelektiv/node-cron#296]
Hi, 

My partner and I are developing an app with NodeJS. He use Linux MINT and I use MACOSX and the code works on his machine and not mine. We are not sure if we actually need to change some code because it's working on his machine. 

![capture d ecran 2017-07-07 a 17 25 59](https://user-images.githubusercontent.com/16724059/27977591-61c7bcf8-6339-11e7-9fe6-5f253f6126e3.png)

**Comment by RohitBht** [comment]
How did u resolve this error later?
Is it got something to do with cron version?

**Comment by fabioespinosa** [comment]
Same issue here, it seems 'und' is added to the aliases defined here https://github.com/kelektiv/node-cron/blob/ea19efb16ded0887cb2a8c5d52f83666d8484468/lib/cron.js#L64

**Comment by javascriptlove** [comment]
I've actually had this error but the alias was `mai`. Happened when I set the timezone to Europe/Warsaw (`mai` means month May in Polish).

```
node --version
v8.9.0
npm --version
5.5.1
```

Happens only in the built docker container based on ubuntu:16.04

**Comment by dennisgcoleman** [comment]
I just started getting this error as well. My local development environment is running MacOS and it's fine. Our staging environment is running Debian Gnu Linux 8 Jesse. Node 8.9.1. Npm 5.5.1 and cron 1.4.0. We are also using Docker Node Image https://github.com/nodejs/docker-node.

**Comment by javascriptlove** [comment]
@ncb000gt the question is, why does it even need the localized versions of aliases to run? I thought setting timezone to "Europe/Warsaw" will only affect the clocks / offset / DST or whatever else, but now it just spits the error. Moreover, the cron time is set as `0 0 3 1-31 1-12 2,6`, so there's no need in aliases. Does it sound logical?

**Comment by ncb000gt** [comment]
@javascriptlove there is no need for aliases in the example you posted, and when i use it locally, it's fine. I don't get an exception. But, if I use `mai` in the expression it will.
`0 0 mai 1-31 1-12 2,6` vs `0 0 may 1-31 1-12 2,6`, the first doesn't work and throws an exception whereas the second does work because the alias is specified. hope that helps clear it up.

@dennisgcoleman can you share the cron expression you're using? Also, can you update to the latest cron, 1.5.0, please? Thanks!

**Comment by jgomes94** [comment]
I Had "Monday" for week day and it was giving me this error, changed to "Mon" and it worked.

**Comment by DanielIchida** [comment]
Unknown alias: und

      65 |   addCronJob(name: string) {
      66 |     const time = `${process.env.SECONDS} ${process.env.MINUTES} ${process.env.HOURS} * * 2-5`;
    > 67 |     const job = new CronJob(time,
         |                 ^
      68 |       async () => {
      69 |         this.service = null;
      70 |         this.logger.log(

      at ../node_modules/cron/lib/cron.js:413:11
          at String.replace (<anonymous>)
      at CronTime._parse (../node_modules/cron/lib/cron.js:406:29)
      at new CronTime (../node_modules/cron/lib/cron.js:46:9)
      at new CronJob (../node_modules/cron/lib/cron.js:527:19)
      at Service.addCronJob (application/use_case/app.service.ts:67:17)
      at new Service (application/use_case/app.service.ts:25:10)
      at TestingInjector.instantiateClass (../node_modules/@nestjs/core/injector/injector.js:301:19)
      at callback (../node_modules/@nestjs/core/injector/injector.js:48:41)
      at TestingInjector.resolveConstructorParams (../node_modules/@nestjs/core/injector/injector.js:124:24)

**Comment by taneron** [comment]
I had the same error message.

`und` here stands for `undefined` and this is probably due to dynamic cron definitions. 
It happened to me that a cronjob variable was undefined at startup. 

`@Cron(`*/${INTERVALL} * * * *`)`
which I simply resolved with adding a fallback value
`@Cron(`*/${INTERVALL || 5} * * * *`)`

**Comment by SaM-0777** [comment]
This is an un expected behavior. It can happen if you are using delay and repeat object together, As it is not a best practice
Please use only delay or repeat.
