### ISSUE TITLE
how to run one cron job on every 2 hours?

### ISSUE THREAD

**Issue by jaisonka91** [kelektiv/node-cron#297]
How to run one cron job on every 2 hours.

**Comment by baileyherbert** [comment]
The format is `ss mm hh dd ww` where:

- `ss` = seconds
- `mm` = minutes
- `hh` = hour
- `dd` = day
- `ww` = weekday

So a cron schedule of `0 0 */2 * *` will run once every 2 hours (when at 0 minutes and 0 seconds).

**Comment by josinaldobarbosa** [comment]
`0 0 0 */1 * *` Does it run every day at midnight?
