### ISSUE TITLE
how to run everyday midnight?

### ISSUE THREAD

**Issue by josinaldobarbosa** [kelektiv/node-cron#302]

**Comment by baileyherbert** [comment]
Come on, man. You need to start looking things up!! It will save you so much time.

http://lmgtfy.com/?q=run+a+cron+job+at+midnight

**Very first result:**
"How to write a cron that will run a script every day at midnight?"
https://stackoverflow.com/questions/3984134/how-to-write-a-cron-that-will-run-a-script-every-day-at-midnight

**And the answer on that page says...**
`00 00 * * *`

**BUT WAIT!**
This `node-cron` package also has seconds, whereas normal crons only go down to minutes. So you must add another 0 before everything else:

`0 0 0 * * *`

The cron pattern for `node-cron` is `[seconds] [minutes] [hours] [day_number] [months] [day_of_week]`. Remember that `*` means _each_, `*/x` means _every x_, and any number _n_ means the _nth_.

Thus, `0 0 0 * * *` will run at midnight, once per day.

**Comment by josinaldobarbosa** [comment]
Excuse my English is very bad, I had to be sure that this lib would work, thank you anyway.
