### ISSUE TITLE
steps interval problem

### ISSUE THREAD

**Issue by andreash92** [kelektiv/node-cron#303]
hello, 
I set up a cronjob to run every 45 minutes. The pattern i use is this:  
``` 
job = new CronJob('0 */45 * * * *', ... )
```
My problem is that the job runs every hour and every 45th minute of every hour like this: 
```
[Sat Aug 26 2017 15:45:00 GMT+0300 (EEST)] INFO cronjob
[Sat Aug 26 2017 16:00:00 GMT+0300 (EEST)] INFO cronjob 
```

What i want is to run **every 45 only**,  and **not** every hour! i.e. i want 15:45, 16:30, 17:15 and so on..

How to do that? Am i doing something wrong or is it a bug?

Thanks

**Comment by dwjft** [comment]
Getting the same issue with `* */15 * * * *`.

**Comment by ncb000gt** [comment]
@andreash92 this is behaving as expected. when you specify the repetition with `0 */45 * * * *`, it should always run at 0 and then every 45th second. Just to verify I tried this out locally in some testing and verified that it does that, it's basically the same as using `0 0,45 * * * *`. I'm not entirely sure why this is the case, but that's the way that most of the cron tools I've looked at work.

@dwjft running with `* */15 * * * *` != `0 */15 * * * *`. If you want to run every 15th minute then use the latter. If you want to run every second after every 15th minute then use the first.
