### ISSUE TITLE
CronJob executing several times

### ISSUE THREAD

**Issue by renilbabu03** [kelektiv/node-cron#305]
I am using cron job to run a task at night only one time but the cron is running multiple times due to which my code gets executed several time. How can I stop this.

`var Job = new CronJob({

    cronTime: '* * 01 * * *', //Execute at 1 am every day

    onTick  : function() {

        co(function*() {

            yield insertToDatabase(); //this is the function that does insert operation

        }).catch(ex => {

            console.log('error')

        });

    },
    start   : false,

    timeZone: 'Asia/Kolkata'

});`

I have placed the job.start() in the index.js file. Can you please help me figure out what I am doing wrong!

**Comment by doowb** [comment]
This pattern `'* * 01 * * *'` is saying "at every second from 01:00:00 to 01:59:59 every day".

I think you just need to use `'00'` in place of the minute and second fields: '00 00 01 * * *'.

**Comment by renilbabu03** [comment]
I have done Job.stop() which fixed the issue but the job only runs when the server is restarted and it never runs again

**Comment by diptenagile** [comment]
I also had the same problem and i notice that server is run on cluster mode.
so need to put cronjob in 
```
if(cluster.isMaster){
   // cronjob
}
```

**Comment by ncb000gt** [comment]
@renilbabu03 were you able to work out the issues you were having?

**Comment by ncb000gt** [comment]
Closing due to age. We can create a new ticket if this is still an issue.
