### ISSUE TITLE
ontick never execute if utcOffset set to zero

### ISSUE THREAD

**Issue by aerchen** [kelektiv/node-cron#309]
here is my code 
```
let job = new cron.CronJob({
     cronTime: '*/2 * 6 * * *',
     onTick: tick,
     runOnInit: true,
     start: true,
     utcOffset: 0,
 })  

 function tick() {
     console.log('job', new Date(), this)
 } 
```

**Comment by aerchen** [comment]
now utc is 06:30:38, then I set  cronTime to '* * 6 * * *', set utcOffset to  0. I think onTick function will execute every second, but onTick function  never execute

**Comment by ncb000gt** [comment]
I added a test case for this, that seems to pass as expected. Is there something else happening that this doesn't seem to cover?

		it('should run a job using cron syntax with number format utcOffset that is 0', function () {
			var clock = sinon.useFakeTimers();
			var c = 0;

			var moment = require("moment-timezone");

			// Current time
			var t = moment();

			var job = new cron.CronJob('* * * * * *', function(){
				c++;
			}, null, true, null, null, null, 0);

			clock.tick(999);
			expect(c).to.eql(0);

			clock.tick(1);
			clock.restore();
			job.stop();
			expect(c).to.eql(1);
		});

Let me know, thanks!
