### ISSUE TITLE
Problem when creating a new CronJob with a defined day of month

### ISSUE THREAD

**Issue by softrucktech** [kelektiv/node-cron#310]
I'm having some trouble to create a new CronJob for a specific day of month: the `new CronJob` function does not return when I define a cron that will be triggered only in the next month (although it works fine for the same month). 

The following code snippet, for example, never prints *'After new CronJob'* (considering today as October 2). However, if I change the day of month to **3** then `new CronJob` returns.

```javascript
const CronJob  = require('cron').CronJob;

console.log('Before new CronJob');

new CronJob('0 30 12 2 * *', function() {
  console.log('Triggered!');
}, null, true, 'America/Sao_Paulo');

console.log('After new CronJob');
```

Am I missing something or `new CronJob` was indeed supposed to return? I'm using Node.js v6.9.4 and cron v1.3.0.

**Comment by stnever** [comment]
I'm having a similar issue, with `new CronJob` not returning, and I *think* it might be related to timezone/daylight-saving-time shenanigans.

I can see that you are in `America/Sao_Paulo` timezone, just as I am. Notice that in 2017 Brasilian Daylight Saving Time starts on October 15.

**Comment by ncb000gt** [comment]
DST has been an ongoing issue in this project and I haven't had enough time to properly solve the issue. For now, just try to avoid it if possible. Maybe I or someone will have time to fix it properly.
