### ISSUE TITLE
How do I view the existing node-cron job?

### ISSUE THREAD

**Issue by onebook0505** [kelektiv/node-cron#311]
How do I view the existing node-cron job? ( Find and delete cron job )

**Comment by onebook0505** [comment]
Now my server has two cpu, which leads to the recurrence of cron job, how can i remove the wrong cron job?

**Comment by onebook0505** [comment]
Has been resolved, please close the issue

**Comment by leizard** [comment]
HEY @onebook0505 , how do you resolve this ?

**Comment by topwood** [comment]
@onebook0505 +1

**Comment by yanickrochon** [comment]
As far as I can see, the app is responsible to preserve a cache of all defined jobs, and you can see if a job is pending/running with `job.running`.
