### ISSUE TITLE
How schedulate function  15 Nomber 2017 at 18:36

### ISSUE THREAD

**Issue by francedema** [kelektiv/node-cron#316]
I need to schedulate  a function in   15 Nomber 2017 at 18:36  (one time), without repeating itself over time. This is the code:

```
var task = cron.schedule('0  36 18 15 11 *', function() {
			console.log("hello");
		}, false);

		task.start();
```

This code doesn't work for all date that I have tried, so I think that I'm wronging date. Anyone can help me?

**Comment by ncb000gt** [comment]
While it's after the 15th, if you want to do this in the future, you can supply a date or moment object as the first parameter.
