### ISSUE TITLE
NPM Docs seem out of date

### ISSUE THREAD

**Issue by AriLFrankel** [kelektiv/node-cron#317]
I'm seeing a lot of inconsistency between the examples provided on the NPM page and the Github readme

Thanks!

**Comment by ncb000gt** [comment]
Yea, sorry. I haven't had much time to be a good maintainer the past year or more...I'm trying to work on it and keep up. I'll try to attend to the docs in the near future. Keeping open so that my "nag" script reminds me. ;D

**Comment by ncb000gt** [comment]
I know this is _long_ overdue, but I pushed a new version and released some updated examples and docs. Sorry about the delay.
