### ISSUE TITLE
Readme: error in the "For good measure" example - param start

### ISSUE THREAD

**Issue by vince137** [kelektiv/node-cron#318]
Hello,

The param "start" is not working on my environment to launch the cron instantly. However, the param "runOnInit" is working properly. 

You should update the doc.

**Comment by ncb000gt** [comment]
`start` actually starts the cronjob. If you don't set it the job will not actually run meaning that the onTick wont actually trigger on its schedule. `start` does not actually fire the onTick. The docs explicitly call this out:
```This does not immediately fire your onTick function, it just gives you more control over the behavior of your jobs.```

Similarly the `runOnInit` does fire your onTick as soon as it can and the docs call that out.

I realize I'm just getting to this so you may not have an issue anymore, but were you looking for something more than this in the docs?

Let me know, thanks.
