### ISSUE TITLE
Timezone doesn't seem to be working

### ISSUE THREAD

**Issue by carasel** [kelektiv/node-cron#320]
I am using the following code to call my function.    

                new CronJob("0 0 14 * * *", () => {
                    ...
                }, true, "America/New_York")

It is running at 14:00 UTC (on a machine in the UK), but shouldn't it be running at 19:00 UTC?

**Comment by ncb000gt** [comment]
You didn't add the `onComplete` function. You can skip that if you use the object style for init.
