### ISSUE TITLE
Wrong Sunday/Saturday

### ISSUE THREAD

**Issue by Hedinhiervard** [kelektiv/node-cron#322]
I create job like this: 

`cron.CronJob('0 20 23 * * 7', cb, null, true, 'Asia/Novosibirsk');`

I expect it to run each Sunday on 23:30, however, it actually runs each SATURDAY on 23:20.
I suspect the week starts on Sunday never mind the timezone (hence, I need to put it like `'0 20 23 * * 1'`? In this case, the docs are obviously wrong:

```
var job = new CronJob({
  cronTime: '00 30 11 * * 1-5',
  onTick: function() {
    /*
     * Runs every weekday (Monday through Friday)
     * at 11:30:00 AM. It does not run on Saturday
     * or Sunday.
     */
  },
  start: false,
  timeZone: 'America/Los_Angeles'
});
```

**Comment by ncb000gt** [comment]
![screen shot 2017-12-04 at 11 24 43 am](https://user-images.githubusercontent.com/62615/33563375-c3802242-d8e5-11e7-88a7-9f159d8b3c7c.png)

I can put in a note though to be more explicit (ea19efb16ded0887cb2a8c5d52f83666d8484468).

**Comment by Hedinhiervard** [comment]
So, is the Sunday 6 or 7?
7 is Saturday in my timezone and I consider it a bug. Can you reopen please?

**Comment by ncb000gt** [comment]
Sunday should be 0 (I updated the README, linked to above).

Saturday is 6, but the way that it parses, it set's anything above that to the "max". It should probably warn that you've specified a value over the max though.

**Comment by analytik** [comment]
Sunday is the 7th day for 6.7 billion people on Earth. Why on Earth would you not support this?
