### ISSUE TITLE
How to run cron on multiple servers?

### ISSUE THREAD

**Issue by mrded** [kelektiv/node-cron#323]
Hello,

I'm running multiple servers at the time. If I create a cron job - it will run on all servers.

How to make it run only on one of servers?

Thank you.

**Comment by paulogdm** [comment]
Hello mrded, if you want a cron job to work like a singleton, you need to do a "lock system" yourself, like creating a file somewhere and checking if it exists (like package managers on linux distros) or a variable in a database.

**Comment by mrded** [comment]
Good idea, I was also thinking to set a database lock. The first server who managed to set a lock - runs a cron. 

Thank you for your advice.
