### ISSUE TITLE
CronJob doesn't stop

### ISSUE THREAD

**Issue by MattNot** [kelektiv/node-cron#325]
Hi i'm trying to stop a cronJob but it doesn't stop, here's the code:
`crono[m]=new Cron('00 * * * * *',()=>{
                  if(json[m].time['hour']==0 && json[m].time['minute']<=10)
                                  console.log("foo");
                  if(json[m].time['hour']==0 && json[m].time['minute']==0) 
               {
                      console.log("time is up")
                      crono[m]=null;
                      }
						json[m].time['minute']--;
					},null,true)`
Already tried with crono[m].stop, this.stop, this=null. Nothing happens, how can i do this?

**Comment by ncb000gt** [comment]
You nee to call stop. `crono[m].stop()` or `this.stop()`. Take a look at the tests for an example of how this works there.
