### ISSUE TITLE
Run Task after every Four Hours pass.

### ISSUE THREAD

**Issue by AbdulRehmanDevStudio** [kelektiv/node-cron#326]
I want to run cronJob after every 4 four hrs end in 24hr.

**Comment by faladinojames** [comment]
Use this
`var CronJob = require('cron').CronJob;
var job = new CronJob('00 00 4 * * *', function() {
  
  }
);`

**Comment by AbdulRehmanDevStudio** [comment]
thanks @faladinojames .... it gives error on this i try this. I found solution for this. e.g 
new cronJob('00 */4 ***', function() {})
