### ISSUE TITLE
running cron every 90 seconds / 90 minutes

### ISSUE THREAD

**Issue by Selectful** [kelektiv/node-cron#327]
is there a way to run a cron for these specific intervals or would i need more than 1 cron job? 
  and if I do need multiple crons do i need to do two cronjobs separately or can I do it in one job with two cronTimes?

**Comment by sirius1024** [comment]
In my mind you need more than 1 cron jobs and have to create multiple cron expressions to 2 cronjobs.

**Comment by ncb000gt** [comment]
Jobs don't currently support two different crontimes. I believe you'll need two jobs.
