### ISSUE TITLE
Cron running very random days

### ISSUE THREAD

**Issue by esthersong** [kelektiv/node-cron#332]
00 30 00 * * *

My cron runs very randomly. I want it to run everyday at 12:30am UTC which happens at the correct time; however, the days are off. It ran 1/26, 2/11, 2/15, 2/18, 2/20.

**Comment by ncb000gt** [comment]
This seemed strange to me so I created a test to see but it appears to be working as expected in the tests. Are you still seeing this issue? I pushed the test changes to 2163d1e5ebce2a102e340169045b90a2d9acc215 and d2e0ab2a33f2be86610277ed072b6aa6a10669e5. Can you share a larger code snippet if you're still seeing this?
