### ISSUE TITLE
Cron quits immediately with dates

### ISSUE THREAD

**Issue by Reid-Luna** [kelektiv/node-cron#341]
When i use a date with cron, it stops immediately and never executes.
`let date = new Date('2018-5-23T16:56:00');
let dateJob = new cron(date, ()=>{
	console.log('sending message');
	text('7192311746', 'hello');
}, ()=>{
	console.log('job stopped');
}, true, null);`

**Comment by rjoydip** [comment]
@Reid-Luna You code is executing perfectly. You are setting the value which one-time executable.

**Comment by ncb000gt** [comment]
@Reid-Luna are you seeing any text in the log?

There are tests to ensure that dates operate as expected, execute once that is so I'd definitely be surprised if it's not doing that at all. @rjoydip is right that it should execute at most once with what you're using. If you want it to repeat then you'll need to use cron style syntax.
