### ISSUE TITLE
Can i change the crontab pattern for a running job?

### ISSUE THREAD

**Issue by 3epnm** [kelektiv/node-cron#342]
I wonder if there is a way to change the pattern for a running job.

**Comment by akaisuicchi** [comment]
I had the same issue once.
What you can do is: 
- Initialize a variable with the desirable pattern and create your cronjob with that
- In `onTick` do your logic and change that variable, then immediately call `this.stop()`
- In `onComplete` start your job again. `this.start()`

**Comment by ncb000gt** [comment]
You can call `job.setTime()` but it needs to be a `CronTime` object. That would stop the job and change the syntax/time of the job. You'll need to restart it manually.
