### ISSUE TITLE
Wait for job finished to execute the next one

### ISSUE THREAD

**Issue by qeude** [kelektiv/node-cron#347]
Hi !
I'm actually using cron jobs to get some data from a server to another. During the first job I'm retrieving the whole db if there is nothing in my new one, and i would like to execute this cronjob every minutes AND when i am sure that the previous one is ended. Is there a way for this kind of thing ?
Thanks

**Comment by acanimal** [comment]
I'm in a similar situation and use a semaphore variable.
Supposing the real job is done by `runYourTaks` function I create a job like this:

```
  const job = new CronJob({
    cronTime,
    onTick: async () => {
      if (job.taskRunning) {
        return
      }

      job.taskRunning = true
      try {
        await runYourTaks()
      } catch (err) {
        // Handle error
      }
      job.taskRunning = false
    },
    start: true,
    timeZone: 'UTC'
  })
```

Although the onTick is run multiple time you avoid overlapping your tasks.

**Comment by ncb000gt** [comment]
You may want to setup a queue of sorts. Run the jobs, have your first push data into a queue for processing, the second checks the queue for new items and processes them as they come in. You could also have a check to see when the first job actually finishes as well and then just kill the process when completed if you don't want this task to just sit around forever.

Does that help?

**Comment by ncb000gt** [comment]
I put up a directory with some examples into the project. One of the examples included shows how I would tackle this task. Hope it helps and thanks @acanimal for your earlier help!

**Comment by medjamiaanes** [comment]
This is working fine for me 
`const job = cron.schedule('*/10 * * * * *', async function(){
  job.stop();
  filter = 'PENDING', slidingTime = 60
  await heatmap_settings.findOne().select('options filterType').then(setting => {
    filter = setting.filterType
    slidingTime = setting.options.slidingTime
  }).catch(err => console.log(err))
  await getHeatmapRules()
  job.start();
}, {
  scheduled: true
})`

**Comment by shailendra-k1245** [comment]
Thanks ncb000gt , I'm using an array to push data every time cron is triggered and I'm checking whether previous cron process should be killed before starting a new one . 👍 
Actually in my case I want to terminate old cron process whenever a new job comes

let taskArr = [ ]
let task

if (taskArr.length > 0) {
        task.stop()
    }
    
    task = cron.schedule("* * * * * *",()=>{
    })
    
    taskArr.push(task)

**Comment by didenkuswendi** [comment]
> Thanks @ncb000gt , your solution worked for me 👍 I'm using an array to push data every time cron is triggered and I'm checking whether previous cron process should be killed before starting a new one . Actually in my case I want to terminate old cron process whenever a new job comes
> 
> ```
> let taskArr = [ ]
> let task
> 
> if (taskArr.length > 0) {
>         task.stop()
>     }
>     
>     task = cron.schedule("* * * * * *",()=>{
>     })
>     
> taskArr.push(task)
> ```

berjalan seperti pesona.
thanks

**Comment by AregGhazaryan** [comment]
all of this is such a huge poopoo ways to manage this, cant we just have a simple flag set on the cron object itself?

**Comment by sheerlox** [comment]
Hi @AregGhazaryan, thank you for your inspirational and constructive comment.

There is a feature request (which is referenced right above your comment) here:
- https://github.com/kelektiv/node-cron/issues/556
