### ISSUE TITLE
CRON task logged once but ran twice

### ISSUE THREAD

**Issue by Roger13** [kelektiv/node-cron#349]
I have a task that is set to run at midnight on the 5th and 15th days of the month, which generates a report and post it to slack. 

Interesting enough, looking at the service log, the task ran smoothly and only once, but looking at the slack output and the saved report at the db, it actually ran twice with very little time difference.

Is there any chance that when redeploying the service the previous cron wasn't removed and triggered a zombie process? 

Thank you kindly

**Comment by ncb000gt** [comment]
It seems plausible that multiple deployments could leave a handful of processes hanging around. You'll want to make sure you clean up processes when you're deploying new code.

You could likely check the processes in your system to see if there are mutiple node processes running (assuming node here ;D).
