### ISSUE TITLE
Usage without `new`?

### ISSUE THREAD

**Issue by christianbundy** [kelektiv/node-cron#352]
Hello!

I'm working to conform to https://eslint.org/docs/rules/no-new, but I don't see an easy way to use this package without using `new` for side-effects. Is there a way to do this?

Thanks!

**Comment by christianbundy** [comment]
# Problem Solved!

## Before

```js
var CronJob = require('cron').CronJob;
new CronJob('* * * * * *', function() {
  console.log('You will see this message every second');
}, null, true, 'America/Los_Angeles');
```

## After

```js
var cron = require('cron');
cron.job('* * * * * *', function() {
  console.log('You will see this message every second');
}, null, true, 'America/Los_Angeles');
```

**Comment by ncb000gt** [comment]
To be fair, `.job` just wraps `new CronJob()`. But I may be making some changes to the module in the next few months that would include a pretty large rewrite and likely breaking changes, but would support what the link talks about. :)
