### ISSUE TITLE
how can I set cron jobs for date range and every 190 minutes ?

### ISSUE THREAD

**Issue by xhkocatepe** [kelektiv/node-cron#353]
I want to run a job every 190 minutes and only  between 06:15 - 22:15.

How can I do with cron expression :/

**Comment by ncb000gt** [comment]
Well, right now the minutes are hard specified to less than 60, and the hours need to be integers between 0 and 23.

So you could do something like `0 6-22 * * * *` but that doesn't get you exactly what you want. You want something to run every 1h50m between those hour sets. So, you could do something like `0 6-22/2 * * * *`.

I have a test here that I've added which confirms it working:

	it('should run every 2 hours between hours', function() {
		var c = 0;
		var d = new Date('12/31/2014');
		d.setSeconds(0);
		d.setMinutes(0);
		d.setHours(0);
		var clock = sinon.useFakeTimers(d.getTime());

		var job = new cron.CronJob({
			cronTime: '0 2-6/2 * * * *',
			onTick: function() {
				c++;
			},
			start: true
		});

		clock.tick(2 * 60 * 1000);
		expect(c).to.eql(1);
		clock.tick(2 * 60 * 1000);
		expect(c).to.eql(2);
		clock.tick(2 * 60 * 1000);
		expect(c).to.eql(3);
		clock.tick(2 * 60 * 1000);

		clock.restore();
		job.stop();
		expect(c).to.eql(3);
	});

Let me know if this helps?
