### ISSUE TITLE
Execute cron job at a specific date, or nearest friday if the specified date happens to be on the weekend.

### ISSUE THREAD

**Issue by MaximilianLloyd** [kelektiv/node-cron#361]
Hi. I want to send invoices for my service using node-cron. Specified in the agreement me and my business partner have written we send it on the 10th of every month, or friday if the 10th is on the weekend. I am not sure how i can implement this in a good way using node-cron. Any help would be greatly appreciated.

**Comment by ncb000gt** [comment]
I would probably do this task this way:

Have a job that fires every Friday at 9am (`* 0 9 * * 5`) that checks to see if the current date is the 10th or within 2 days of it (to account for the weekend) that fires off invoices.

Does that help?
