### ISSUE TITLE
onTick is being executed every second 

### ISSUE THREAD

**Issue by leonardoampuero** [kelektiv/node-cron#362]
I just started testing it and for some reason the basic example does not work.
After 2 minutes I see the line being logged every second.

`let job = new CronJob("* */2 * * * *", function() {
  console.log("You will see this message every second");
});
job.start();`

**Comment by ncb000gt** [comment]
If you want it to print every two minutes then you need to use `0 */2 * * * *` otherwise what you're seeing will happen where the onTick will fire every second of the second minute.

Hope that helps!
