### ISSUE TITLE
How to stop specific job in running server?

### ISSUE THREAD

**Issue by canyoudev** [kelektiv/node-cron#363]
Hi there. Trying to figure out how to stop certain cron job.

I have an Express server, I store jobs in Mongo. On server start up (and after the job creation) I start the job. 

```js
function startUpJobs () {
  Job.find({}).then(jobs => {
    jobs.forEach(job => {
      const cronJob = new CronJob(`*/${job.timeout} * * * * *`, function() {
        console.log(job.name)
      })
      cronJob.start()
    })
  })
}
```
But how can I stop certain job? How to specify which job to stop with `stop()`?

**Comment by ncb000gt** [comment]
You can't stop the job by name with the module. You'd want to maintain an in memory list of the job name (syntax or something similar) to the job reference and then you could stop it that way. Does that help?

**Comment by azamsolix** [comment]
Hi Nick Cambell,
I am also facing same issue.I also want to stop specify job and i don't know how to?
Could you please help me with some sample code @ncb000gt 
Thanks and regards
Azam
