### ISSUE TITLE
v1.4.0 not working

### ISSUE THREAD

**Issue by rajat12a** [kelektiv/node-cron#366]
const 
    CronJob = require('cron').CronJob;

(async function() {

    // Defining the cron
    const job = new CronJob({
        cronTime: '* * * * * *',
        onTick: () => {console.log("ok")},
        timeZone: 'Asia/Kolkata',
        start: true
    });

})();

**Comment by rajat12a** [comment]
v1.3.0 works fine, it prints ok every second
v1.4.0 prints nothing

**Comment by thujikun** [comment]
I fallen in same error too. I found this comment.
```
This has backwards incompatibility baked in, so I’m going to merge it and publish it separately later. Thanks!
```
https://github.com/kelektiv/node-cron/pull/360

**Comment by yihuaxiang** [comment]
1.4 not working + 1,and the example in you project not work tood

**Comment by MarkAdell** [comment]
v1.4.0 not working

code
```
const { CronJob } = require('cron');

const job = new CronJob('*/1 * * * * *', () => {
  console.log('Every second');
}, null, true, 'Africa/Cairo');
```

node version: 8.10.0

**Comment by andycaramba** [comment]
Hi folks.

The same issue here

I try to test 1.4.0 with the following code
```javascript
var CronJob = require('cron').CronJob;

var job = new CronJob('0 */5 * * * *', () => {
    console.log('JOB IS FIRED AT:', (new Date()).toString())
});

console.log('CURRENT DATE:', (new Date()).toString());
console.log('JOB WILL BE STARTED AT:', job.nextDates().toString());

job.start();
```
and have the following result in console
```
> $ node -v
v8.10.0

$ node test.js
CURRENT DATE: Sun Aug 26 2018 00:01:54 GMT+0500 (+05)
JOB WILL BE STARTED AT: Fri Aug 31 2018 00:00:00 GMT+0500
```

Cron strings `'* */5 * * * *'` or `'*/5 * * * *'` give the same result

**Comment by ncb000gt** [comment]
There was a bug introduced before the 1.4.0 release. We've published a new version to npm with a fix in GH-375. Please take a look. Sorry about the inconvenience this has caused. We'll be expanding the test suite as well. The examples share here are useful for that, thanks!
