### ISSUE TITLE
not working !

### ISSUE THREAD

**Issue by wybosys** [kelektiv/node-cron#372]
1.3 1.4, after test the sample

const CronJob = require('../lib/cron.js').CronJob;

console.log('Before job instantiation');
const job = new CronJob('* */10 * * * *', function() {
	const d = new Date();
	console.log('Every Tenth Minute:', d);
});
console.log('After job instantiation');
job.start();

on window\linux  with node 8.11

**Comment by sintetico82** [comment]
also for me
