### ISSUE TITLE
Are some examples buggy when running every N minutes ?

### ISSUE THREAD

**Issue by claustres** [kelektiv/node-cron#377]
I ran into an issue when trying to make a job execute every 15 minutes with the following pattern `* */15 * * * *` taken from the example folder https://github.com/kelektiv/node-cron/blob/master/examples/every_10_minutes.js#L4. Indeed, the job seems actually to be run every second during the 15th, 30th, etc. minute of an hour.

Looking at the tests I can find a different pattern for this kind of jobs, e.g. https://github.com/kelektiv/node-cron/blob/master/tests/test-cron.js#L241 or https://github.com/kelektiv/node-cron/blob/master/examples/every_30_minutes_between_9_and_5.js#L4. 

Should the pattern be `0 */15 * * * *` to run something **once** every 15 minutes ? In the case I am not wrong then the examples should be corrected.

**Comment by ncb000gt** [comment]
Yea. I actually noticed this yesterday and forgot to push the change up. I believe it is just the "every 10 minutes" example.

I'll push it up shortly. Sorry about that.

**Comment by claustres** [comment]
I think the *every_30_minutes_between_9_and_5.js* file should be updated and probably *at_10_minutes.js* as well.

**Comment by ncb000gt** [comment]
Ah, ok. I'll look through them all again. Gotta get the kids out of the house first. Thanks!
