### ISSUE TITLE
error with cron expressions

### ISSUE THREAD

**Issue by jairandresdiazp** [kelektiv/node-cron#378]
when using non-standard cron expressions, failure occurs and the job is not executed, nor does it generate an impression that the expression is invalid, so the user does not know that the job was not executed.

https://crontab.guru/#*_4-22_*_*_1-5

var cron = require('cron');

var Job = new cron.CronJob({
    cronTime: '* 4-22 * * 1-5',
    onTick: function() {
        console.log('You will see this message every second');
    },
    timeZone: 'America/Bogota'
});
Job.start();

**Comment by ncb000gt** [comment]
Ahh, we used to have a notice about faulty expressions. I'll see about adding this back in. Thanks!

**Comment by ncb000gt** [comment]
So, I looked into this some more and see a couple of exceptions around parsing that happen in the code. So, if the cron expression is invalid this should throw an exception. I'm going to close this for now since this should suffice until we do a larger rework of the code. Thanks!
