### ISSUE TITLE
How to kill a scheduled cron job ?

### ISSUE THREAD

**Issue by tgreco** [kelektiv/node-cron#384]
I'm curious if I have a rest API that creates and schedules a cron job.

How could I cancel this cron job at a future point?
Considering the reference to the job is now out of scope when I want to cancel it.

` 
        I can start it but I can't end it..

        var cronJob = CRON.job(frequency, function()
         {        

                updateFeedbackJob()
                .then(result =>
                 {
                        printMessage("updateFeedbackJob()-> finished");
                })
                 .catch(err =>
                {
                       printMessage("updateFeedbackJob()-> failed");
                        printObject(err);
                });
        });
        cronJob.start();
`

**Comment by ncb000gt** [comment]
You can stop the job by calling `cronJob.stop();`

**Comment by kamleshkarwande** [comment]
I am also having the same question. I am also not having a reference to the previously created job, Which I want to update

**Comment by ncb000gt** [comment]
@kamleshkarwande You get the reference to the job in two ways. Either by setting a variable when instantiating `var a = new Job()` and then calling `a.stop()` via a closure or something else OR by not using an arrow function for the onTick in which case the scope of the function should be the job.

Hope that helps.

**Comment by iamakshatjain** [comment]
how do I store the cron jobs to the database to kill it later?

**Comment by alan345** [comment]
> @kamleshkarwande You get the reference to the job in two ways. Either by setting a variable when instantiating `var a = new Job()` and then calling `a.stop()` via a closure or something else OR by not using an arrow function for the onTick in which case the scope of the function should be the job.
> 
> Hope that helps.

How can we save `a` in the database. So we can do some action on this job later?
