### ISSUE TITLE
how gracefully close cron ?

### ISSUE THREAD

**Issue by ipengyo** [kelektiv/node-cron#391]
How to gracefully close cron when nodejs exits ？

**Comment by ncb000gt** [comment]
You can use `job.stop()` to halt execution of the job. You can maintain a reference to the job and use it in a `process.on('...', () => { job.stop(); });` type of callback. This wont guarantee the job finishes, it will remove references to the objects and stop the timer for the `setInterval()` call.

Does that help?

**Comment by ncb000gt** [comment]
I'm going to close this ticket but let us know if this doesn't resolve your issue. Thanks!

**Comment by ipengyo** [comment]
@ncb000gt Thank you for your greetings from China.  预祝你圣诞快乐
