### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by antonsamper** [kelektiv/node-cron#395]
Could you add CHANGELOG or maybe some release notes to each release? I noticed the minor version bump to `1.6.0` and I'd like to update my package but I'm not sure what has changed or whether it will affect my plugin.

**Comment by ncb000gt** [comment]
Hey, great idea. How's this?

https://github.com/kelektiv/node-cron/blob/master/CHANGELOG

I wrote something to try to generate the changelog from commits. It's interactive and doesn't just pull in from commits (I modified the messages heavily). Let me know if you're looking for something else in this.

Thanks!

In case anyone is interested: this is the link https://github.com/ncb000gt/clh

**Comment by antonsamper** [comment]
Nice one 👍🏼 

Quick suggestion, if you add the extension “.md” it will render the file as markdown

**Comment by ncb000gt** [comment]
Forgot to respond here, but it is done. :D
