### ISSUE TITLE
Is Node-Cron the best Lib for this app?

### ISSUE THREAD

**Issue by awcchungster** [kelektiv/node-cron#396]
I have several jobs that are currently managed by cron. Let's call them job1, job2, job3. Each of these jobs run daily.

The main features I want to be able to supports:

- Cancel next run, or a specific day's run
- Reenable next run, or a specific's day's run
- Change the time for the next run, or run for a specific day (while having all other runs begin at the normal time)
- Change the params for the script being run on next run, or a specific day's run.

Is node-cron the best lib to build this in, or should I take a look at node-schedule to build a hybrid approach?

Thanks!

**Comment by ncb000gt** [comment]
I'm not super familiar with `node-schedule`. I would expect that you could do what you want with this module, but that you'd have to have to do a bunch of the plumbing yourself such as job ids, enabling and disabling jobs, etc. You can instantiate a job for a specific date no problem, but other parts would need coordination. If `node-schedule` does much of that plumbing then it might be more appropriate.

Hope that helps.

**Comment by awcchungster** [comment]
Yeah, I was thinking of keeping track of all the jobs in a dictionary layered by:

> date --> process name --> job

Whenever a change needed to happen to a certain job, I navigate the dictionary to modify the time/process params. Since I don't want to track all the jobs to infinity, I was planning to include another jobs that ensure there are always 14 days worth of jobs already scheduled. 

If anyone has some thoughts, that would be amazing!

**Comment by ncb000gt** [comment]
I'm not sure I fully understand the case you're trying to handle with this. If you want jobs to run daily you can do that with a basic cron, something like `0 15 10 * * *` which would run the job at 10:15 every day dependent on your timezone and the timezone you specify.

Based on your OP it seems like you need something that can have a bit more control like a job that runs every hour or 15 minutes or something like that. You could have your jobs stored in redis, psql, or some other store outside of the node process (don't want that to disappear if the node proc dies for some reason). Then when you run the cron, it would check the store to see if something should run in that window (15 mins or whatnot). If so, it runs the job, if not, it doesn't run and just moves on. The params for the process that runs would be specified in the data store, and then you're dealing with one cron job that just runs somewhat frequently.

Does that makes sense? Again, I may not fully understand your use case so YMMV.

**Comment by awcchungster** [comment]
I think your suggestion will work. Currently in the process of building it. I have a question on the onTick param. Is it possible to pass in variables into the function? I was looking to create a cronjob with some preloaded details. 

> onTick - [REQUIRED] - The function to fire at the specified time. If an onComplete callback was provided, onTick will receive it as an argument. onTick may call onComplete when it has finished its work.

Thanks!
