### ISSUE TITLE
cronjob runs abnormal on mac

### ISSUE THREAD

**Issue by cnwesleywang** [kelektiv/node-cron#397]
MacOS Mojave

node --version
v8.9.3

cat node_modules/cron/package.json  | grep "version"
  "version": "1.6.0",

> var CronJob = require('cron').CronJob;
undefined
> (new CronJob('* * */3 * * *', ()=>{console.log(new Date(), 'hi');})).start();
undefined
> 2018-12-30T01:28:29.006Z 'hi'
2018-12-30T01:28:30.006Z 'hi'
2018-12-30T01:28:31.002Z 'hi'
2018-12-30T01:28:32.004Z 'hi'
2018-12-30T01:28:33.002Z 'hi'
2018-12-30T01:28:34.003Z 'hi'
2018-12-30T01:28:35.006Z 'hi'

it should be run like every 3 hours, but it goes every sec.

If I add the timezone parameter it works fine.

> var CronJob = require('cron').CronJob;
undefined
> (new CronJob('* * */3 * * *', ()=>{console.log('hi');}, null, true, 'America/Los_Angeles')).start();
undefined
> 

but if I use another valid timezone, it fail again!

> var CronJob = require('cron').CronJob;
undefined
> (new CronJob('* * */3 * * *', ()=>{console.log(new Date(), 'hi');}, null, true, 'Asia/Shanghai')).start();
undefined
> 2018-12-30T01:34:59.007Z 'hi'
2018-12-30T01:35:00.001Z 'hi'
2018-12-30T01:35:01.004Z 'hi'
2018-12-30T01:35:02.006Z 'hi'
2018-12-30T01:35:03.005Z 'hi'
2018-12-30T01:35:04.006Z 'hi'

Seems there is some problem when parsing timezone.

Please, help.

**Comment by ncb000gt** [comment]
The syntax is wrong. To run every 3 hours you'd need something more like `0 0 */3 * * *`, otherwise I'd expect it to run every second AND every 3 hours (which would be the same given the second level granularity)

Does that help?.

**Comment by ncb000gt** [comment]
You can find some examples of this here: https://github.com/kelektiv/node-cron/blob/master/examples/every_10_minutes.js and in other places in the examples directory.

**Comment by ncb000gt** [comment]
Awesome. Glad it helped! Happy coding.
