### ISSUE TITLE
onTick Function Params

### ISSUE THREAD

**Issue by awcchungster** [kelektiv/node-cron#399]
I have a question on the onTick param. Is it possible to pass in variables into the function? I was looking to create a cronjob with some preloaded details. 

> onTick - [REQUIRED] - The function to fire at the specified time. If an onComplete callback was provided, onTick will receive it as an argument. onTick may call onComplete when it has finished its work.

Thanks!

**Comment by ncb000gt** [comment]
For some reason I thought we'd done this, but it seems like that isn't accurate. For now you can likely use `.bind()` in es6+ or `_.bind()` from underscore or lodash: https://lodash.com/docs/4.17.11#bind

Does that help?

**Comment by awcchungster** [comment]
Apologies-- a little more documentation would be really helpful here. 

This is my constructor now. LaunchHelper is another function. res[i] contains the 2 launch params I have. Where should I be adding the bind?

const job = new CronJob({
	cronTime: "* * * * * *", 
	onTick: function(){
		launchHelper(res[i].process_name, res[i].params)
	}
	start: true,
        timeZone: 'America/Los_Angeles'
})

**Comment by awcchungster** [comment]
The following more or less is the entire relevant function. This code is not yet working.

```
async function launchStandard(){
	let standard_processes = await db.getAllProcesses().then((res) => {
		for(var i = 0; i < res.length; i++){
			if(res[i].enabled){
				const job = new CronJob({
					cronTime: res[i].cron_time, 
					onTick: function(){
						launchHelper(res[i].process_name, res[i].params)
					}
					start: true,
					timeZone: 'America/Los_Angeles'
				})
				logger.info('Enabling ' + res[i].process_name + ".")
			}
		}
		logger.info('Standard Processes Launched.');
	})
}
launchStandard()
```

> In this case you'd likely want to add the bind to the ontick callback and
> pass in res[i].

Should the main constructor look something like this? A quick example would be helpful so I can understand how the callbacks are interacting with the bind.

```
const job = new CronJob({
	cronTime: res[i].cron_time, 
	onTick: function(){
		launchHelper(res)
	}.bind(onCallback)
	start: true,
	timeZone: 'America/Los_Angeles',
        onCallback: res
})
```

Thanks in advance!

**Comment by ncb000gt** [comment]
Yea. Sorry. On my phone now, about to head to bed, I'll respond tomorrow
with an example. :)

**Comment by ncb000gt** [comment]
So, for the function you provided above, I'd look at doing something like this.

```
async function launchStandard(){
	let standard_processes = await db.getAllProcesses().then((res) => {
		for(var i = 0; i < res.length; i++){
                         const proc = res[i]
			if(proc.enabled){
				const job = new CronJob({
					cronTime: proc.cron_time, 
					onTick: function({ process_nam, params }){
						launchHelper(process_name, params)
					}.bind(null, proc)
					start: true,
					timeZone: 'America/Los_Angeles'
				})
				logger.info('Enabling ' + proc.process_name + ".")
			}
		}
		logger.info('Standard Processes Launched.');
	})
}
launchStandard()```

or something like that.

**Comment by awcchungster** [comment]
This was amazing! I really appreciate your hard work maintaining this lib. 

As a quick suggestion, I think this is worth adding an example in the repo.
