### ISSUE TITLE
After running for a while, cron starts firing twice

### ISSUE THREAD

**Issue by Ratstail91** [kelektiv/node-cron#401]
I have this discord bot: https://github.com/Ratstail91/discordbot

It used node-cron to post an inspirational quote to a discord channel named bot-spam at 7am. After running it normally for a while, it suddenly starts posting twice a day.

This might be related to #180, but I don't think so. I'm using node-cron 2.0.3, and only becomes visible after days or weeks of use; I'm not sure of the time frame exactly.

**Comment by ncb000gt** [comment]
Hmm. I think you filed this issue in the wrong project. This is the original `cron` package on npm: https://www.npmjs.com/package/cron

If you do end up using this package and notice an issue here then feel free to post back here. Hope you can find a resolution to your issue though!

**Comment by Ratstail91** [comment]
Isn't that just the same project as this? Clicking on the github link there takes you back here as well.

I don't see anywhere there to report a bug.

**Comment by ncb000gt** [comment]
@Ratstail91 it isn't. the project listed in your dependencies is https://www.npmjs.com/package/node-cron not https://www.npmjs.com/package/cron.

This project is the latter. You'll probably have to check https://github.com/node-cron/node-cron/issues for issues related to that project. But, as I said above, if you decide to use this project I'd be more than happy to help. :)

**Comment by Ratstail91** [comment]
I see, my mistake. Thank you very much!

**Comment by ncb000gt** [comment]
No worries. :) GL.
