### ISSUE TITLE
Replace moment.js with an alternative date library

### ISSUE THREAD

**Issue by antonsamper** [kelektiv/node-cron#402]
I noticed on Bundle Phobia that this module is just over 100kb when minified and gzipped

https://bundlephobia.com/result?p=cron@1.6.0

And the majority of the size is coming from `moment.js`.

As an idea and if possible it would be nice to replace `moment.js` with a different lighter library such as:
- https://github.com/date-fns/date-fns
- https://github.com/iamkun/dayjs

Has this been considered before?

**Comment by saltire** [comment]
Another option is Luxon: https://moment.github.io/luxon/

I'm sure a pull request for this issue would be welcome ;)

**Comment by antonsamper** [comment]
I'll have a look when i get some downtime

**Comment by ncb000gt** [comment]
I'd certainly entertain a pr for this. Thanks!

**Comment by tgensol** [comment]
Any progress on this one ? :) 

Thanks

**Comment by antonsamper** [comment]
I'm slammed at the moment so I havent had a chance to look into this properly yet

**Comment by Unitech** [comment]
Any news on that one? 450kb for a cron library is clearly obese

**Comment by ncb000gt** [comment]
I've landed GH-486 which uses luxon. It hasn't hit npm yet, as I'm going to try to roll a few changes into the next release. Sorry this has taken so long to happen and a big thanks to @bvigursky for implementing it.

**Comment by wbt** [comment]
Hi nbc000gt,

Greetings!  This is just a friendly check-in to see how things are doing with the few changes intended to be rolled into that next release.
