### ISSUE TITLE
How can i pass parameter to the function?

### ISSUE THREAD

**Issue by rzbrme** [kelektiv/node-cron#404]
What im trying to achieve is set a job and when its time i need to do some db stuff.

Ex,

const job = new CronJob( moment().add(2, 'm'), function(userProfile) {
        console.log('User information: ' + userProfile.email); });

job.start();

So the cron runs, but i get userProfile undefined when it runs. When i console.log it before the job it is there. Is there something im doing wrong?

thanks

**Comment by MichaelLiss** [comment]
I asked the same question.  Here is what I am doing that works:

        noop = (engine) => {
            var debugThis = false;
            if(debugThis){
                var now = new Date();
                console.log(`${now} noop called with ` + JSON.stringify(engine));
            }
        }


        configureCronJobs = (engine) => {
            var debugThis = false;

            if(debugThis){
                console.log('engine ' + JSON.stringify(engine));
            }

            const cg = new CronGroup({
                timezone: engine.timezone
            });

            cg.add({
                name: "No Op",
                schedule: '0 */1 * * * *', // every 1 minutes
                worker: () => noop(engine),
            });

            cg.on('run', ({name, runnedBy}) => {
                if(debugThis){
                    var now = new Date();
                    console.log(`${now} running ${name}`);
                }
            });
            
            cg.on('complete', ({name, runnedAt, completedAt}) => {
                if(debugThis){
                    var now = new Date();
                    console.log(`${now} completed ` + JSON.stringify(name));
                }
            });
            
            cg.on('error', ({name, err}) => {
                console.error(`${name} is completed with error\n${err.stack || err}`);
            });
        };

**Comment by ncb000gt** [comment]
@rzbrme That wouldn't work unless you set the `context` of the job itself or bound the onTick and passed in userProfile. Otherwise cron wont have any idea what userProfile is.

Does that help answer your question? Sorry about the late reply, I missed this question.

**Comment by zyf0330** [comment]
@ncb000gt Hello, I need use this to access class method, and I need to access job self too.
Expect use codes like `const classThis = this` to achieve my need, can node-cron supports to pass custom parameters into `onTick`?
