### ISSUE TITLE
cron reached maximum iterations.

### ISSUE THREAD

**Issue by chrisle** [kelektiv/node-cron#405]
Time Zone: "" - Cron String: 0 0 2 * * 0 - UTC offset: -07:00 - current Date: Sun Mar 03 2019 03:42:00 GMT-0800

**Comment by MichaelLiss** [comment]
> Time Zone: "" - Cron String: 0 0 2 * * 0 - UTC offset: -07:00 - current Date: Sun Mar 03 2019 03:42:00 GMT-0800

I see what you wrote... but do not understand the problem ?

**Comment by shuat** [comment]
@chrisle see https://github.com/kelektiv/node-cron/issues/408#issuecomment-471242670 I created a PR that was already merged in. Not sure it was pushed to npm yet.

**Comment by ncb000gt** [comment]
I just published the PR to npm as 1.7.0. I'm going to close this as of now, but let me know if you see it again. Thanks.
