### ISSUE TITLE
TypeScript Definitions?

### ISSUE THREAD

**Issue by ztzven** [kelektiv/node-cron#406]
Definition files would be very useful for this project! If you could provide them that would be great, otherwise I could make a pull request at some later date with them :)

**Comment by ncb000gt** [comment]
Hey, if you have time and would be willing to throw up a prescription that would be awesome. Thanks!

**Comment by kevin68** [comment]
They are already available on [DefinitelyTyped](https://www.npmjs.com/package/@types/cron).

**Comment by ztzven** [comment]
You're right!
