### ISSUE TITLE
I can't destory a job. It says "not a function" error. 

### ISSUE THREAD

**Issue by idreamer** [kelektiv/node-cron#407]
Hello. 

I am working on a feature to start and destroy cron jobs using node-cron. 
Successfully I created the jobs and by the way I would like to destroy the jobs at any time. 

But it show an error log below. 
`TypeError: testJob.destory is not a function`

Please help me to solve this issue.

**Comment by ncb000gt** [comment]
We have start and stop and that's it. Do you have any sample code?

**Comment by ncb000gt** [comment]
@idreamer did you figure it out?

**Comment by idreamer** [comment]
Sorry about that. It was a typo error. I fixed it.

**Comment by ncb000gt** [comment]
Ahh. Glad to hear. :) Thanks.
