### ISSUE TITLE
Restart or kill jobs when deploying to server

### ISSUE THREAD

**Issue by judemanutd** [kelektiv/node-cron#412]
The library works perfectly but I had a question with regards to creation of the cron jobs.

I am currently deploying the node app to an ec2 instance by first building the app and then running `node app.js` which starts the server.

When I re-deploy the app ie, re-build and re-run `node app.js`, will it overwrite existing jobs on the server or will it create new jobs?

Currently the `app.ts` looks like this

```typescript
import express, { Application, Request, Response, NextFunction } from "express";
import { schedulePeriodicCheckJob } from "./utils/cronHelper";

/*** More commands ***/

schedulePeriodicCheckJob();

/*** More commands ***/

app.use(router);

export default app;

```

`cronHelper.ts`

```typescript
import cron from "cron";

const CronJob = cron.CronJob;

export const schedulePeriodicCheckJob = () => {
  const job = new CronJob(
    "1 1 */1 * * *", // run every 1 hour
    () => {
      // const d = new Date();
      console.log("on Tick:");

      // long running task
    },
    () => {
      console.log("on Complete");
    },
    true
  );
};

```

**Comment by ncb000gt** [comment]
@judemanutd This module runs _inside_ the node process. So, if you kill the node process, you kill the job. It doesn't directly modify your /etc/cron* files/directories.

Does that help?

**Comment by judemanutd** [comment]
@ncb000gt understood, what about situations where say hot reloads are involved such as using nodemon, the node process isn't killed there, instead it's restarted, in those situations will the job be overwritten or a new one created that's an exact replica of the existing job.

**Comment by ncb000gt** [comment]
So, that's a little complicated. In part it depends on your code. If you instantiate the job every time the node process starts up then the job will start up every time you start up a node process. The node process _is_ killed, it's just that nodemon runs and manages child processes afaik. So, nodemon will kill that child process, or watch for it to die, then it starts a new process. This should restart your cron instantiations. I'm using pm2 locally and this is how it works for me.

So, the short answer is, nodemon should kill the prior process and cron jobs with it, and then the new process would instantiate replicas assuming you're instantiating them on startup of the code.

Does that make sense?

**Comment by judemanutd** [comment]
@ncb000gt that makes alot of sense, thank you for that insight and explanation, that answers all my questions.

**Comment by ncb000gt** [comment]
Awesome. Glad I could help.
