### ISSUE TITLE
Cron reached maximum iterations

### ISSUE THREAD

**Issue by rfenaux** [kelektiv/node-cron#413]
Time Zone: "" - Cron String: 0 0 10 * * * - UTC offset: +01:00 - current Date: Sat Mar 30 2019 10:10:29 GMT+0000

**Comment by ncb000gt** [comment]
Which version of the module are you using?

**Comment by ncb000gt** [comment]
@rfenaux if you're using an older version of the addon please upgrade to the latest. This issue was resolved in a more recent version. See GH-414 and GH-408.

Thanks!
