### ISSUE TITLE
Jobs increase rapidly if first field is * .

### ISSUE THREAD

**Issue by tboulis** [kelektiv/node-cron#417]
This is a weird issue:
i use `kue` to enqueue the jobs that my worker creates. If i use the `* */30 * * * *` pattern for the worker the job is somehow forking(?)/running indefinitely and not once every 30 min as the pattern indicates. However, if i remove the first asterisk and have only 5 fields it works.
I don't know if this is intended or not, so apologies in advance if I'm wrong.

Environment:
node: 10.15.3
cron: 1.7.0
ubuntu: 18.04

**Comment by ncb000gt** [comment]
The pattern is wrong. if you want it to run every 30 mins you need `0 */30 * * * *`. That should get you what you want. The first place is seconds. :)

Does that help?

**Comment by tboulis** [comment]
@ncb000gt yeap that helps, I just thought that it may be an issue. Thanks for your help! :)

**Comment by ncb000gt** [comment]
Np!
