### ISSUE TITLE
how to validate if cron expression is valid or not?

### ISSUE THREAD

**Issue by akalitenya** [kelektiv/node-cron#419]
I plan to get cron expression from app users. So i need to validate it.

**Comment by snehalhumne** [comment]
Hi, There is the best site that can be very helpful to validate the Cron expression.
Hope it helps. :) Although I am not sure what exactly you mean by from app users!
https://crontab.guru/#0_3_*_*_*

**Comment by akalitenya** [comment]
Hi. I am asking if there is a way to validate cron expressions using this library, because in my case this expressions are provided by end users of my app.

**Comment by ncb000gt** [comment]
Hey, sorry I'm just responding.

You should have access to a Crontime object. If you try to instantiate that
you _should_ get presented with an error if it cannot parse it. If this
doesn't happen, let me know.

Does that help?

**Comment by GuillaumeRochat** [comment]
I looked at the code and I see 2 potential issues with using CronTime for cron expressions validation.

1. CronTime add defaults if the expression has less than the minimal amount of parameters. So `* *` would be valid in CronTime, which might give you false positive.

2. The alias can be used in as a step, which will make steps of the alias number. E.g.: `new CronTime('* * * * */jan *')` is accepted. I'm assuming that's a bug? crontab.guru accepts it though, but it doesn't really make sens to allow that. (https://crontab.guru/#0_3_*_*/jan_*)

**Comment by akalitenya** [comment]
@ncb000gt yes it works, thanks! I try instantiation and catch if there is error!

**Comment by ncb000gt** [comment]
@GuillaumeRochat Yea, that makes sense to me. I've had plans to rewrite the crontime parser for a long time and just haven't found the time to do so. But, if I get around to it, i'll add a proper "validator" into it. I just haven't been able to find the time, and the others that exist haven't given me what I wanted or covered the cases that this module has grown to cover. So, until I can get that done it's probably going to remain that way, unless someone wants to take a stab at it.

For now, it seems like the initial case was covered with my suggestion, but I'll keep this in mind if I do get the time to work on the parser.

**Comment by GuillaumeRochat** [comment]
@ncb000gt I actually did one because we needed it and published it about 2 weeks ago. I didn't think to come back here to reference it. https://github.com/TheCloudConnectors/cron-validator

Your comments are very welcomed, as I am no expert in cron, and really only tried to validate the base use cases. The code might be longer than needed but I needed clarity for the first version.
