### ISSUE TITLE
cron job is firing twice

### ISSUE THREAD

**Issue by Alisher778** [kelektiv/node-cron#421]
When I use a basic cronjob it is firing twice. Here is the sample code:
```
router.get('/cron-job', (req, res) => {
    const day = new Date();
    const myJob = new CronJob({
        cronTime: '20 * * * * *',
        onTick: function() {
           console.log('Job is started');
      }
   });
   myJob.start();
   res.send('Started')
})
```
I would really appreciate If you have any workarounds. Thanks.

**Comment by ncb000gt** [comment]
That job shouldn't fire twice unless you are getting two requests to your endpoint. I'd isolate the example from route handler and try it out there. If you're still getting double execution let me know.

Does that help?

**Comment by Alisher778** [comment]
Thank you @ncb000gt. It is working as expected If I use it without the route. How can I solve the issue with the route?

**Comment by Alisher778** [comment]
I have found the issue. The chrome extension was making an extra get request and I removed the JSON viewer extension and it is working well.

**Comment by ncb000gt** [comment]
Awesome. Glad it worked for you!

**Comment by NareshKukreti12** [comment]
@ncb000gt  I am also facing the same issue. CRON  is firing twice. Here is my code
`var job2 = new CronJob('00 00 10 * * *', (res) => {
    woStatusCheck();
}, null, false, 'Asia/Kolkata');
job2.start();`
