### ISSUE TITLE
cronJob will happen on specific count

### ISSUE THREAD

**Issue by sathik-basha** [kelektiv/node-cron#427]
Ex: If i set the cronjob every one hour.. But it will be halt on fourth count.

**Comment by mordof** [comment]
Just looking at the documentation, you could keep a count, then once the count has reached a certain amount, simply call `job.stop()` to turn the job off.

**Comment by ncb000gt** [comment]
@sathik-basha if you're trying to halt after a certain number of executions like @mordof suggested then their approach is a perfect solution.

If you're looking for something built in then I'd be open to reviewing a pr for that, but it is not currently supported.

Does that help?
