### ISSUE TITLE
How to add some delay between multiple callbacks?

### ISSUE THREAD

**Issue by viplavkumar96** [kelektiv/node-cron#428]
I have multiple callbacks in a cronjob which do similar work but they have some dependencies(DB access) and it takes some to process each callback. Because of this other callbacks are executed but raise an error because there is a lock on DB. Can we some delay between each callback?

**Comment by viplavkumar96** [comment]
`let job = new CronJob(cronTime,null, null, true, 'Asia/Kolkata');
//For loop-for each request, I am adding a calling job.addCallback()
operation.addCallback( ()=>
      onTickCallback(reqArgs));

//Each Callback is executed but not fully as once a callback locks a DB write access
async function onTickCallback(req){
  //DB access
}
//Method to add a delay between each callback?

`

**Comment by KhanhHH** [comment]
@viplavkumar96 try this
`  let isTaskCompleted = false;
  const processPendingJob= new CronJob('*/5 * * * * *', async () => {
    if (!isTaskCompleted) {
      isTaskCompleted = true;
      await processQueryInDatabase();
      isTaskCompleted = false;
    }
  });
  processPendingJob.start();`

**Comment by ncb000gt** [comment]
There is no way to reasonably add a delay between callback executions. This would slow everything down.

What I'm curious about is why you're having locking issues. I'm guessing this is more of an architecture type discussion. Without knowing much about what you're trying to do this is what I'd imagine you could do.

1. If you don't care about runs that "fail", then just through a try/catch around the executed code and let it fail without crashing the execution.
2. If you need to have every callback run and _can consolidate_ the executed code, then use async/await, callbacks, promises, or something like that to chain together the execution of subsequent, and reliant code. So, if you have something that needs to update a row, and the next code needs to update that same row then make sure it executes after.
3. If you cannot consolidate the executed code, then you'll probably need to have a blend of what @KhanhHH mentioned where you are tracking a "mutex" type variable inside the execution and then checks to see if the lock has been released. The hard part there is that you're likely to run into issues if your cron settings are low and the execution is long so this approach will get tricky to deal with.

Does that help?
