### ISSUE TITLE
Sunday problem in computing nextRunAt

### ISSUE THREAD

**Issue by sheikirfanbasha** [kelektiv/node-cron#430]
If I have an cron expression to run every day at a given time say "9:30 PM". In computing the `_getNextDateFrom` if the given date is a `Sunday` then the behaviour is wrong. Please let me know if I am missing something or it is an issue with the core code.

```js
// load the cron module
const {CronTime} = require('cron');
// make the cron expression 
// to run At 09:02 PM, only on Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, and Sunday
const cronTime = new CronTime("0 02 21 * * 1,2,3,4,5,6,7");

// Showing the right behaviour
// any date which is not a Sunday
// Eg: 6/22/2019, 10:06:12 AM
var startDate1 = new Date("2019-06-22T04:36:12.588Z");
 let nextDate1 = cronTime._getNextDateFrom(startDate1, "Asia/Kolkata");
 var x1 = nextDate1.format();
// output: 6/22/2019, 9:02:00 PM
 console.log(new Date(x1).toLocaleString());

// Showing the problem
// any date which is a Sunday
// Eg: 6/23/2019, 10:06:12 AM
var startDate2 = new Date("2019-06-23T04:36:12.588Z");
let nextDate2 = cronTime._getNextDateFrom(startDate2, "Asia/Kolkata");
var x2 = nextDate2.format();
// output: 6/24/2019, 9:02:00 PM. But the expectation is 6/23/2019, 9:02:00 PM
console.log(new Date(x2).toLocaleString());
```

**Comment by honzahommer** [comment]
@sheikirfanbasha Days in week begins with 0 and if you want to run task every day, you should use `*`. These patterns are same.
`const cronTime1 = new CronTime("0 2 21 * * 0,1,2,3,4,5,6");`
`const cronTime2 = new CronTime("0 2 21 * * 0-6");`
`const cronTime3 = new CronTime("0 2 21 * * *");`

**Comment by sheikirfanbasha** [comment]
> @sheikirfanbasha Days in week begins with 0; and if you want to run task every day, you should use `*`. These patterns has same behaviour.
> `const cronTime1 = new CronTime("0 2 21 * * 0,1,2,3,4,5,6");`
> `const cronTime2 = new CronTime("0 2 21 * * 0-6");`
> `const cronTime3 = new CronTime("0 2 21 * * *");`

Thank you @honzahommer . You are right! I missed to notice week days range is only [0-6] but I have mentioned 7 in the cron expression.
