### ISSUE TITLE
How could I search for a specific process

### ISSUE THREAD

**Issue by YuriFontella** [kelektiv/node-cron#431]
How could I search for a specific process to be able to stop?
When I start a job, is it possible to have a callback with some process ID?

**Comment by ryonguyen** [comment]
Hi, did you find away? I have same problem, Can u show me your solution?

**Comment by YuriFontella** [comment]
@ryonguyen I had to work with logic.
For example, when I start a job, inside I check the status of my service. When the job is called and the status has changed within the system, it cancels the job.
