### ISSUE TITLE
npm WARN moleculer-cron@0.0.2 requires a peer of moleculer@^0.11.0 but none is installed.

### ISSUE THREAD

**Issue by babnik63** [kelektiv/node-cron#437]
When installing on latest version of moleculer it gives this error:
npm WARN moleculer-cron@0.0.2 requires a peer of moleculer@^0.11.0 but none is installed.

you should fix something in packaging.
Thanks

**Comment by ncb000gt** [comment]
I updated the dependencies in this package and published. However, I looked at the version in the molecular-cron project and it appears they are relying on `^1.3.0` which is a pretty old version of cron.

You should ask them to update to the latest which is `1.7.2`.
