### ISSUE TITLE
Refactor tests to use Jest.

### ISSUE THREAD

**Issue by ncb000gt** [kelektiv/node-cron#439]
This isn't about adding new tests, but is just about reworking all of the tests to use Jest. It's something that has been in my to-do for quite a while.

**Comment by florenciasilva** [comment]
Hi! I would love to work on this!

**Comment by ncb000gt** [comment]
@florenciasilva Haha. Sorry about that. If you're interested, there are still other tasks available that I'd love some help with. Feel free to take a look at the backlog. But, no worries if not and thanks for the interest in the first place!
