### ISSUE TITLE
cron stop after change server time

### ISSUE THREAD

**Issue by Foxhound401** [kelektiv/node-cron#447]
Sorry I'm pretty new to work with cron, I set up 2 cron job like below, the first job run at minute 16 but when i change time to 17:59:55, the first cron will finnish and stop, the second cron doesn't run at all  

                        let scheduleTime = '* 16-17 * * * *';
                        console.log("Duong: insertDatabase -> Cron 1")
                        new CronJob({
                         cronTime: scheduleTime,
                            onTick: function() {
                                // console.log(c++);
                                console.log(moment().format('HH:mm:ss'));
                            },
                            start: true,
                            timeZone: 'UTC'
                        });

                        console.log("Duong: insertDatabase -> End Cron 1")

                        console.log("Duong: insertDatabase -> Cron 2")

                        scheduleTime = '* 18-19 * * * *';

                        new CronJob({
                            cronTime: scheduleTime,
                            onTick: function() {
                                // console.log(c++);
                                console.log('New cron' , moment().format('HH:mm:ss'));
                            },
                            start: true,
                            timeZone: 'UTC'
                        });
                            
                        console.log("Duong: insertDatabase -> End Cron 2")

If you have the time to look into this and point me to the right direction, I will be greatly appreciated. The problem just happen when i change the time on the server (my machine) (both window and linux). if i don't change the server time, it's running just fine

**Comment by ncb000gt** [comment]
The first job should run from minute 16 - 17 and the second from 18-19.

If you changed the time _during_ the execution of cron 1 to what you shared above then I would expect that job to complete as you haven't explicitly stopped it. But, I wouldn't expect job 2 to start until the minute ticks to 18-19 again. Also, if you changed the time to what is shown above, I'd expect the first job to run again _before_ you hit the second job since you'll hit 16-17 again before.
