### ISSUE TITLE
`0/2 * * * * *` seconds field range

### ISSUE THREAD

**Issue by mwiktorczyk** [kelektiv/node-cron#449]
Hi,
I am trying to run the cron every two seconds but starting with the odd second.
`1/2 * * * * *` expression causes a job to run every minute instead.
The one and only workaround I found is to enumerate all values like `1,3,4,7,9,[...],55,57,59 * * * * *`

Example apps:
```js
const cron = require("cron");
const cronJob = new cron.CronJob("*/2 * * * * *", () => console.log(new Date().toISOString()));
cronJob.start();
// 2019-11-29T14:18:40.006Z
// 2019-11-29T14:18:42.003Z
// 2019-11-29T14:18:44.003Z
// 2019-11-29T14:18:46.003Z
```

```js
const cron = require("cron");
const cronJob = new cron.CronJob("1/2 * * * * *", () => console.log(new Date().toISOString()));
cronJob.start();
// 2019-11-29T14:19:00.015Z
// 2019-11-29T14:20:00.051Z
```

**Comment by nmay231** [comment]
One solution is to use a range with the step of 2: `"1-59/2 * * * * *"`

However, this should probably be updated so `"1/2 * * * * *"` gives the desired behavior. It's literally a one line change if I understand it correctly.

```diff
// line 479
-upper = upper ? Math.min(high, ~~Math.abs(upper)) : lower;
+upper = upper ? Math.min(high, ~~Math.abs(upper)) : high;
```

I could open a PR if this is reasonable @ncb000gt
