### ISSUE TITLE
Change CronTime after job is created

### ISSUE THREAD

**Issue by archonitex** [kelektiv/node-cron#45]
I'm trying to find out if there's a way to change the CronTime of a job after the job is created..

I have tried using the CronTime object, but it does not seem to respect it's own prototype as it does not find the parse method:

What I have tried :

job.cronTime = require('cron').CronTime("0 10 \* \* *","America/Montreal");

but when I try that I get 

TypeError: Object # has no method '_parse' at Object.CronTime (cron.js:24:10)

**Comment by zc01** [comment]
Is this working now? 
I tried the following code:
var cron = require('cron');
var cronJob = cron.job("0 */2 * * * *", function(){
    // perform operation e.g. GET request http.get() etc.
    console.info('cron job completed');
}); 
cronJob.start();
var cronTime=cron.CronTime("0 * * * * *");
cronJob.setTime(cronTime);

and got the following error:
~/node_modules/cron/lib/cron.js:20

		this._parse();
		     ^
TypeError: Object #<Object> has no method '_parse'

Is something wrong with my code?
thanks
