### ISSUE TITLE
Jobs run without being started

### ISSUE THREAD

**Issue by chhatch** [kelektiv/node-cron#450]
According to the docs: "You need to explicitly start a job in order to make it run. This gives a little more control over running your jobs." This is not the case for me. Code to reproduce:

```node
const CronJob = require('cron').CronJob

new CronJob('* * * * * *', () => console.log('I still run!'), null, true, 'America/Chicago')
```

**Comment by aneyo** [comment]
You set `start` parameter to `true` (4th parameter at constructor)
https://github.com/kelektiv/node-cron#api

**Comment by chhatch** [comment]
That's what I get for not reading all of the documentation. It's a bit confusing that the **Usage (basic cron usage)** section has the start parameter set to true in the example code and says that jobs must be started explicitly. Thank you for the quick reply.

**Comment by WangHansen** [comment]
I was going to ask this as well. In the example code in document:
```javascript
var CronJob = require('cron').CronJob;
var job = new CronJob(
	'* * * * * *',
	function() {
		console.log('You will see this message every second');
	},
	null,
	true,
	'America/Los_Angeles'
);
job.start();
```
It says: 
> Note - You need to explicitly start a job in order to make it run. This gives a little more control over running your jobs.
Should this be changed so that it is more clear.
