### ISSUE TITLE
Cron runs at wrong time

### ISSUE THREAD

**Issue by Gotemperor** [kelektiv/node-cron#451]
Hi, I am trying to run cronjob at 15.01 (3 pm) every day.
I am using it to send sms reminders.
In the begining it was working, but a few days after I did the cronjob I start receiving the reminder at 12 AM. Why?

I am using this code:

var sendConformationSmsJob = new CronJob({
   cronTime: '00 */1 */15 * * *',
    onTick: function () {
        console.log('Performing SendEmail check: ', new Date());
        findBooking();
    },
    //null,
    start: false,
    timeZone: 'Europe/Stockholm'
});

sendConformationSmsJob.start();

Can you please help me?

**Comment by Gotemperor** [comment]
Also the server time zone is the same as in cron -  'Europe/Stockholm'

**Comment by CliffS** [comment]
> cronTime: '00 */1 */15 * * *'

You currently seem to be trying to trigger this cronjob every minute and every 15 hours.  You need it to be:

`crontime: '0 1 15 * * *'`
