### ISSUE TITLE
Saving node-cron object to database

### ISSUE THREAD

**Issue by iamakshatjain** [kelektiv/node-cron#452]
I am building a scheduling application, that schedules tasks as per the user's need and unschedules them as well. I wanted to save the created node-cron to firebase (cloud firestore) so that I can kill the cron job later if the user desires to. I tried turning the cron job object into JSON ( by `JSON.stringify()` ) to do the same. For that, I had to set the `context` property to `null` as the object has cyclic references. This got stored okay, but the information from the entire cron job object is lost. When I turn it back to JS object ( by `JSON.parse()` ), I cannot access the stop method.

Can anyone help me with the same?

**Comment by iamakshatjain** [comment]
Before `JSON.stringify()`
![before](https://user-images.githubusercontent.com/32021987/71582989-8486b000-2b32-11ea-8e03-1e21443f2174.png)
After `JSON.parse()`
![after](https://user-images.githubusercontent.com/32021987/71583006-949e8f80-2b32-11ea-8e31-efd437f2926a.png)

**Comment by cah-brandon-trebbien** [comment]
👍 what is the easiest way to accomplish this to be able to reference specific already scheduled jobs?

**Comment by tristan957** [comment]
just save the cron syntax `* * * * 5`.... and create a new job. Your solution is not a good way to solve the problem.

**Comment by iamakshatjain** [comment]
I need to do so to provide crash protection as well as unschedules jobs as per the user's need so I want to access it from the firebase to stop it later.

**Comment by ncb000gt** [comment]
@iamakshatjain We spoke about this in DMs on twitter, were you able to figure out a solution?

**Comment by mohammad-babaei** [comment]
I have the same requirement (to store the object to access it later to stop the cronjob) and i don't have access to your twitter DMs.
Could you help me with this
