### ISSUE TITLE
runOnInit does not work 

### ISSUE THREAD

**Issue by johnico** [kelektiv/node-cron#453]
Hi , I have the following cron object 

```
   const job = new CronJob({
            cronTime: `0 */1 * * * *`,
            onTick() {
                logger.debug('log');
     
            },
            start: true,
            runOnInit: true
        });

 job.start()
```

and I see that its no matter what I set in `runOnInit` and it always executes in  `XX:XX:00`

btw I am using NestJs but define the cron  object from your package

**Comment by ncb000gt** [comment]
I'm not seeing this behavior. I have an example that seems to work:

```javascript
const CronJob = require('../lib/cron.js').CronJob;

console.log('Before job instantiation');
new CronJob({
	cronTime: '* * 10-23 * * *',
	onTick: function() {
		const d = new Date();
		console.log('Every second:', d);
	},
	start: true,
	runOnInit: true
});
console.log('After job instantiation');
```

The output is this:
```
Before job instantiation
Every second: 2020-01-24T13:27:22.587Z
After job instantiation
```

The onTick shouldn't fire outside of the `runOnInit` in my case because it isn't yet between the hours I've specified. Do you notice the same behavior or something different?

**Comment by flashtheman** [comment]
Has this been solved. I have the same issue and don't understand @ncb000gt 's answer. runOnInit only gets called first after 5 minutes in my case.

```
    const job = new cron.CronJob({
        cronTime: '*/5 * * * *',
        onTick: () => {
            console.log('Running reminder job...', Date.now())
            updateQueue()
        },
        start: true,
        timeZone: 'UTC',
        runOnInit: true
    })
```

**Comment by ncb000gt** [comment]
I closed the issue because it was working for me in my tests case.

runOnInit is mostly a convenience. If it doesn't appear to be working for you, you can call the function outside of the ontick and you'd have the same behavior.

**Comment by flashtheman** [comment]
thanks, I'll do that.
