### ISSUE TITLE
Invalid exception: Field has an invalid range

### ISSUE THREAD

**Issue by mastepanoski** [kelektiv/node-cron#455]
The change introduced in the version 1.8.0 introduces breaking changes that are not compatibles with the expected behaviour in the standard cron. ([Cron Hour Range](https://crontab.guru/hour-range)) .
If you write: `"* * 9-20 * * *"`, then an exception is triggered: **"Field (9-20) has an invalid range"**.
The version 1.7.1 works fine. In version 1.8.0 or 1.8.1 if you modify the range to include the step it does not work either, i.e.: `"* * 9-20/1 * * *",` triggers:  **"Field (9-20/1) has an invalid range".**

**Comment by casz** [comment]
Yup seeing the same issue with ranges.

**Comment by fcbvirus0k** [comment]
Same for me

**Comment by caiquejjx** [comment]
Same for me, if I let the time as "* * * * * *" it works normally but if i put any value this errro shows up

**Comment by ncb000gt** [comment]
Sorry about this, I'll take a look tonight and see what's up.

**Comment by drubetti** [comment]
Same for me, too! I am using `0 0 9-19 * * 1-6`.

**Comment by ncb000gt** [comment]
I just pushed up v1.8.2. Please try it out and let me know if you're still seeing issues. Thanks for reporting!

**Comment by drubetti** [comment]
It works now. Thank you!

**Comment by mastepanoski** [comment]
Yes, it works. Thanks

**Comment by ncb000gt** [comment]
Awesome. Glad to hear it. Thanks!
