### ISSUE TITLE
Can anyone write a cron expression for every 3rd mon,tue (NOTE: not every months 3rd mon,tue)

### ISSUE THREAD

**Issue by zakriyaalisabir** [kelektiv/node-cron#456]

**Comment by zakriyaalisabir** [comment]
@okuryu @KyleAMathews  @karjaneth  @anyone @neyric  @a0viedo  @Akim95

**Comment by ddnetters** [comment]
@zakriyaalisabir You should be able to find it [here](https://lmgtfy.com/?q=man+cron&iie=1)

**Comment by zakriyaalisabir** [comment]
Actually i tried many combinations like 0 0 0 ? 1 1#3,2#3 etc but that
didn't acheive what i desired

**Comment by nmay231** [comment]
It doesn't look like this is a standard even with regular cron jobs: https://stackoverflow.com/questions/9687278/cron-job-run-every-x-weeks-and-on-specific-days

You could run it *every* Mon/Tue and check if it's the third week.

```js
const week = 1000 * 60 * 60 * 24 * 7

new CronJob('* * * * * 1,2', () => {
  // Run every three weeks
  if (parseInt(Date.now() / week) % 3 === 0) {
    // Do important stuff...
  }
});
```

And please don't spam others with mentions. People do have a life outside of open source.

**Comment by ncb000gt** [comment]
I agree with @nmay231 on all accounts. :)

Does that help @zakriyaalisabir ?

**Comment by zakriyaalisabir** [comment]
Yeah
