### ISSUE TITLE
Preventing concurrent runs/builds?

### ISSUE THREAD

**Issue by ethanfoxIBM** [kelektiv/node-cron#459]
Hello.  I am working on a project where we used to have a bunch of cron jobs running in Jenkins, but business needs have dictated we need to migrate away from this resource and into an already-existing k8s infrastructure, whose devops pipeline unfortunately does not allow for the management of cronjobs.  As a result, next best possible thing is to stand up an application that manages the cronjobs as an abstraction, which is what we're doing with this library.

My question is, we have a certain job that runs every half hour.  However, because of the data that is being handled, it may take longer than 30minutes to execute this job.  In the past, in Jenkins, we were able to simply include `options { disableConcurrentBuilds() }` in our Jenkinsfile, and the next job would only run after the previous execution terminated.  However, i have done some digging through the docs and i haven't found anything that would allow for this with `cron`.  Perhaps I am missing something?  would love some additional insight on this, as well as any workarounds if this functionality does not exist out-of-the-box.

Thanks!

**Comment by nmay231** [comment]
I don't think this is a feature in the library, and it might add significant complexity if implemented (though maybe it should be :man_shrugging: ). In the meantime, you could try running the job in an asynchronous function and then wait for it the next time around.

```js
let previousJob

new CronJob('* */30 * * *', async () => {
  await previousJob

  previousJob = new Promise((resolve) => {
    // Data processing here
    resolve()
  }
})
```

However, I don't know what would happen when a job overlaps with two future jobs.

**Comment by ncb000gt** [comment]
In the past I've been very hesitant to expand the scope of this project for a few reasons, but mainly because my time is extremely limited. This kind of feature is one of those scope expansion things. There are some projects that act as schedulers with features like this and use this library underneath the hood.

Alternatively, you could use something like redis or a rdb as a mutex/lock for the execution of concurrent jobs and check that to see if executing is the right next step. This is the approach I've recommended in the past to people who have asked similar questions.

Does that help?

**Comment by ethanfoxIBM** [comment]
Hi @ncb000gt @nmay231 thanks for the responses.  It certainly sparks a few ideas; in the past we talked about wrapping the function around some sort of lock/semaphore so that it the job can't fire if the function is already executing.

What are some of the scheduler libraries you mentioned that use this one?  I think at this point we've already developed a pretty robust application with `cron`, concurrency notwithstanding, but would love to check out some other solutions as well, both for my education and as possible feature enhancements moving forward.

**Comment by ncb000gt** [comment]
@ethanfoxIBM This is one that I could find. I thought there were others, but couldn't find them in a quick search so you may have to dig a little more. :D

https://www.npmjs.com/package/agenda

**Comment by claytongulick** [comment]
Just want to jump in here with my $0.02.

First, @ncb000gt  I moved from agenda to this library. I had a bunch of problems with agenda, especially with multiple worker processes. Agenda-dash (the UI) was written as an experimental first project by the author, and they did a great job for a first project, but it wasn't at a quality level that I could use in production. YMMV.

Second, to help @ethanfoxIBM and others that are struggling with this, the scope of the issue for overlapping job runs is a long-standing problem (40 years) that has several strategies, but the most common, mature and solid solution I've seen is the classic lockfile (this is how pretty much everything in unix works).

Node has a robust and simple lockfile library that should make solving this problem a breeze on any platform and file system (even network file systems) https://github.com/moxystudio/node-proper-lockfile

HTH!

**Comment by claytongulick** [comment]
I just realized that my last comment was a bit sparse on details, so here's how I'm doing it.

In a file lock.js, I have a simply utility that looks like:
```
const lockfile = require('proper-lockfile');

module.exports = async function(name, fn) {
    let release;
    try {
        release = await lockfile.lock(name);
    }
    catch(err) {
        console.error(`Failed to aquire lock: ${name}, error: ${err}`);
        return;
    }

    try {
        await fn();
    }
    catch(err) {
        console.error(`Failed to execute lock function: ${err}`);
    }

    try {
        await release();
    }
    catch(err) {
        console.err(`Failed to release lock: ${name}, error: ${err}`);
    }
}
```

This will give you a wrapper function that'll let you do an exclusive lock on any function.

The way I structure my node-cron jobs is a single job per file, in a jobs folder (with an index.js). When I import index.js, all the jobs run. I also, however, want to be able to run jobs on-demand, from the cli. So my job files look like this:

```
let CronJob = require('cron').CronJob;
let path = require('path');
let Sync = require('../etl/legacy/sync');
let winston = require('winston');

let job_name = path.basename(__filename);

async function job_function() {
    winston.info(`Starting job: ${job_name}`)
    try {
        await lock(__filename, async () => {
            await Sync.run({families: true, new_only: true});
        });
    }
    catch(err) {
        winston.error(err);
    }
}


if(require.main == module) {
    job_function();
}
else {
    let job = new CronJob({
        cronTime: '0 * * * * *', //every minute
        onTick: job_function,
    });

    job.start();
    module.exports = job;
}
```

Where in this case Sync is an external helper library that handles some data synchronization, it can be any function though.

**Comment by ncb000gt** [comment]
Going to go ahead and close this, but we can revisit if this isn't sufficient to get you rolling.
