### ISSUE TITLE
Documentation: how to execute a job immediately

### ISSUE THREAD

**Issue by claytongulick** [kelektiv/node-cron#464]
Looking through the source, it looks like calling job.fireOnTick() will cause the job to execute immediately - this is a great feature to have in the public API. Perhaps it should be documented?

Or maybe an alias like "runNow()" that's a bit more user friendly?

Edit: just searched for fireOnTick in the main doc readme and found it! However, it wasn't clear to me from looking at it initially what it did, also there's a scary warning about "it matters, so only do it if you know what you're doing".  Since I just need a mechanism to run a job immediately, that's a bit concerning - maybe we can provide extra details in the documentation of that function for how/why it matters?

Thanks!

**Comment by claytongulick** [comment]
User story: I'm building a UI around jobs, their execution, next run, history, etc...

I want a button on the screen with the list of jobs that says "Run Now" so that the user can immediately execute (for example) a data refresh.

**Comment by intcreator** [comment]
this functionality is possible with the `runOnInit` command which is documented. it is not recommended to use `fireOnTick()` unless absolutely necessary
