### ISSUE TITLE
 You can not stop, but delete the work?

### ISSUE THREAD

**Issue by MilyaushaShigapova** [kelektiv/node-cron#465]
You can not stop, but delete the work?

**Comment by ncb000gt** [comment]
I'm not sure what you're looking for here. Can you elaborate a bit and explain what you're trying to do?

**Comment by MilyaushaShigapova** [comment]
there is a function -job.stop().
she stops work
Is there a function that completely destroys processes?

**Comment by ncb000gt** [comment]
When you call `stop()`, the timeout is cleared. Is that what you are asking about?

**Comment by intcreator** [comment]
closing as stale. feel free to reopen if you have more information to add
