### ISSUE TITLE
Run a cron job between two dates

### ISSUE THREAD

**Issue by omazin** [kelektiv/node-cron#466]
I want a cron job to run every minute starting from February 8, 10:00AM until February 28, 10:00AM. Is there a functionality for this use case? Should I manually detect the start date and invoke `start` method of a job and then detect the end date and invoke the `stop` method?

**Comment by ncb000gt** [comment]
You could setup a cron with the following syntax that should get you close to what you want: `* * * 2 *`

Then you can check the time and date values for your specific use case. Does that help?

**Comment by omazin** [comment]
> You could setup a cron with the following syntax that should get you close to what you want: `* * * 2 *`

Yes, but I would go with the "every minute" pattern `0 */1 * * * *` or specify ranges for my use case as follows `0 */1 * 8-28 1 *` and make sure it would not go again from 8th to 28th in the next years.
Was actually looking for some convenient options e.g. `startDate` to tell the cron when it needs to start a cron job automatically and `endDate` which would stop the cron job automatically as soon as it reaches the date. But it looks there aren't any so will need to manually check for specific dates and invoke `start` / `stop`
