### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by AfanasievN** [kelektiv/node-cron#470]
<img width="1330" alt="Снимок экрана 2020-02-20 в 10 09 04" src="https://user-images.githubusercontent.com/25581141/74909285-070c4d00-53c9-11ea-8170-97b7ea7a729d.png">

**Comment by ncb000gt** [comment]
Can you share some code to help debug?

**Comment by mryellow** [comment]
https://github.com/kelektiv/node-cron/issues/408

**Comment by ncb000gt** [comment]
#467 #469

**Comment by mikelam14** [comment]
I realized the error would show whenever my CPU utilization is too high (>9x%). That might cause some delay of code and affect something.

**Comment by ncb000gt** [comment]
I pushed up a PR with some changes to allow a "soft warning". Can you please test and report back?

**Comment by kasir-barati** [comment]
@mikelam14 Can you give me a script which reproduce/potentially reproduce the same issue?

**Comment by intcreator** [comment]
closing in favor of #467
