### ISSUE TITLE
Getting error for adding 7 digit subexpression

### ISSUE THREAD

**Issue by PankajGadia16** [kelektiv/node-cron#473]
Trying to execute expression "* * * 1 12 ? *", but got invalid expression error.
expression is validated at http://www.cronmaker.com/.

Kindly help is understanding such expressions.

This issue is extension for https://github.com/agenda/agenda/issues/953

**Comment by ncb000gt** [comment]
The cron ranges supported are noted here: https://github.com/kelektiv/node-cron#cron-ranges

Sorry about the issue you ran into.

Drop the last `*` and you should be ok. Let me know if it still has issues.

**Comment by intcreator** [comment]
closing as stale
