### ISSUE TITLE
Make _getNextDateFrom "public"

### ISSUE THREAD

**Issue by emilio-notable** [kelektiv/node-cron#476]
Because of some special requirements we have in our app we need to be able to tell if a job was supposed to run in the previous X minutes (or even better, when was the last time the job was supposed to execute).

I think we were able to achieve this using the method `_getNextDateFrom`, passing it a date in the past (instead of the current date like `sendAt` does), but i guess this method was not intended to be public, and might change its signature in the future.

Would you guys be open to making this method "public" and part of the documentation, and/or creating a new method similar to `sendAt` but that would go in reverse and return the last X times the job was supposed to run?

If you guys think this would be a good idea i can try to spend some time to create a PR

**Comment by LeraAl** [comment]
Our team also has the same requirements. 
We will be grateful if you can make it public

**Comment by ncb000gt** [comment]
I'm happy to review a pr for this especially considering that more than one person have a need. :)

Thanks!

**Comment by LeraAl** [comment]
@emilio-notable would you have time to work on this issue?
 If you don’t have the opportunity right now, we could do it

**Comment by emilio-notable** [comment]
@LeraAl go for it, i haven't started on this yet
