### ISSUE TITLE
Executing two times per hour instead of one

### ISSUE THREAD

**Issue by caiquejjx** [kelektiv/node-cron#481]
` async cronjob_updateDB() {
    const job = new CronJob(
      "0 0/40 * * * *",
      async () => {
        await equipmentController.update();
      },
      null,
      true,
      "America/Sao_Paulo"
    );
  },`

That's the code of my job, i want it to execute every 40 minutes and it does execute when the clock reaches 40 min but it also executes when the clock reach 00 minutes... for example it will execute 15:00 and 15:40 and i want it to execute only 15:40.. is there something wrong with the cron string I used?

**Comment by joeflateau** [comment]
your syntax is wrong. `0/40` means "every 40th minute from 0".  if you want it to fire only at the 40th minute, then you simply want `0 40 * * * *`

**Comment by caiquejjx** [comment]
Worked, thanks

**Comment by joeflateau** [comment]
no prob
