### ISSUE TITLE
Skip/queue if already running

### ISSUE THREAD

**Issue by joeflateau** [kelektiv/node-cron#482]
I have a task that runs every few minutes and occasionally takes several minutes to complete. I would like the option to skip a tick if a handler for a previous tick is still running. I propose adding an option `concurrentTickHandling` which would have a default value of `runAsScheduled` which behaves exactly the same as now. But an alternate value of `skipIfAlreadyRunning` which would skip starting a new job of a previous one is still running. The callback list would each be mapped and passed to `Promise.all` to track whether the previous run has completed. Potentially, down the road, another alternate of `queueIfAlreadyRunning` which would schedule the next ticks to run immediately after the completion of the previous tick.

I'm happy to implement if you'd entertain this in **node-cron** but wanted to check before doing the work/sending a PR

**Comment by ncb000gt** [comment]
I'd be happy to review a PR for this. Thanks.
