### ISSUE TITLE
.stop() is not working for real time

### ISSUE THREAD

**Issue by ivayloc** [kelektiv/node-cron#487]
I  have set up a cron job for a specific date and time, but when I call `job.stop()` on it, it is still executed.

**Comment by ncb000gt** [comment]
Can you provide a base sample that replicates what you're seeing? We have tests that use the `job.stop()` functionality so I'd be surprised if this wasn't working. But, I'm happy to take a look.

**Comment by ivayloc** [comment]
This is how I am using it:
```javascript
const job = new CronJob({
  cronTime: new Date(req.body.dateTime),
  onTick: async () => {},
  start: false,
  timeZone: timeZoneName,
})
```

**Comment by MoSattler** [comment]
I have the same problem

**Comment by MoSattler** [comment]
I got the same problem in tests.
```typescript
    it('some test', async () => {
      job.start();
      job.stop();
    });
```

the job never quits. I get 
> Jest did not exit one second after the test run has completed.
>
> This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.

**Comment by intcreator** [comment]
can you reproduce the issue by adapting one of the tests? https://github.com/kelektiv/node-cron/blob/master/tests/cron.test.js
