### ISSUE TITLE
Something went wrong. cron reached maximum iterations

### ISSUE THREAD

**Issue by amit221** [kelektiv/node-cron#497]
Time Zone: "" - Cron String: 1 0,10,20,30,40,50 * * * * - UTC offset: +00:00 - current Date: Thu May 14 2020 05:00:20 GMT+0000

**Comment by validkeys** [comment]
I actually just received this issue as well: 

```
Time Zone: "" - Cron String: 0 * * * * * - UTC offset: -04:00 - current Date: Thu May 14 2020 13:33:06 GMT+0000
```

**Comment by ncb000gt** [comment]
I pushed up a PR with some changes to allow a "soft warning". Can you please test and report back?

**Comment by intcreator** [comment]
closing in favor of #467
