### ISSUE TITLE
Cron Reached Maximum Iteration

### ISSUE THREAD

**Issue by angeloanan** [kelektiv/node-cron#498]
Suddenly and randomly, my program crashed with an error that told me to file an Issue.

The code that's used is [available here](https://github.com/angeloanan/Discord-KawalCOVID19-Webhook/blob/master/index.js#L11)

The error mentions that I'll need to include this:
```Time Zone: "" - Cron String: 0 0,10,20,30,40,50 * * * * - UTC offset: +07:00 - current Date: Thu May 14 2020 17:30:18 GMT+0000```

**Comment by yetithefoot** [comment]
Mine is here

```
18|metrics | 2020-05-26 03:37:42: Error: Something went wrong. cron reached maximum iterations.
18|metrics | 2020-05-26 03:37:42: 						Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
18|metrics | 2020-05-26 03:37:42: 						Time Zone: "" - Cron String: 0 0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58 * * * * - UTC offset: +00:00 - current Date: Tue May 26 2020 03:36:11 GMT+0000
18|app | 2020-05-26 03:37:42:     at CronTime._getNextDateFrom (.../node_modules/cron/lib/cron.js:235:12)
18|app | 2020-05-26 03:37:42:     at CronTime.sendAt (.../node_modules/cron/lib/cron.js:156:17)
18|app | 2020-05-26 03:37:42:     at CronTime.getTimeout (.../node_modules/cron/lib/cron.js:175:29)
18|app | 2020-05-26 03:37:42:     at CronJob.start (.../node_modules/cron/lib/cron.js:613:31)
18|app | 2020-05-26 03:37:42:     at Timeout.callbackWrapper [as _onTimeout] (.../node_modules/cron/lib/cron.js:665:29)
18|app | 2020-05-26 03:37:42:     at listOnTimeout (internal/timers.js:531:17)
18|app | 2020-05-26 03:37:42:     at processTimers (internal/timers.js:475:7)
```

**Comment by ncb000gt** [comment]
I pushed up a PR with some changes to allow a "soft warning". Can you please test and report back?

**Comment by christianto88** [comment]
I have the same issues too. It happens yesterday with the same error

**Comment by TomlDev** [comment]
Same error to me, yesterday 2020-06-15T22:00:00.010Z:

`

/srv/sw-server/node_modules/cron/lib/cron.js:235
 throw new Error(
 ^

Error: Something went wrong. cron reached maximum iterations.
Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
 Time Zone: "" - Cron String: 5 0 0 * * * - UTC offset: +02:00 - current Date: Tue Jun 16 2020 00:00:23 GMT+0200
    at CronTime._getNextDateFrom (/srv/sw-server/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/srv/sw-server/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/srv/sw-server/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/srv/sw-server/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/srv/sw-server/node_modules/cron/lib/cron.js:665:29)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)      

`

**Comment by lk77** [comment]
Hello,

same error for me :
```
["Error: Something went wrong. cron reached maximum iterations.\n\t\t\t\t\t\tPlease open an  issue (https:\/\/github.com\/kelektiv\/node-cron\/issues\/new) and provide the following string\n\t\t\t\t\t\tTime Zone: \"\" - Cron String: 0,30 * * * * * - UTC offset: +02:00 - current Date: Wed Jun 24 2020 08:30:59 GMT+0200"]
```

**Comment by intcreator** [comment]
closing in favor of #467
