### ISSUE TITLE
ES Modules Support

### ISSUE THREAD

**Issue by romap0** [kelektiv/node-cron#503]
If I try to import `CronJob` from `cron` module I get this error.

```js
import { CronJob } from 'cron';
         ^^^^^^^
SyntaxError: The requested module 'cron' does not provide an export named 'CronJob'
```

Please add support for named imports.

**Comment by L-U-C-K-Y** [comment]
Would also be interested in having ES Modules support.

**Comment by camel113** [comment]
what about something like
`import cron from "cron";`
and then 
```
const job = new cron.CronJob(
  "0 0 10 * * *",
  () => {
    logger.info("It's CRON JOB TIME");
  },
  null,
  true,
  "Europe/Paris"
);
```

**Comment by antoine-souesme-needone** [comment]
You can add ES Modules support by installing `@types/cron`.

**Comment by intcreator** [comment]
I'm able to use `cron` with imports so I'm going to close this
