### ISSUE TITLE
Hour step not working.

### ISSUE THREAD

**Issue by defaultDeveloper** [kelektiv/node-cron#505]
I want to run a the cron every 4 hrs.
I used '0 * */4 * * *',and it just executes every second now.

**Comment by Saun25** [comment]
I was using linux crontab with seconds value. Instead used  '0  */4 * * *' but it is running every 2 hours for some reason.

**Comment by TechchainBinhCQ** [comment]
@defaultDeveloper let try `0 0 */4 * * *`

**Comment by defaultDeveloper** [comment]
Doesn't work,tried it,that why I settled for the one I stated. Also I am running it in dev cluster but the crons are running inconsistently,every 2-4 hours.

**Comment by TechchainBinhCQ** [comment]
@defaultDeveloper did you run it in cluster mode?
Could you provide your snip code?

**Comment by defaultDeveloper** [comment]
Are you asking about Node.js cluster? I will try to provide the snip if possible.

**Comment by defaultDeveloper** [comment]
'0 */4 * * *' this worked for me. But initially 3-4 calls were inconsistent,firing every 2-4 hours and then after that became stable and started firing every 4 hours. Nothing else was modified.

**Comment by TechchainBinhCQ** [comment]
It's too strange! hmm...

**Comment by defaultDeveloper** [comment]
What I suspect is that for hours the cron time tries to align the hours like, 00:00 -> 04:00 -> 08:00. so if we start the job at say 8:22, the subsequent crons will try to align the time with say 9 or 10 or so on. I don't have time to go through the code else I would have.

**Comment by HassanKanj** [comment]
@defaultDeveloper I am also having issues when using hours in this format `*/number` (e.g `*/4`,...), so I am currently testing it using the commas format instead, which seems to be more accurate so far (e.g. `1,5,9,etc..`)

**Comment by defaultDeveloper** [comment]
> '0 */4 * * *' this worked for me. But initially 3-4 calls were inconsistent,firing every 2-4 hours and then after that became stable and started firing every 4 hours. Nothing else was modified. 

Check this out, in my local system as well as in dev/test it is working fine. Tried with node version 8 -12

**Comment by HassanKanj** [comment]
@defaultDeveloper, yeah it seems it gets consistent after that, but the problem for me is that it is important that I don't even have these few inconsistent calls at the beginning, especially that I am calling an API, and each call removes from my daily quota.

**Comment by defaultDeveloper** [comment]
@HassanKanj oh I see,my use case didn't require it to be consistent outright.
