### ISSUE TITLE
Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by katariyamilan** [kelektiv/node-cron#508]
Error: Something went wrong. cron reached maximum iterations. Please open an issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string Time Zone: "" - Cron String: 0 * * * * * - UTC offset: +00:00 - current Date: Thu Jul 09 2020 18:00:03 GMT+0000 at CronTime._getNextDateFrom (/var/www/html/sails_project/node_modules/cron/lib/cron.js:235:12) at CronTime.sendAt (/var/www/html/sails_project/node_modules/cron/lib/cron.js:156:17) at CronTime.getTimeout (/var/www/html/sails_project/node_modules/cron/lib/cron.js:175:29) at CronJob.start (/var/www/html/sails_project/node_modules/cron/lib/cron.js:613:31) at Timeout.callbackWrapper [as _onTimeout] (/var/www/html/sails_project/node_modules/cron/lib/cron.js:665:29) at ontimeout (timers.js:498:11) at tryOnTimeout (timers.js:323:5) at Timer.listOnTimeout (timers.js:290:5)

**Comment by lautaroramos** [comment]
#478

**Comment by kasir-barati** [comment]
@katariyamilan Can you give me a script which reproduce/potentially reproduce the same issue?

**Comment by intcreator** [comment]
closing in favor of #467
