### ISSUE TITLE
Cron reached maximum iterations

### ISSUE THREAD

**Issue by Gp2mv3** [kelektiv/node-cron#509]
I received this error in prod and the container restarted.
What should I do? Just create an issue here ?

Something went wrong. cron reached maximum iterations.
Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string

Time Zone: "" - Cron String: 0 * * * * * - UTC offset: +02:00 - current Date: Mon Jul 13 2020 21:09:22 GMT+0000

**Comment by intcreator** [comment]
closing in favor of #467
