### ISSUE TITLE
Cron doesn't work when it should be running a few days later.

### ISSUE THREAD

**Issue by sevadagrigoryan12** [kelektiv/node-cron#512]
cron expression example:  `0 0 8 19 6 *`.
Cron does not cause any errors and no logs.
Additional info:  In cases where it should be launched on the same day or, for example, every day, it works as expected.

**Comment by stefankirchfeld** [comment]
same here, cron is not working if there is a longer time between scheduled starts...job just does not run

**Comment by intcreator** [comment]
[this test](https://github.com/kelektiv/node-cron/blob/master/tests/cron.test.js#L574) tests execution times one month apart and it passes. could you adapt that test to illustrate this issue if you're still experiencing it?

**Comment by sheerlox** [comment]
Please update to the latest version of `cron` (`v2.4.1` as of now).
Closing this for now, if this issue still exists feel free to reopen!
