### ISSUE TITLE
How to get Meaningful Next Date

### ISSUE THREAD

**Issue by SpencerWF** [kelektiv/node-cron#520]
Using the nextDates function you can get an array of the next x number of onTick times.  An array of Objects with zero functions appears to be returned, how do you get the actual time of day at which the onTick will occur?

**Comment by P4sca1** [comment]
Hey @SpencerWF 👋
https://github.vom/P4sca1/cron-schedule allows you to do that.

**Comment by intcreator** [comment]
the API has changed since you opened this issue but currently `nextDates` returns an array of Luxon DateTime objects. you can use Luxon formatting options if you need a string that displays the date and time
