### ISSUE TITLE
cron reached maximum iterations

### ISSUE THREAD

**Issue by suruaku** [kelektiv/node-cron#522]
Time Zone: "" - Cron String: 0 0,10,20,30,40,50 * * * * - UTC offset: +00:00 - current Date: Fri Jul 24 2020 21:30:19 GMT+0000
Time Zone: "" - Cron String: 0 0,10,20,30,40,50 * * * * - UTC offset: +00:00 - current Date: Fri Jul 24 2020 01:30:44 GMT+0000

I am running node app on node v14.5.0 and cron version ^1.8.2.

**Comment by suruaku** [comment]
Closed because there is already report for the same issue.

**Comment by lautaroramos** [comment]
#478

**Comment by kasir-barati** [comment]
@suruaku Can you give me a script which reproduce/potentially reproduce the same issue?
