### ISSUE TITLE
Allow for multiple cron schedules

### ISSUE THREAD

**Issue by adrfantini** [kelektiv/node-cron#523]
With Cron, if one wants to run every day at 00:00 and at 13:30, one has to create two separate cron entries.
This is also the case with this package: one needs to create multiple jobs. Is there any way this can be taken care of in a single job, like for example passing an Array as first parameter of CronJob?

**Comment by intcreator** [comment]
unfortunately no, and this is not a planned feature at the moment. what you can do is make a cron builder function that takes an array and spins up a job for every cron time in the array though. should be very simple to implement
