### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by denis23x** [kelektiv/node-cron#526]
Hello i got this error:

Time Zone: "" - Cron String: 0 0,30 8,9,10,11,12,13,14,15,16,17,18,19,20 * * * - UTC offset: +03:00 - current Date: Tue Sep 08 2020 17:00:09 GMT+0300

**Comment by kasir-barati** [comment]
@denis23x Can you share a simple repo that can/potentially can reproduce bug again
