### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by GregyFun** [kelektiv/node-cron#529]
Error: Something went wrong. cron reached maximum iterations.
                                                Please open an  issue (https://g
ithub.com/kelektiv/node-cron/issues/new) and provide the following string
                                                Time Zone: "" - Cron String: 0 *
 * * * * - UTC offset: +00:00 - current Date: Fri Sep 04 2020 12:25:24 GMT+0000
    at CronTime._getNextDateFrom (/root/safe/server/node_modules/cron/lib/cron.j
s:235:12)

**Comment by kasir-barati** [comment]
@GregyFun Can you share a simple repo that can/potentially can reproduce bug again

**Comment by intcreator** [comment]
closing in favor of #467
