### ISSUE TITLE
can remove moment timezone package ?

### ISSUE THREAD

**Issue by LinboLen** [kelektiv/node-cron#530]
moment timezone same like is too big. it depends on moment

maybe just use tz-offset instead

**Comment by idinium96** [comment]
Just wondering if `cron` still uses `moment-timezone`. This is from [tf2autobot](https://github.com/idinium96/tf2autobot) package-lock.json file.
I have cloned `cron` and run `npm install`, but I can't find `moment-timezone` but `luxon`, so why is it in tf2autobot still required `moment-timezone`?
![image](https://user-images.githubusercontent.com/47635037/101272851-05323f80-37cb-11eb-97e8-70ad16acdd55.png)

**Comment by Shogobg** [comment]
The package on NPM have not been updated with the latest version of the GIT repository.
NPM package still uses moment-timezone.
If you want to use this package without moment, use `"cron": "github:kelektiv/node-cron",` in your package.json

**Comment by idinium96** [comment]
I see. that explains it. Thanks a bunch 👍
I hope all the latest changes got pushed to the NPM package soon.

**Comment by intcreator** [comment]
the NPM repo version now uses Luxon in place of Moment
