### ISSUE TITLE
Invalid Range

### ISSUE THREAD

**Issue by entoroadun** [kelektiv/node-cron#531]
The goal is a cronjob which is done every morning at 6 o'clock in the months July to December.

I have tried the following: '0 0 6 * 6-11 *'.
Result: Error: Field (6-11) has an invalid range

I then tried this: '0 0 6 * 6,7,8,9,10,11 *'.
Result: No error

**Comment by PQMISSCMP** [comment]
valid range are 0-6

**Comment by entoroadun** [comment]
> valid range are 0-6

As far as I understood it, in addition to the Linux cron at position 1 the second was used and so position 5 is for the months. So there should be a range of 0 - 11.

**Comment by raptor1989** [comment]
I have the same problem:
"0 7 * 1,2,3,10,11,12 *" - is vaild on https://crontab.guru/
but in the app:
Error: Field (1,2,3,10,11,12) value is out of range

Why?

**Comment by PQMISSCMP** [comment]
representa los dias de la semana, no los dia del mes.

**Comment by entoroadun** [comment]
> representa los dias de la semana, no los dia del mes.

A copy of the documentation:
----------------8<----------------------------------------
Cron Ranges
When specifying your cron values you'll need to make sure that your values fall within the ranges. For instance, some cron's use a 0-7 range for the day of week where both 0 and 7 represent Sunday. We do not. And that is an optimisation.

Seconds: 0-59
Minutes: 0-59
Hours: 0-23
Day of Month: 1-31
Months: 0-11 (Jan-Dec)
Day of Week: 0-6 (Sun-Sat)
---------------8<-----------------------------------------

Pos 1: Seconds
Pos 2: Minutes
Pos 3: Hours
Pos 4: Day of Month
Pos 5: Months
Pos 6: Day of Week

**Comment by intcreator** [comment]
I added a test for this in the PR I just mentioned. feel free to take a look. I can't duplicate your issue in the test

**Comment by intcreator** [comment]
closing as stale/can't reproduce
