### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by kwypchlo** [kelektiv/node-cron#533]
Reporting an issue as per request in the error:

`Time Zone: "" - Cron String: 0 0,5,10,15,20,25,30,35,40,45,50,55 * * * * - UTC offset: +00:00 - current Date: Sun Oct 18 2020 11:40:42 GMT+0000`

**Comment by kasir-barati** [comment]
@kwypchlo Can you share a simple repo that can/potentially can reproduce bug again.

**Comment by kwypchlo** [comment]
Sorry but I abandoned using the project due to this issue some time ago, unfortunately I'm not able to provide a reproduction step any more.
