### ISSUE TITLE
Pass job instance as onTick callback parameter

### ISSUE THREAD

**Issue by antoine-pous** [kelektiv/node-cron#544]
Actually we can't manipulate the job from it's callback.

It would be really cool to be able to pause it and update it depending the task itself.

For this use case the simplest way is to pass the CronJob instance as parameter for `onTick` and `onComplete`.

Here's a small use case:
```ts
const exec = async (job: CronJob) => {
  job.stop()
  // Do the job...
  job.start()
}
new CronJob('* * * * * *', exec, () => {}, true)
```

**Comment by mayerlench** [comment]
Cant you do this by just passing in the instance like this?

```
var runCron = async function (job: CronJob) {
   console.log("CRON running", job.running)
}

var cronJob = new CronJob({
    cronTime: '0 */5 * * * *',
    onTick: () => runCron(cronJob),
    start: true
})
```
