### ISSUE TITLE
Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by rubenstolk** [kelektiv/node-cron#551]
```Time Zone: "" - Cron String: 0,5,10,15,20,25,30,35,40,45,50,55 * * * * * - UTC offset: +01:00 - current Date: Thu Jan 21 2021 14:06:07 GMT+0000```

**Comment by MelodicCrypter** [comment]
I'm also experiencing this issue, just today.

**Comment by intcreator** [comment]
closing in favor of #467
