### ISSUE TITLE
Time Zone: "" - Cron String: 0 * * * * * - UTC offset: +00:00 - current Date: Thu Feb 04 2021 12:42:14 GMT+0000

### ISSUE THREAD

**Issue by hardikbutani222** [kelektiv/node-cron#552]
i have used cron in every minute.
cronTime: '0 */1 * * *'
but i got this error.

**Comment by Shogobg** [comment]
@hardikbutani222 the cron string that you use '0 */1 * * *' has only 5 groups - 'minute(0) hour(*/1) day(*) month(*) weekday(*)'. This package requires a sixth group for the seconds - this is why you get an error.

Try:
'0 */1 * * * *'

**Comment by intcreator** [comment]
closing as stale/answered
