### ISSUE TITLE
Able to edit or delete or destroy scheduled Jobs

### ISSUE THREAD

**Issue by manjufy** [kelektiv/node-cron#558]
Hi,
I'm dynamically creating new schedules based on date-time (not using cron expression). However, I need to be able to control these jobs at some point later.
Ex:
Let's say I have 5 schedules
```
new CronJob(today, jobHandler, null, true, 'Asia/Singapore');
new CronJob(todayAtMidNight, jobHandler, null, true, 'Asia/Singapore');
new CronJob(tomorrowAt4am, jobHandler, null, true, 'Asia/Singapore');
new CronJob(tomorrowAt5am, jobHandler, null, true, 'Asia/Singapore');
new CronJob(tomorrowAt6am, jobHandler, null, true, 'Asia/Singapore');
```
Imagine that each of the above jobs schedules a different date times,
I want to be able to edit a few of the Jobs to change the Date and Time if they have not run yet.

Would I be able to get a list of future Jobs or is there a method to be able to get the list and reload them with the new scheduled date time.

**Comment by muhammadtalhas** [comment]
I do this by storing them in a data structure (such as a map) and use the `.stop()` function and then recreating them. 

You'll need to manage the retrieval and such yourself. For example I store "jobs" in a database with a unique ID. Once I load them into my app (by createing `CronJob`s, I store them in a `Map` where the key is the unique ID. When I go to edit them, I retrieve the `CronJob` object by unique ID, stop the `CronJob` and create a new object.

**Comment by manjufy** [comment]
@muhammadtalhas That's a very good idea. Thanks for Sharing.

I did the same but database level, When I edit the record, I end up creating a new record, marking the old one with a flag (active/abort = false).
When the CronJob runs, I will retrieve the Job from DB again and check for the flag if it's not active, ignore running the Job.

**Comment by erhancan256** [comment]
ya aga ben bunu değişken adıyla delete edemiyorum
