### ISSUE TITLE
Something went wrong. cron reached maximum iterations

### ISSUE THREAD

**Issue by Amityadavv** [kelektiv/node-cron#559]
Time Zone: "" - Cron String: 0 0,4,8,12,16,20,24,28,32,36,40,44,48,52,56 * * * * - UTC offset: +05:30 - current Date: Sun Mar 14 2021 22:54:14 GMT+0000

**Comment by Sampaguitas** [comment]
Hi @Amityadavv,

Having the same issue here. I see that you closed this issue: how did you fix it?
