### ISSUE TITLE
[FR]: Add a "started" state

### ISSUE THREAD

**Issue by mkikets99** [kelektiv/node-cron#562]
on `CronJob` instance i founded an running state which is true while job is currently running.
What if i want to check when job is somewhere called by start method?

for example:
Later in code i can use
```javascript
if(!cronjob.started) cronjob.start();
```
to check if job is enabled (at least once)

**Comment by intcreator** [comment]
this should get you the functionality you need. I think it's kind of a niche use case to see if the job has been started once so I don't think it needs to be explicitly implemented at the moment

```js
var CronJob = require('cron').CronJob;
var job = new CronJob(
    '* * * * * *',
    function() {
        console.log('You will see this message every second');
    },
);

job.start();
job.wasStarted = true; // just add your own property to the object after starting

setTimeout(function() {
    console.log(job.wasStarted);
}, 3500);
```
