### ISSUE TITLE
Time Zone: "" - Cron String: 0 0 1 * * * - UTC offset: +06:00 - current Date: Thu Jun 17 2021 01:00:20 GMT+0600

### ISSUE THREAD

**Issue by msrumon** [kelektiv/node-cron#570]
Today I got this email from PM2 saying `Error: Something went wrong. cron reached maximum iterations.`. And I was instructed to create a new issue. Let me know what other information you guys need. Also let me know if I can help in any way by contributing into it. Thanks in advance and have a great day.

**Comment by intcreator** [comment]
closing in favor of #467
