### ISSUE TITLE
Not triggered with month specific crons

### ISSUE THREAD

**Issue by frankforpresident** [kelektiv/node-cron#571]
I've noticed when I use crons that are month specific, they aren't executed. Only when using alterative single values it does work.

What doesn't work:
9,29,49 * * 6 *

What does work:
9,29,49 * * JUN *
9,29,49 * * * *

**Comment by hehejiuhuizhe** [comment]
In the doc you can see:
Months: 0-11 (Jan-Dec)

So 6 means July.

**Comment by intcreator** [comment]
unfortunately this package currently differs from the Linux spec with numbers representing months. I want to align this package with the Linux spec as part of v4

feel free to reopen if you're describing a different issue than this
