### ISSUE TITLE
How to stop all cron jobs?

### ISSUE THREAD

**Issue by jackmatrix** [kelektiv/node-cron#573]
I was testing `cron` for node-js several month ago and I created some jobs. However, since then, these jobs execute everyday (since several months) and I cannot stop it.

I read the docs but I cannot figure out how to stop it. I've tried to execute :

```javascript
const cron = require("cron");

const job = new cron.CronJob(time, () => {
        ...
      });
      job.stop(); 
```

Without success.

Any recommendation ?

**Comment by frbuceta** [comment]
> I was testing `cron` for node-js several month ago and I created some jobs. However, since then, these jobs execute everyday (since several months) and I cannot stop it.
> 
> I read the docs but I cannot figure out how to stop it. I've tried to execute :
> 
> ```js
> const cron = require("cron");
> 
> const job = new cron.CronJob(time, () => {
>         ...
>       });
>       job.stop(); 
> ```
> 
> Without success.
> 
> Any recommendation ?

Add all crons to an array and then loop through the array by calling job.stop()

```js
const cron = require("cron");
const cronList = []

cronList.push(new cron.CronJob(time, () => {
        ...
}));

cronList.forEach((cron) => cron.stop()) 
```

**Comment by jackmatrix** [comment]
Thank you. Your solution worked very well. 

Issue solved.
