### ISSUE TITLE
[BUG] Setting runOnInit executes onTick with false start

### ISSUE THREAD

**Issue by frbuceta** [kelektiv/node-cron#574]
OnTick is running when runOnTick is true and start is false.

Any solution to this problem?

**Comment by ManuLpz4** [comment]
Same here, some workaround? 👀

**Comment by intcreator** [comment]
can you add a test case that illustrates this issue?

**Comment by ManuLpz4** [comment]
@intcreator 
> can you add a test case that illustrates this issue?

```ts
import { CronJob } from "cron";

const job = new CronJob({
    cronTime: "* * * * *",
    onTick: () => console.log("Tick"),
    runOnInit: true,
    startNow: false, // startNow is false by default anyway
});
```

It fires the tick every minute even if you never do `job.start()`

**Comment by intcreator** [comment]
I believe this is expected behavior for this option. there is [an existing test](https://github.com/kelektiv/node-cron/blob/master/tests/cron.test.js#L354) that shows that the function is called as soon as the job is defined but before it is started

**Comment by ManuLpz4** [comment]
> I believe this is expected behavior for this option. there is [an existing test](https://github.com/kelektiv/node-cron/blob/master/tests/cron.test.js#L354) that shows that the function is called as soon as the job is defined but before it is started. perhaps this could be clarified in the documentation

I think it makes no sense since you can achieve it with the config but you cant achieve the other behavior :/

You can config `runOnInit: true, startNow: true` but you can't config `runOnInit: true, startNow: false`

**Comment by intcreator** [comment]
actually when I run the [code example](https://github.com/kelektiv/node-cron/issues/574#issuecomment-1458407652) you provided it only runs once for me. what are you expecting `runOnInit` to do?

**Comment by ManuLpz4** [comment]
> actually when I run the [code example](https://github.com/kelektiv/node-cron/issues/574#issuecomment-1458407652) you provided it only runs once for me. what are you expecting `runOnInit` to do?

For "on init" we understand "on start" but if the cron didn't start yet I think the cron must not run.

How else can I achieve that behavior?

**Comment by intcreator** [comment]
I do think it's kind of confusing but `runOnInit` runs the function when the cron job is _initalized_ which is a different moment from when it is _started_.

```
import { CronJob } from "cron";

const job = new CronJob({
    cronTime: "* * * * *",
    onTick: () => console.log("Tick"),
    runOnInit: true,
    startNow: false,
});
// should see "Tick" once in the console even though job has not started
```
once you start the job you should see "Tick" in the console every second. does that make sense?

**Comment by ManuLpz4** [comment]
> I do think it's kind of confusing but `runOnInit` runs the function when the cron job is _initalized_ which is a different moment from when it is _started_.
> 
> ```
> import { CronJob } from "cron";
> 
> const job = new CronJob({
>     cronTime: "* * * * *",
>     onTick: () => console.log("Tick"),
>     runOnInit: true,
>     startNow: false,
> });
> // should see "Tick" once in the console even though job has not started
> ```
> 
> once you start the job you should see "Tick" in the console every second. if you are _not_ starting the job but you _are_ seeing "Tick" appear every second instead of just once, then that would be a bug. but you should be able to replicate that with a test case similar to the other test cases we have in the repo

Oh ok, you are right! I understood. Maybe its a bit confusing

How can I run the job when start?

**Comment by intcreator** [comment]
I'm not sure there's a built in way to do that, but it should be easy enough to extract your job to a function and then call that function when you call `job.start()`. honestly I'm not sure `runOnInit` is the greatest feature but since we have it we might want to add a `runOnStart` as well. feel free to make a PR for that if you'd like that functionality

**Comment by intcreator** [comment]
@frbuceta is this the issue you were experiencing or was there a bug where `runOnInit` caused the job to start? I cannot reproduce that behavior in the latest version

I'm going to close this for now since it's an old issue that I can't duplicate and I think it's getting a bit off topic. I'm still open to adding a `runOnStart` option if someone wants to make a PR but technically that's a different issue than what this issue initially covered
