### ISSUE TITLE
How to run cron every minute

### ISSUE THREAD

**Issue by soubhikchatterjee** [kelektiv/node-cron#576]
I am using the following code to run a cronjob every minute, I copied the corn expression from https://crontab.cronhub.io/ but it does not seem to console.log() every 1 minute.

```
var CronJob = require("cron").CronJob;

var date1 = new Date();

var job = new CronJob(
  "*/1 * * * *",
  function () {
    var date2 = new Date();
    const diffTime = Math.abs(date2 - date1);
    console.log(Math.round(diffTime / 1000));
  },
  null,
  true,
  "Asia/Kolkata"
);
job.start();

```

**Comment by alfanhui** [comment]
Try this expression: "0 */1 * * * *". This adds an extra astrisk and the initial 0 states which part (second) of the minute to run: 1:00.. 2:00, 3:00..

**Comment by intcreator** [comment]
`*/1` is actually the same as `*` in cron syntax so you can just use `0 * * * * *`. the main gotcha compared with other cron implementations is that node-cron has an spot for seconds so you have to set that as 0 to run on the 0th second of every minute
