### ISSUE TITLE
Cron instance becomes running = false after some time

### ISSUE THREAD

**Issue by alex-uw** [kelektiv/node-cron#580]
I have a long running process with cron job

```
const job = new CronJob('* * * * * *', async () => {
        // every second
        // some stuff
 });
```

After some time job.running becomes false. Not sure why, I do not call stop()..

I see there is `self.running = false;` ([source](https://github.com/kelektiv/node-cron/blob/9a5172661be362af2871b1c013f126775fbab808/lib/job.js#L167))

![image](https://user-images.githubusercontent.com/80477812/130604066-b1fbbf09-f7e2-4175-9849-4649416f78f7.png)

What is condition of this clause to be executed?

thx

**Comment by intcreator** [comment]
this is the cron job waiting for the next execution time. it does set `self.running = false` but as you can see unless the job is set to only run once, it calls `self.start()` four lines later to start the next iteration of the job. therefore the job should run indefinitely. it needs to restart every time it reaches an execution time so it can count down to the next execution time

how are you checking `job.running`? how long has your "long running" process been running? I've been using this library for months with Discord bots and I've never had issues with the job randomly stopping

going to close as can't reproduce; feel free to reopen if you have more details
