### ISSUE TITLE
How can I  run a cron Only once at an exact DateTime?

### ISSUE THREAD

**Issue by DhiaDjobbi** [kelektiv/node-cron#586]
### Description

Hello,
I want to run a cronjob **ONLY ONE TIME** at a very specific time which is : 
`let runAt= new Date(new Date().setHours(new Date().getHours() + 2));`
`runAt` is `Date('now')` + 2 hours.
I want to run my cronjob only one time at `runAt` and then I stop/kill the cron!
How can I achieve that?

**Comment by Hexagon** [comment]
It would be possible using https://github.com/hexagon/croner, by supplying correct hour and minute to pattern, and using option maxRuns:1. 

But as you request a very specific point in time (now + 2 hours), and only once, wouldnt the simplest solution be something like

```javascript
setTimeout(()=>{
   // the code... 
}, 3600*1000*2};
```

This will run the code exactly 2 hours from now
