### ISSUE TITLE
Cron job every five months, nextDates not calculated correctly

### ISSUE THREAD

**Issue by AntoninoBonanno** [kelektiv/node-cron#587]
### Description

Hi 
I'm trying to run a cron every 5 months at 10 am. But the nextdate is not calculated correctly.

```
const job = new CronJob(`* 0 10 1 */5 *`, () => {
    // My Job
}, null, true, 'Europe/Rome');
console.log((new Date()).toISOString() , job.nextDates().toISOString())
```

Output: 
Now: 2021-11-10T18:33:56.415Z
nextDates:  2022-01-01T09:00:00.000Z

I expect the nextDates is: 2022-04-01T09:00:00.000Z

My tests: 
`* 0 10 1 */1 *` -> (nextDates:  2021-12-01T09:00:00.000Z)

`* 0 10 1 */2 *` -> (nextDates:  2022-01-01T09:00:00.000Z)

`* 0 10 1 */3 *` <- Not work (nextDates:  2022-01-01T09:00:00.000Z)

**Comment by mryellow** [comment]
#408

It's broken and no one is fixing it. Time to move on to another lib.

**Comment by Hexagon** [comment]
Check out [github.com/hexagon/croner](https://github.com/hexagon/croner) for a great alternative, pay special attention to the section "Why another JavaScript cron implementation?"

**Comment by AntoninoBonanno** [comment]
Migrated to [github.com/hexagon/croner](https://github.com/Hexagon/croner)

but i have the same problem [https://github.com/Hexagon/croner/issues/52](https://github.com/Hexagon/croner/issues/52)
