### ISSUE TITLE
Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by tayler-king** [kelektiv/node-cron#591]
Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string

```js
Time Zone: "" - 
Cron String: 0 0,5,10,15,20,25,30,35,40,45,50,55 * * * * - 
UTC offset: +00:00 - 
current Date: Tue Dec 07 2021 21:40:31 GMT+0000
```

**Comment by mryellow** [comment]
#408

No one is doing anything about this critical fault.

**Comment by carlo23666** [comment]
https://github.com/kelektiv/node-cron/issues/599#issuecomment-1057806566

**Comment by intcreator** [comment]
@mryellow this should largely be fixed with the move to Luxon instead of Moment. if you're still having issues please refer to #467
