### ISSUE TITLE
Cron at specific time is not working

### ISSUE THREAD

**Issue by saito-kosuke** [kelektiv/node-cron#593]
### Description

Cron at specific time like below is not working
`@Cron("48 21 20 1 *")`
and
```
 @Cron("48 21 20 1 *, {
    name: "sendEmailToAllUsers",
    timeZone: "Asia/Tokyo",
  })
```

### Additional information

Minimum reproduction code
https://gist.github.com/saito-kosuke/d34e4f25f6d32cb3ab40518c3ac3b1f2

**Comment by Hexagon** [comment]
Check out [github.com/hexagon/croner](https://github.com/hexagon/croner) for a great alternative, pay special attention to the "Why another JavaScript cron implementation?"

**Comment by intcreator** [comment]
where is the `@Cron` syntax coming from? according to the docs a cron job should look like this:
```
var CronJob = require('cron').CronJob;
var job = new CronJob(
    '* * * * * *',
    function() {
        console.log('You will see this message every second');
    },
    null,
    true,
    'America/Los_Angeles'
);
// Use this if the 4th param is default value(false)
// job.start()
```

going to close this as stale for now and because it doesn't look like you're using the correct syntax. feel free to reopen if you have an update
