### ISSUE TITLE
Cron at a specific date not working

### ISSUE THREAD

**Issue by RaiahMohamedAmine** [kelektiv/node-cron#594]
### Description

Heey, so am trying to schedule a job at a specefic date, so am passing the date which is of type JS Date, but the job is triggered immediately.

You can see what am doing down here. 

### Screenshots

![Capture2](https://user-images.githubusercontent.com/45490821/150683209-22dfd4f8-a28d-4bda-ab7f-4fc1750692d4.PNG)

**Comment by LarsFlieger** [comment]
Can you provide one calling example? Like
```javascript
createCronJob(xxx, () => console.log("hey there!"))
```

**Comment by intcreator** [comment]
closing as stale
