### ISSUE TITLE
[BUG] setTime() starts the job even if the job was stopped

### ISSUE THREAD

**Issue by TaccolaA** [kelektiv/node-cron#598]
### ⭐ Suggestion

In 1.8.2, cronjob.setTime() stops the job and change the time but doesn't automatically starts the job back.
It would be nice to start it automatically, maybe checking first if it was running before.

### 💻 Use Cases

We sometimes want to change the cron expression of a running job. We have to call start() again which is a bit counter intuitive.

### ❌ Related Problems

On master, it looks like the setTime method already starts back the job after changing the time.
I can see the last release is from 2 years ago, is there any plan for a new release ?

**Comment by oh2th** [comment]
setTime() now starts the job, even if it was already stopped. Should not restart if job wasn't running.
Suggest there would be more logic in setTime() to check if job is running or not before setting the time.
