### ISSUE TITLE
Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by danieljoppi** [kelektiv/node-cron#600]
Time Zone: "" - Cron String: * * * * * * - UTC offset: +00:00 - current Date: Fri Feb 25 2022 07:19:01 GMT+0000

**Comment by carlo23666** [comment]
https://github.com/kelektiv/node-cron/issues/599#issuecomment-1057806566

**Comment by intcreator** [comment]
closing in favor of #467
