### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations

### ISSUE THREAD

**Issue by nibinkjose** [kelektiv/node-cron#603]
Time Zone: "" - Cron String: 0 * * * * * - UTC offset: +00:00 - current Date: Sat Apr 02 2022 16:41:33 GMT+0000
0|SSN      | 2022-04-02 16:42:08 +00:00:     at CronTime._getNextDateFrom (/home/ubuntu/ssn-api/node_modules/cron/lib/cron.js:235:12)
0|SSN      | 2022-04-02 16:42:08 +00:00:     at CronTime.sendAt (/home/ubuntu/ssn-api/node_modules/cron/lib/cron.js:156:17)
0|SSN      | 2022-04-02 16:42:08 +00:00:     at CronTime.getTimeout (/home/ubuntu/ssn-api/node_modules/cron/lib/cron.js:175:29)
0|SSN      | 2022-04-02 16:42:08 +00:00:     at CronJob.start (/home/ubuntu/ssn-api/node_modules/cron/lib/cron.js:613:31)
0|SSN      | 2022-04-02 16:42:08 +00:00:     at Timeout.callbackWrapper [as _onTimeout] (/home/ubuntu/ssn-api/node_modules/cron/lib/cron.js:665:29)
0|SSN      | 2022-04-02 16:42:08 +00:00:     at ontimeout (timers.js:424:11)
0|SSN      | 2022-04-02 16:42:08 +00:00:     at tryOnTimeout (timers.js:288:5)
0|SSN      | 2022-04-02 16:42:08 +00:00:     at listOnTimeout (timers.js:251:5)
0|SSN      | 2022-04-02 16:42:08 +00:00:     at Timer.processTimers (timers.js:211:10)

**Comment by hirenthinkinfoservices** [comment]
Hello 
I have same issue
**Error:** 
Error: Something went wrong. cron reached maximum iterations.

Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string

Time Zone: "" - Cron String: 0,30 * * * * * - UTC offset: +05:30 - current Date: Sat Apr 09 2022 02:50:46 GMT+0000

**Comment by intcreator** [comment]
closing in favor of #467
