### ISSUE TITLE
Please point out that there is a backward-incompatible change

### ISSUE THREAD

**Issue by AnnAngela** [kelektiv/node-cron#611]
### Description

I found out that in V1.8.3, [this library changed it's internal data lib from `moment` to `luxon`](https://github.com/kelektiv/node-cron/commit/36c673b01a57dabbab1c96333a32d6cf3641cf51), and this is a backward-incompatible change.

Please make it clear in readme.md and change the major version number to let peoples know that.

### Screenshots

![QQ截图20220502214812](https://user-images.githubusercontent.com/9762652/166244971-ac9e12ee-d96a-4e71-a9ed-265dfd0ff81e.png)

**Comment by ncb000gt** [comment]
I deprecated 1.8.3 and released 2.0.0. I thought the `luxon` change had already been released. Sorry about that and thanks for calling it out.

**Comment by AnnAngela** [comment]
> I deprecated 1.8.3 and released 2.0.0. I thought the `luxon` change had already been released. Sorry about that and thanks for calling it out.

THX for response!
