### ISSUE TITLE
Breaking compatibility when updating from 1.8.2 to 1.8.3

### ISSUE THREAD

**Issue by Zhuull** [kelektiv/node-cron#612]
### Description

Please, make it clear when there is a backward-incompatble change in a minor version

In 1.8.2, this code worked  as intended:

```javascript
const cron = require('cron')
let myCronjob = new cron.job('0 */3 * * * *', myFunction, null, true, "Europe/Paris")
```

in 1.8.3 with the same code I got : 

```javascript
 > cron.job is not a constructor
```

According to the Readme I found that I can Indeed use the code below to fix it but that breaks my script and that is not what we could expect on a minor upgrade

```javascript
const cron = require('cron')
let myCronjob = new cron.CronJob('0 */3 * * * *', myFunction, null, true, "Europe/Paris")
// OR
let myCronjob = cron.job('0 */3 * * * *', myFunction, null, true, "Europe/Paris")
```

**Comment by ncb000gt** [comment]
Sorry about that. I must have missed this. It's been a while since I pushed a release. I deprecated 1.8.3 and released 2.0.0 instead. Thanks for calling it out.

**Comment by JuanJo4** [comment]
@ncb000gt maybe worth unpublishing 1.8.3 from npm to avoid breaking changes. I just ran into this issue because other package was using this, and the upgrade to 1.8.3 break the whole thing.

https://docs.npmjs.com/unpublishing-packages-from-the-registry#unpublishing-a-single-version-of-a-package

**Comment by intcreator** [comment]
hmm...but if packages depend on 1.8.3 wouldn't that for sure break them?

**Comment by sheerlox** [comment]
@JuanJo4 unfortunately, as intcreator stated, unpublishing from npm would break projects currently relying on this version. There is some [limitations on the side of npm](https://docs.npmjs.com/policies/unpublish) to prevent package maintainers from unpublishing in these situation.
The best we can do is deprecate it, which is already done.

>>> Regardless of how long ago a package was published, you can unpublish a package that:

- no other packages in the npm Public Registry depend on

- had less than 300 downloads over the last week

- has a single owner/maintainer

**Comment by sheerlox** [comment]
> > hmm...but if packages depend on 1.8.3 wouldn't that for sure break them?
> 
> will probably break them anyway because of the breaking compatibility added in 1.8.3, but I guess that's better than breaking it when installing because 1.8.3 is not found in the registry.

If they're using 1.8.3 they probably adapted their codebase.


> I was just exploring ideas to avoid hard times figuring out what was the breaking change, is it too crazy if a new version 1.8.4 is released just reverting the breaking change? in that way, packages depending on `~1.8.0`or `^1.0.0` will end up with 1.8.4 instead of 1.8.3 with the breaking change.

That seems like a very good idea at first, but because projects using 1.8.3 probably have no issue with it, that would introduce another breaking change on a minor version, which would cause the same problem all over again, wdyt?

**Comment by JuanJo4** [comment]
yeah, this version has been out since more than a year ago so very likely they already figured out and resolved the issue by upgrading or something, doesn't worth the effort.

Cool, thanks @sheerlox !
