### ISSUE TITLE
Unable to use utcOffset

### ISSUE THREAD

**Issue by dummy-account-practise** [kelektiv/node-cron#617]
### Description

I have a job

```js
someJob = new CronJob( '0 ${minutes} ${hours} * * ${targetday}', async () => {
   // job stuff
}, null, null, null, null, null, '5:30', null );
```

I've also started the job.

I have also tried giving the constructor an object with key-value pairs; cronTime, onTick ...etc etc.

But the utcOffset does not work and I am unable to figure out why. If I use the same job in a scenario that does not require me
to use offset, it works fine.

I am unable to find this in ANY code example except in a couple of git issues and even those do not work for me.
have tried giving numbers and string as offset.

Can someone show me a practical example? I have spent hours trying to make it work. also getting no errors.

**Comment by intcreator** [comment]
you can use [this example](https://github.com/kelektiv/node-cron/blob/master/tests/cron.test.js#L786) from the test suite. it needs to be in minutes as a number, the Luxon object is just convenience. I can look into updating the docs and adding an example

**Comment by intcreator** [comment]
updated the docs and examples in #652
