### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations

### ISSUE THREAD

**Issue by Sampaguitas** [kelektiv/node-cron#621]
Time Zone: "" - Cron String: 0,3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57 * * * * * - UTC offset: +01:00 - current Date: Wed Jul 13 2022 11:14:17 GMT+0000

**Comment by intcreator** [comment]
please close this issue and refer to the canonical issue at #467. if you get an error message telling you to open a new issue it's because you're using an old version of node-cron
