### ISSUE TITLE
Error: Invalid timezone.

### ISSUE THREAD

**Issue by DhananjayanSidhan** [kelektiv/node-cron#622]
### Description

timezone working only when time-zone is 'local' or 'utc'

	
	const job = new CronJob(
		'*/5 * * * * *',
		function () {
			const d = new Date();
			console.log(d);
		},
		null,
		true,
		'America/Los_Angeles'
	);

`Error: Invalid timezone.
    at new CT (/home/node_modules/cron/lib/time.js:75:11)
    at new CJ (/home/node_modules/cron/lib/job.js:62:19)
`

### Additional information

It will already working on cron@1.2.1 when I try to update it will throw error.

**Comment by Hexagon** [comment]
Try https://github.com/hexagon/croner if you want a working alternative 👍

**Comment by mohanagy** [comment]
Your pattern is wrong; it has extra asterisk

**Comment by intcreator** [comment]
can't reproduce
