### ISSUE TITLE
How many jobs can i schedule via node-cron?

### ISSUE THREAD

**Issue by YoussefAlmardini** [kelektiv/node-cron#623]
Hi all! 

I have a question!

For a notification client i want to schedule a job foreach notification i have. When notification is sent, job will be deleted.
But we are talking about 10000 notification or more per week. I wonder if this package can handle that amount of jobs. And where does the package saves the jobs under the hood? I want to make sure that my process will not be stopped because of cache problem or something.  I am using a `cron-job-manager` which uses `node-cron` as dependency.

Example: 
![Screenshot 2022-08-08 at 11 38 47](https://user-images.githubusercontent.com/32193161/183388336-5fc0471d-95db-4049-b0b9-b3bea6fbc2ac.png)

Thank you!

**Comment by michael-azogu** [comment]
they're held in memory as long as the program is running

to see the capacity you can create a mini repo to benchmark what point it starts to break

10k over a week isn't hard.

**Comment by intcreator** [comment]
correct, jobs are just stored in memory. node-cron is memory only. so the number of jobs you can have depends on the memory available and potentially CPU power

if you feel something specific about performance can be improved, you can reopen the issue. otherwise I'm going to close as answered
