### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations

### ISSUE THREAD

**Issue by vkbDevelop** [kelektiv/node-cron#627]
Time Zone: "" - Cron String: 0,10,20,30,40,50 * 5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 * * * - UTC offset: +03:00 - current Date: Wed Sep 14 2022 11:02:00 GMT+0300

**Comment by intcreator** [comment]
please close this issue and refer to the canonical issue at #467. if you get an error message telling you to open a new issue it's because you're using an old version of node-cron
