### ISSUE TITLE
Issue in cron job

### ISSUE THREAD

**Issue by narendersaini32** [kelektiv/node-cron#631]
Time Zone: "" - Cron String: 0 0,5,10,15,20,25,30,35,40,45,50,55 * * * * - UTC offset: +00:00 - current Date: Mon Nov 14 2022 03:32:46 GMT+0000
at CronTime._getNextDateFrom (/var/app/current/node_modules/cron/lib/cron.js:235:12)
Nov 14 03:42:37 ip-172-31-31-217 web: at CronTime.sendAt (/var/app/current/node_modules/cron/lib/cron.js:156:17)
Nov 14 03:42:37 ip-172-31-31-217 web: at CronTime.getTimeout (/var/app/current/node_modules/cron/lib/cron.js:175:29)
Nov 14 03:42:37 ip-172-31-31-217 web: at CronJob.start (/var/app/current/node_modules/cron/lib/cron.js:613:31)
Nov 14 03:42:37 ip-172-31-31-217 web: at Timeout.callbackWrapper [as _onTimeout] (/var/app/current/node_modules/cron/lib/cron.js:665:29)
Nov 14 03:42:37 ip-172-31-31-217 web: at listOnTimeout (node:internal/timers:559:17)
Nov 14 03:42:37 ip-172-31-31-217 web: at processTimers (node:internal/timers:502:7)

**Comment by intcreator** [comment]
closing in favor of #467
