### ISSUE TITLE
My Cron Job at a specified date isn't running at all

### ISSUE THREAD

**Issue by priyatham1188** [kelektiv/node-cron#641]
### Description

Hello,

I'm using this module to send out a reminder emails based on a particular date as per my app's business logic:

It's like when some hit a remind me after button in frontend and In the backend I'm writing this cron job to send out those reminder emails based on the dates accroding to our business logic.

Can you please let me know why do you think its not working?

Thanks!!!

### Screenshots

const date = new Date(moment(subdata.mealDate,'DD-MM-YYYY').subtract(1,'days').subtract(4,'hours').add(30,'seconds').tz('America/Halifax'))
    
    console.log('date',date);

    const job = new CronJob(date, function() {
      
      ejs.renderFile(emailUser, { data: MailObj }, (err, results) => {
        if (err) {
          logger.info('ERROR::::while sending foundsomerror' + err);
        }
        emailApi.sendEmailApi(
          `Scheduled Reminder `,
          'Scheduled Reminder ',
          results,
           subdata.billingAddress.email,
          'Mail sent failure',
          'Mail sent successfully',
          process.env.EMAIL_SENDER
        );
      });
      

    },null,true,'America/Halifax');

**Comment by elxeltor** [comment]
Hi, I'm not one of the authors, but I can ensure you're not providing enough information to help debug your issue.

is your method ever called ? have you tried to just console.log from inside the callback ? Are you sure the error isn't coming from your `ejs.renderFile` maybe you should provide an error message you're receiving so anyone can understand your issue.

Finally, you could try to create a small test project only containing only the CronJob creation with one of the dates you generated and check if that works.

**Comment by intcreator** [comment]
closing this as stale. feel free to reopen if you have more info
