### ISSUE TITLE
TypeError: n.format is not a function

### ISSUE THREAD

**Issue by lk77** [kelektiv/node-cron#643]
### Description

Hello,

i have an issue sometimes with node-cron,

i have this error :

```
TypeError: n.format is not a function
    at l._getNextDateFrom
```

it's seems to occur in the lib/time.js file, in the _getNextDateFrom function, and seems related to luxon, perhaps updating luxon fixes the issue i don't know

thanks

**Comment by intcreator** [comment]
the fix for this is merged and should be available in the next version update

**Comment by lk77** [comment]
thanks !

**Comment by GamerGirlandCo** [comment]
> the fix for this is merged and should be available in the next version update

which update?

**Comment by intcreator** [comment]
I don't have perms to publish to NPM yet, once I do I can get this fix out
