### ISSUE TITLE
Vulnerability found in the dependency

### ISSUE THREAD

**Issue by seidhkona** [kelektiv/node-cron#646]
### Description

luxon  1.0.0 - 1.28.1
Severity: high
Luxon Inefficient Regular Expression Complexity vulnerability - https://github.com/advisories/GHSA-3xq5-wjfh-ppjc

**Comment by ncb000gt** [comment]
Fixed in https://github.com/kelektiv/node-cron/pull/640 which I've published as v2.2.0.
