### ISSUE TITLE
*/59 * * * * * runs every minute twice (on second 59 and 00)

### ISSUE THREAD

**Issue by elxeltor** [kelektiv/node-cron#647]
### Description

When setting a cron job with `*/59 * * * * *` ,  the job runs twice every minute instead.
at second 59 (as expected) and the following second (00 of the following minute)

reproductible issue snippet:
```javascript
const { CronJob } = require('cron')
new CronJob('*/59 * * * * *', () => console.log((new Date()).toUTCString()), null, true, 'UTC')
```

### Screenshots
Output I got from running the code above

![image](https://user-images.githubusercontent.com/742976/211453742-87b3c254-eb97-4296-9dc1-f4243abfa077.png)

**Comment by Hexagon** [comment]
Thats the expected behavior of all cron implementations supporting stepping. Just as */15 will run on 0,15,30,45 every minute - */59 will run at 0,59.

If you want to exectute a function each 59th second you could use the interval feature of https://github.com/hexagon/croner
