### ISSUE TITLE
[FEATURE] CronJob.clearCallBacks() to clear all callbacks from a CronJob instance

### ISSUE THREAD

**Issue by oh2th** [kelektiv/node-cron#649]
### ⭐ Suggestion

Add a method clearCallbacks() to clear all the callbacks from CronJob that were added with addCallback().

### 💻 Use Cases

When re-setting the CronTime for a CronJob, I would like to clear all callbacks, so that I can apply new callbacks.

### ❌ Related Problems

none.

**Comment by intcreator** [comment]
if you're resetting the time and the callbacks would it be easier to just create a new job?

```js
var CronJob = require('cron').CronJob;
var job1 = new CronJob(
    '* * * * * *',
    function() {
        console.log(`original callback, every second`)
    },
    null,
    true,
);

setTimeout(function() {
    job1.stop();
    job1 = new CronJob(
        '*/2 * * * * *',
        function() {
            console.log(`new callback, every 2 seconds`)
        },
        null,
        true,
    );
}, 2500);
```
this is the output I get:
```
original callback, every second
original callback, every second
original callback, every second
new callback, every 2 seconds
new callback, every 2 seconds
new callback, every 2 seconds
new callback, every 2 seconds
```
feel free to make a PR, I guess it would be consistent with the other features but it's also fairly easy to work around

**Comment by intcreator** [comment]
closing as stale
