### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Ittakes007** [kelektiv/node-cron#650]
Time Zone: ""- Cron String: 0.09

UTC offset: -06:00 - current Date: Sun Feb 12 2023

13:55:02 GMT-0600

at CronTime. getNextDateFrom (C\Program

Files\Fing\resources\app.asar\node_modules\cron\lib\cron.js:235:12) at Cron Time.sendAt (C:\Program

Files Fing resources\app.asar\node_modules\cron\lib\cron.js:156:17) at CronTime.getTimeout (C:\Program

Files\Fing resources\app.asar\node_modules\cron\lib\cron.js:175:29) at CronJob.start (C:\Program

Files\Fing resources\app.asar\node_modules\cron\lib\cron.js:613:31) at Timeout.callbackWrapper [as_onTimeout] (C:\Program

Files Fing resources\app.asar\node_modules\cron\lib\cron.js:665:29) at listOn Timeout (internal/timers.js:554:17)

at process Timers (internal/timers.js:497:7)

**Comment by intcreator** [comment]
what exactly is the issue? this is just a stack trace

**Comment by intcreator** [comment]
going to close for now since there's not enough info. please edit the issue to include all fields from the [bug issue template](https://github.com/kelektiv/node-cron/blob/master/.github/ISSUE_TEMPLATE/bug_issue.yaml) if you would like to reopen
