### ISSUE TITLE
nextDate(s) returns date although job is stopped

### ISSUE THREAD

**Issue by sheerlox** [kelektiv/node-cron#660]
### Description

Hello, I have noticed a behavior that seems like a bug. Please let me know your view on this and I'll be happy to find some time to open a PR!

When stopping a job, subsequent calls to `nextDate()` / `nextDates()` still return a date even though the job won't be run since it is in a stopped state.

Here's a minimal reproduction:
```js
const CronJob = require("cron").CronJob;
const { DateTime } = require("luxon");

// prevent program from exiting
const process = require("process");
process.stdin.resume();

// create job (example from README)
const job = new CronJob(
  "* * * * * *",
  function () {
    console.log("You will see this message every second");
  },
  null,
  true,
  "America/Los_Angeles"
);

// wait for one execution, then
setTimeout(() => {
  // stop job
  job.stop();
  console.debug("-> Job stopped.");

  // log next date
  const n = job.nextDate().toLocaleString(DateTime.DATETIME_FULL);
  console.debug(`-> Job next date: ${n}`);
}, 1000);
```

Which results in:
```
$ node index.js 
You will see this message every second
-> Job stopped.
-> Job next date: April 13, 2023 at 5:36 AM PDT
```

In case you'd like me to open PR, what do you think would be the best behavior from those functions if the job is stopped? I see two options, ordered by relevance:
- return `null`;
- throw an error;
- something else?

Thanks in advance!

**Comment by intcreator** [comment]
this is interesting, I can see that intuitively it makes more sense for `nextDate()` to not supply any values if the job is stopped. however, even though it might be subtle, this could be a breaking API change that would require a major version update if we update how this works. I also want to make sure that we don't remove functionality unintentionally; for example we don't want to force people to start a job just to output what the next date would be and then immediately stop the job, but that sounds like a hack that might be implemented if we update this function. thoughts?

**Comment by oh2th** [comment]
It is useful that nextDate(s) do return the next scheduled value(s), even when the job is stopped. I'm using this information together with the job state to show the user when the next run would happen and if the job is enabled or disabled.

**Comment by sheerlox** [comment]
Yeah, actually that makes total sense that `nextDate(s)` would work this way, even if indeed it is a bit counter-intuitive, might be good to add to the README the fact it will answer even if the job is stopped, and that we have to check `.running` to account for that. If you'd like, that let me know, and I'll make a PR. Thanks for taking the time!
