### ISSUE TITLE
 Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by Gaurang2811** [kelektiv/node-cron#662]
"cron": "^1.8.2",

```
Time Zone: "" - Cron String: 0,15,30,45 * * * * * - UTC offset: +00:00 - current Date: Thu Apr 20 2023 14:05:54 GMT+0000
```

**Comment by intcreator** [comment]
closing in favor of #467. you're using an old version of cron; upgrading might fix some of the issues. you can also check for memory leaks or high CPU usage which might cause this
