### ISSUE TITLE
[FEATURE] Align with the UNIX cron format

### ISSUE THREAD

**Issue by sheerlox** [kelektiv/node-cron#666]
### ⭐ Suggestion

The library isn't following the UNIX cron format for `month` & `day-of-week`, which is counter-intuitive.

### Important notes
- we’d also probably have to support security updates in the old version for a while since upgrading for some people might be a big deal

### Resources
[UNIX cron format documentation](https://www.ibm.com/docs/en/db2oc?topic=task-unix-cron-format)

**Comment by intcreator** [comment]
yep agree on the security updates point. also if there are any API breaking changes we've been considering we'd want to bundle that into the next major version upgrade
