### ISSUE TITLE
Memory leak happening (only 2 cron running)

### ISSUE THREAD

**Issue by RohitLakh** [kelektiv/node-cron#676]
### Description

I have 2 cron jobs running along with the slack bot which runs once every day at a specific time, but every minute the memory consumption increases. The app is hosted on railway.app.

Memory graph using `node-cron`

![image](https://github.com/kelektiv/node-cron/assets/34619861/e3d598b7-519e-47d7-9f94-370685b1d47b)

I tried the same code using `cron` library from npm and the graph remains the same

Memory graph using `cron`
<img width="820" alt="image" src="https://github.com/kelektiv/node-cron/assets/34619861/a14b033f-5d0d-47b5-8d94-a279865a64a4">

### Screenshots

`node-cron`
![image](https://github.com/kelektiv/node-cron/assets/34619861/9d38b7a6-550f-4264-bdfd-e333175cae8b)

`cron`
<img width="837" alt="image" src="https://github.com/kelektiv/node-cron/assets/34619861/ca573209-0a9d-4eb6-a5e3-9a3188dee0fa">

**Comment by Hexagon** [comment]
@RohitLakh This repository is the `cron` package, you should post this issue at https://github.com/node-cron/node-cron which is npm package `node-cron`

**Comment by RohitLakh** [comment]
@Hexagon my bad, thanks for the heads up.
