### ISSUE TITLE
Cron is still running even when the server stopped

### ISSUE THREAD

**Issue by afdallah** [kelektiv/node-cron#680]
### Description

I have a simple node.js server that runs a cron job every minute and stores data in a database. The jobs are stored in an object using the ﻿cronJobs objet like this.
```
const cronJobs: Record<string, CronJob> = {};
cronJobs[id] = new CronJob(someConfig);
```

The issue occurs when the server is manually stopped, such as by using CTRL + C. I expected all the jobs to stop as well. However, upon checking the database, I discovered that the jobs continue running and saving data every minute.

Is this behavior expected? If so, is there a way to stop all the jobs without killing the node process? 
Since the `﻿cronJobs` object becomes empty when the server restarts, I can't rely on it. Should I persist the state to solve this issue?"

**Comment by sheerlox** [comment]
Hello @afdallah :wave: 

If you stop the Node process in which you loaded the jobs, then indeed the execution of the jobs should stop with it. Are running the jobs in a separate process that somehow doesn't get terminated with the main one?

Could you describe your setup in more detail? Are you using something like Express? How does your program start itself? Where/when does the code snippet you shared load the jobs?

> If so, is there a way to stop all the jobs without killing the node process?

Hitting Ctrl+C terminates the Node process in most setups, but maybe yours is different.
You can still stop all the jobs without terminating your server by looping over them and calling the `job.stop()` method for each.

**Comment by afdallah** [comment]
I'm using TRPC,  I have a `[procedure](https://trpc.io/docs/server/procedures)` / endpoint that will create and run the job.

here is how to reproduce the issue.

The procedure is triggered > it will create the cron job and run it > while it's still running the job > I stop the trpc server with CTRL + C. apparently the job still running in the background.

**Comment by sheerlox** [comment]
I have no experience with tRPC, but I can assure you that in a regular environment, your cronjob stops when stopping the server since it stops the Node process, and `cron` is JS code running in that same process.

The issue most likely comes from your code (or maybe the way tRPC works), so you should probably open an issue on StackOverflow in order to get the help you need ;) Best of luck!

**Comment by afdallah** [comment]
Let me see if I can reproduce it in a simple express js and put it here

**Comment by sheerlox** [comment]
hey @afdallah :wave: any update?

**Comment by joanklikin** [comment]
same happening here

**Comment by sheerlox** [comment]
@joanklikin thank you for reporting on this. Could you please provide more information? Are you using TRPC as well? If not, please describe your setup in more detail.
If you could provide a minimal example reproducing the issue that would be really helpful in debugging this.
Thanks in advance!

**Comment by joanklikin** [comment]
> sheerlox

Hi sheerlox, couldn't reproduce it since it eventually was an infrastructure issue, not a library issue sorry for the waste of time.

**Comment by sheerlox** [comment]
@joanklikin no problem, glad you find a solution and that library isn't involved :wink:
