### ISSUE TITLE
CronJob not picking up schedule?

### ISSUE THREAD

**Issue by Elindo586** [kelektiv/node-cron#691]
### Description

I am not sure if this is a real issue, or just bad code... but I am writing in here because there is no section for asking for help..

Apparently the CronJob is not picking up the schedule and firing right away..  I am using it in Express.js  .... 

Here is some code sample:

 ```
app.get("/test", function (req, res) {
  try {
res.send("moving");

const the1 =  function () {
     console.log("we got 1");
    };

const the2 =  function () {
     console.log("we got 2");
    };

    const starter = () => {
      var functions = [the1, the2];
      var timesRun = 0;
      var functionIndex = 0;
      var myIntervals = setInterval(function () {
        timesRun += 1;
        functions[functionIndex++]();
        if (timesRun === 2) {
          clearInterval(myIntervals);
        } else if (functionIndex == functions.length) functionIndex = 0;
      }, 10 * 1000);
    };

    const job = new CronJob(
      "* 42 12 * * *",
      starter(),
      console.log("is it showing before time?")
    );
    job.start();
  } catch (e) {
    console.log(e);
  }
});

```
^^^  Basically I have 2 functions running at a given interval...  I want to fire those functions to fire at a given time using CronJob.... but the CronJob doesn't seem to be responding as the 2 functions are starting right away and the the console.log() from the CronJob is shooting right away too...

I have tried to add a time zone, but I also get invalid time zone errors as well...

About 2 months ago I was running a different download from this very same npm cron, with pretty much the same type of code and it was working fine..

**Comment by sheerlox** [comment]
Hello @Elindo586, sorry about the delay!

Your issue is coming from the fact you are executing your function right away, instead of passing a reference to it:

```js
const job = new CronJob(
  "* 42 12 * * *",
  starter(), // <== this should be "starter" only, or "() => starter()"
```

This should solve your issue :) Don't hesitate to join our [Discord server](https://discord.gg/yyKns29zch) if you need further assistance or have any questions!
