### ISSUE TITLE
option to wait for callbacks completion on job.stop()

### ISSUE THREAD

**Issue by YannHulot** [kelektiv/node-cron#713]
### ⭐ Suggestion

Do not stop the jobs if the `onTick` function is being executed. Wait for this function to resolve first and then, resolve `job.stop()`

### 💻 Use Cases

Basically I am trying to gracefully shut down my cron jobs when deploying a new version of my back-end.

That means that ideally, I want to call `job.stop()` on all the ongoing jobs, Then once they are done, I want to close the DB connection and so on and so forth.

The problem is that those jobs are mostly doing async stuff, so if I call a `job.stop()` and my `onTick` function is currently running, then, I would like to wait for the `onTick` function to resolve before the `job.stop(`) function resolves itself so I don't close the DB connection before those jobs are done since they need it.

### Related

- https://github.com/kelektiv/node-cron/issues/556

**Comment by sheerlox** [comment]
related to #556 since both features need to watch for callbacks completion

**Comment by rohith1222004** [comment]
I noticed that PR #894 is linked to this issue for supporting async handling and job status tracking. Is this feature close to completion, or would you still like help working on it?
