### ISSUE TITLE
Cron reach maximum duration (Version 3.1.6)

### ISSUE THREAD

**Issue by hsjakobsen** [kelektiv/node-cron#847]
### Description

I am running a cron every 10 seconds and it crashed:

Error: Something went wrong. cron reached maximum iterations.
Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
`Time Zone: "" - Cron String: 0,10,20,30,40,50 * * * * * - UTC offset: +00:00 - current Date: Mon Jan 15 2024 23:02:36 GMT+0000`

### Expected Behavior

It should keep running

### Actual Behavior

It crashed as above

### Possible Fix

I don't know.

### Steps to Reproduce

Run cron with with 10 sec interval for a long period.

### Context

Our server is checking to calculate things every 10 seconds and if the cron stops running, it doesn't happen.

### Your Environment

- **`cron` version**: 3.1.6
- **NodeJS version**: 20.9.0
- **Operating System and version**:  RockyLinux 8.4 x64
- **TypeScript version (if applicable)**:  5.2.2

**Comment by sheerlox** [comment]
Hi, you're running on v2.0.0 at most. This is shown by the error message you encountered, [which has been changed in v2.1.0](https://github.com/kelektiv/node-cron/commit/520abed84076aa65bc2d836b07c0f9572770f96c).

This error [was fixed](https://github.com/kelektiv/node-cron/commit/c685c63a6d7fa86d6c8afca29b536b9da24e824b) in v2.4.1, so upgrading to at least that version will resolve your issue.
