### ISSUE TITLE
The current Date is not accurate.

### ISSUE THREAD

**Issue by 07ke** [kelektiv/node-cron#887]
### ⭐ Suggestion

I'm currently facing an issue with the accuracy of the Date in our system. The base time seems to be incorrect, and I would like to modify it so that it relies on an NTP (Network Time Protocol) service for synchronization. Could you provide guidance on how to achieve this?

### 💻 Use Cases

job.setNow(XXXX)

**Comment by sheerlox** [comment]
This is out of the scope of this library, and probably even out of the scope of Javascript or the JS runtime you're using.

This is an issue with the underlying OS, for which you gave no indication.

Here's a guide for the Debian system for example: [How To Set Up Time Synchronization on Debian 10](https://www.digitalocean.com/community/tutorials/how-to-set-up-time-synchronization-on-debian-10)
