### ISSUE TITLE
Library does not support '#' in cron expression

### ISSUE THREAD

**Issue by pratik-k2** [kelektiv/node-cron#896]
### Description

I passed **0 30 17 ? * 3#2** expression to trigger a process on 2nd Tuesday of every month at 5:30PM but the library throws exception `CronError: Field (dayOfMonth) cannot be parsed`.
Upon debugging, I found out that it the library does not honor '#' in the expression.

### Expected Behavior

'#' should be be honored as its considered into cron expression.

### Actual Behavior

Library throws exception when '#' is passed in cron expression: `CronError: Field (dayOfMonth) cannot be parsed`

### Steps to Reproduce

Ue expression **0 30 17 ? * 3#2** in any code snippet using the library.

### Context

I was trying to run a cron job.

### Your Environment

- **`cron` version**: 3.1.7
- **NodeJS version**: 18.16.0
- **Operating System and version**: macOS 14.6.1
- **TypeScript version (if applicable)**:
- **Link to your project (if applicable)**:

**Comment by sheerlox** [comment]
This library respects the UNIX cron syntax (cronie's cron), which does not support the `#` symbol.

However, we do plan on supporting it at some point. You can find the existing feature request here: 
- https://github.com/kelektiv/node-cron/issues/435

In the meantime, you can add a check in your `onTick` function to only execute on the second Thursday.
