### ISSUE TITLE
The console send me this error.

### ISSUE THREAD

**Issue by Unbisito** [kelektiv/node-cron#898]
Time Zone: "" - Cron String: 0,20,40 * * * * * - UTC offset: -07:00 - current Date: Tue Oct 22 2024 03:15:16 GMT+0000

**Comment by sheerlox** [comment]
Hi, this error message comes from an old bug we fixed in v2.4.1. Please take a look at the following issues for more information:
- https://github.com/kelektiv/node-cron/issues/847#issuecomment-1921470432
- https://github.com/kelektiv/node-cron/issues/885#issuecomment-2117026571
