### ISSUE TITLE
Module '"cron"' declares 'CronJob' locally

### ISSUE THREAD

**Issue by decoderid** [kelektiv/node-cron#906]
### Description

According to the documentation below, to perform the import in the following way:

```ts
import { CronJob } from 'cron';
```

However, an error occurs that results in:

```log
Module '"cron"' declares 'CronJob' locally.
```

To perform the correct import in TypeScript, use:

```ts
import { CronJob } from 'cron/dist';
```

### Expected Behavior

```ts
import { CronJob } from 'cron';
```

### Actual Behavior

```ts
import { CronJob } from 'cron/dist';
```

### Steps to Reproduce

```ts
import { CronJob } from 'cron';

CronJob.from({
    cronTime: '* * * * * *',
    onTick: () => {
        console.log('Testing Cron')
    },
    start: true
})
```

### Context

no

### Your Environment

- **`cron` version**: 3.1.8
- **NodeJS version**: 21.7.2
- **Operating System and version**: Windows 11
- **TypeScript version**: 5.6.3

**Comment by intcreator** [comment]
I can duplicate this issue using Node v20 and v21, but it works fine in Node v22 and v23. it's possible that a recent package update inadvertently broke support for Node <v22. will look into it

**Comment by sheerlox** [comment]
Thanks for the report, it should be fixed by https://github.com/kelektiv/node-cron/pull/908.

This issue will be updated once the PR is merged and a new version is released. Feel free to re-open it then if the problem is still occurring on the latest version.
