### ISSUE TITLE
Caught exception: Something went wrong. cron reached maximum iterations

### ISSUE THREAD

**Issue by qwertyshark** [kelektiv/node-cron#925]
My unraid server just crashed and checking the logs I see a message pointing to this github telling me to open an issue and provide the following string as the explanation for the issue:

```
#012#011#011#011#011#011#011Time Zone: "" - Cron String: 0 * * * * * - UTC offset: +01:00 - current Date: Thu 
Dec 12 2024 15:22:05 GMT+0100
```

Console log:

```
- Dec 12 15:22:09 Tower unraid-api[7855]: ⚠️ Caught exception: Something went wrong. cron reached maximum iterations.#012#011#011#011#011#011#011Please open an issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string#012#011#011#011#011#011#011Time Zone: "" - Cron String: 0 * * * * * - UTC offset: +01:00 - current Date: Thu 
Dec 12 2024 15:22:05 GMT+0100

-Dec 12 15:22:14 Tower unraid-api[7855]: ⚠️ UNRAID API crashed with exit code 1
-Dec 12 16:31:04 Tower init: Switching to runlevel: 0
```

Hope it helps.

**Comment by intcreator** [comment]
this bug [was fixed in 2.4.1](https://github.com/kelektiv/node-cron/commit/c685c63a6d7fa86d6c8afca29b536b9da24e824b). we are currently on version 3.3.1. I recommend updating to the latest version to get the latest updates.

**Comment by sheerlox** [comment]
@limetech hello 👋 we're getting a lot of reports of that issue from what's seems to be your API.

Could you forward this bug report to the relevant person from the Unraid team?

Thanks in advance!

**Comment by sheerlox** [comment]
Looks like I tagged the wrong person, cc @ljm42 @elibosley @pujitm

**Comment by elibosley** [comment]
My apologies that our users are contacting you - this is probably on our end. I'll be sure to upgrade our cron version and get this out in our next release. Should be in the next couple weeks.

**Comment by sheerlox** [comment]
No issue, thanks for the swift response!
